// Generated by Cypress Author on 2026-07-16
// Covers valuation page API endpoints (issue #672):
//   GET    /api/watchlist/v1/list
//   POST   /api/watchlist/v1/create
//   DELETE /api/watchlist/v1/delete/:ticker
//   GET    /api/valuation/v1/detail/:ticker

describe('Valuation Page API', () => {
  const KNOWN_TICKER = 'BBCA'
  const FAKE_TICKER = 'XXXXZZ'

  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  // ─── watchlist list ───────────────────────────────────────────────────────

  describe('GET /api/watchlist/v1/list', () => {
    it('returns 200 with the watchlist as an array for an authenticated user', () => {
      cy.getWatchlist().then((response) => {
        expect(response.status).to.eq(200)
        expect(response.body.success).to.be.true
        expect(response.body.data).to.be.an('array')
      })
    })

    it('returns 401 when unauthenticated', () => {
      cy.clearApiAuth()
      cy.getWatchlistNoAuth().then((response) => {
        expect(response.status).to.eq(401)
        expect(response.body.error).to.exist
      })
    })
  })

  // ─── watchlist create/delete ──────────────────────────────────────────────

  describe('POST /api/watchlist/v1/create + DELETE /api/watchlist/v1/delete/:ticker', () => {
    // Cleanup runs regardless of test outcome so a failed assertion never
    // leaves KNOWN_TICKER stuck in the watchlist for subsequent runs.
    afterEach(() => {
      cy.deleteWatchlistTicker(KNOWN_TICKER)
    })

    it('adds a valid IDX ticker to the watchlist and returns 201', () => {
      cy.createWatchlistTicker({ ticker: KNOWN_TICKER }).then((response) => {
        expect(response.status).to.eq(201)
        expect(response.body.success).to.be.true
        expect(response.body.data.ticker).to.eq(KNOWN_TICKER)
      })
    })

    it('deletes the ticker it just created and returns 200', () => {
      cy.createWatchlistTicker({ ticker: KNOWN_TICKER }).then(() => {
        cy.deleteWatchlistTicker(KNOWN_TICKER).then((response) => {
          expect(response.status).to.eq(200)
          expect(response.body.success).to.be.true
        })
      })
    })

    it('returns 400 when ticker is missing from the request body', () => {
      cy.createWatchlistTicker({}).then((response) => {
        expect(response.status).to.eq(400)
        expect(response.body.error).to.exist
      })
    })

    it('returns 400 when ticker contains non-letter characters', () => {
      cy.createWatchlistTicker({ ticker: 'BB4A1' }).then((response) => {
        expect(response.status).to.eq(400)
        expect(response.body.error).to.exist
      })
    })

    it('returns 400 when ticker exceeds 10 characters', () => {
      cy.createWatchlistTicker({ ticker: 'ABCDEFGHIJK' }).then((response) => {
        expect(response.status).to.eq(400)
        expect(response.body.error).to.exist
      })
    })

    it('returns 409 when adding a ticker already in the watchlist', () => {
      cy.createWatchlistTicker({ ticker: KNOWN_TICKER }).then(() => {
        cy.createWatchlistTicker({ ticker: KNOWN_TICKER }).then((response) => {
          expect(response.status).to.eq(409)
          expect(response.body.error).to.exist
        })
      })
    })

    it('returns 422 when the ticker is not found on Yahoo Finance', () => {
      cy.createWatchlistTicker({ ticker: FAKE_TICKER }).then((response) => {
        expect(response.status).to.eq(422)
        expect(response.body.error).to.exist
      })
    })

    it('returns 401 when creating without authentication', () => {
      cy.clearApiAuth()
      cy.createWatchlistTickerNoAuth({ ticker: KNOWN_TICKER }).then((response) => {
        expect(response.status).to.eq(401)
        expect(response.body.error).to.exist
      })
    })

    it('returns 400 when deleting with an invalid ticker format', () => {
      cy.deleteWatchlistTicker('BB4A1').then((response) => {
        expect(response.status).to.eq(400)
        expect(response.body.error).to.exist
      })
    })

    it('returns 404 when deleting a ticker not in the watchlist', () => {
      cy.deleteWatchlistTicker('NOTINLIST').then((response) => {
        expect(response.status).to.eq(404)
        expect(response.body.error).to.exist
      })
    })

    it('returns 401 when deleting without authentication', () => {
      cy.clearApiAuth()
      cy.deleteWatchlistTickerNoAuth(KNOWN_TICKER).then((response) => {
        expect(response.status).to.eq(401)
        expect(response.body.error).to.exist
      })
    })
  })

  // ─── valuation detail ─────────────────────────────────────────────────────

  describe('GET /api/valuation/v1/detail/:ticker', () => {
    it('returns 200 with the expected valuation shape for a valid ticker', () => {
      cy.getValuationDetail(KNOWN_TICKER).then((response) => {
        expect(response.status).to.eq(200)
        expect(response.body.success).to.be.true

        const data = response.body.data
        expect(data).to.include.all.keys([
          'ticker',
          'fundamentals',
          'monteCarlo',
          'risk',
          'analystConsensus',
          'pbvAnalysis',
          'dcfValuation',
          'assessments',
          'overall',
        ])
        expect(data.ticker).to.eq(KNOWN_TICKER)
        expect(data.fundamentals).to.be.an('object')
        expect(data.monteCarlo).to.be.an('object')
        expect(data.risk).to.be.an('object')
        expect(data.analystConsensus).to.be.an('object')
        expect(data.pbvAnalysis).to.be.an('object')
        expect(data.dcfValuation).to.be.an('object')
        expect(data.assessments).to.be.an('object')
      })
    })

    it('returns 400 for an invalid ticker format', () => {
      cy.getValuationDetail('BB4A1').then((response) => {
        expect(response.status).to.eq(400)
        expect(response.body.error).to.exist
      })
    })

    it('returns 404 when the ticker is not found on Yahoo Finance', () => {
      cy.getValuationDetail(FAKE_TICKER).then((response) => {
        expect(response.status).to.eq(404)
        expect(response.body.error).to.exist
      })
    })

    it('returns 401 when unauthenticated', () => {
      cy.clearApiAuth()
      cy.getValuationDetailNoAuth(KNOWN_TICKER).then((response) => {
        expect(response.status).to.eq(401)
        expect(response.body.error).to.exist
      })
    })
  })
})
