// Generated by Cypress Author — 2026-06-02
// Updated by Cypress Author — 2026-06-03
// Added sections O–Q: dual-role JSON format rendering (Running Coach / Performance Analyst /
// Summary cards), markdown fallback rendering, and history modal with dual-role items.
// Covers: Analytics AI Card UI states — all sections share the same component;
//         tests use section=weekly_distance (sectionId="weeklydistance") as representative.
//
// AUTH STRATEGY:
//   All describe blocks use setupPageStubs() which:
//     1. cy.setupApiAuthCookies() — sets Supabase auth token cookie
//     2. cy.enableBypass() — sets cypress-bypass cookie to skip middleware auth call
//
// WAIT STRATEGY:
//   Tests do NOT use cy.wait('@getInsights') for initial load — instead they wait for the
//   expected UI element that appears after the insights response is processed.
//
// DESIGN: One describe = one scenario = one page visit (via beforeEach). This eliminates
//   Cypress intercept accumulation issues that arise from multiple before() hooks.
//
// INTERCEPT PRIORITY NOTE:
//   Cypress resolves multiple matching intercepts LIFO (last-in, first-out), but a more
//   specific matcher (e.g. query object) always beats a plain string matcher regardless of
//   order. Therefore, all tests use plain string matchers only — no query-specific matchers.
//
// NOTE: Duplicate-insight guard (preventing re-generate when already pending) is a
//       coverage gap — the backend does not yet expose a guard endpoint; mark BLOCKED.

import { TEST_IDS } from '../../../fixtures/test-ids.js'
import { ROUTES } from '../../../fixtures/routes.js'

const IDS = TEST_IDS.running_analytics
const ANALYTICS_URL = ROUTES.running_analytics
const INSIGHTS_PATH = '/api/running/v1/ai/insights'
const GENERATE_URL = '/api/running/v1/ai/insights/generate'

// Section under test — sectionId strips underscores per AnalyticsAICard logic
const SECTION = 'weekly_distance'

// Convenience selectors for the weekly_distance section card elements
const AI_CARD = `#${IDS.ai_card_weeklydistance}`
const AI_LOADING = `#${IDS.ai_loading_weeklydistance}`
const AI_EMPTY = `#${IDS.ai_empty_weeklydistance}`
const AI_GENERATE_BTN = `#${IDS.ai_generate_btn_weeklydistance}`
const AI_PENDING = `#${IDS.ai_pending_weeklydistance}`
const AI_CONTENT = `#${IDS.ai_content_weeklydistance}`
const AI_ERROR = `#${IDS.ai_error_weeklydistance}`
const AI_RETRY_BTN = `#${IDS.ai_retry_btn_weeklydistance}`
const AI_REFRESH_BTN = `#${IDS.ai_refresh_btn_weeklydistance}`
const AI_STALENESS_BADGE = `#${IDS.ai_staleness_badge_weeklydistance}`
const AI_HISTORY_BTN = `#${IDS.ai_history_btn_weeklydistance}`
const AI_HISTORY_MODAL = `#${IDS.ai_history_modal_weeklydistance}`

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

// Completed insight fixture
const completedInsight = (overrides = {}) => ({
  id: 'insight-completed-1',
  status: 'completed',
  is_valid: true,
  content: '## Weekly Distance\n\nGreat consistency this week. Keep it up.',
  data_refs: { section: SECTION },
  created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  ...overrides,
})

const pendingInsight = () => ({
  id: 'insight-pending-1',
  insight_type: 'analytics_summary',
  status: 'pending',
  is_valid: false,
  content: null,
  created_at: new Date().toISOString(),
})

const setupPageStubs = () => {
  // Set Supabase auth cookie + bypass middleware auth check
  cy.setupApiAuthCookies()
  cy.enableBypass()

  // Page-level stubs — prevent real Supabase/API calls on page load
  cy.intercept('GET', '**/rest/v1/rt_users*', {
    statusCode: 200,
    body: [{ id: 'test-user-id', onboarding_complete: true }],
  })
  cy.intercept('GET', '/api/running/v1/activities*', {
    statusCode: 200,
    body: { data: [], meta: { total: 0, page: 1, limit: 200 } },
  }).as('getActivities')
  cy.intercept('GET', '/api/running/v1/performance-trends*', {
    statusCode: 200,
    body: { data: [] },
  })
  cy.intercept('GET', '/api/running/v1/dashboard*', {
    statusCode: 200,
    body: {
      data: {
        weekly_stats: {
          current: { distance_m: 0, duration_sec: 0, count: 0, avg_pace_sec_per_km: null },
          prev: { distance_m: 0, duration_sec: 0, count: 0, avg_pace_sec_per_km: null },
        },
        training_load: {
          acwr: null,
          acute_load_7d: null,
          chronic_load_28d: null,
          status: 'no_data',
        },
        recent_activities: [],
        calendar_activities: [],
        health_today: { logged: false, data: null },
      },
    },
  })
  // Stub fetchAnalyticsStaleness — use pathname to match exactly (no query params)
  cy.intercept(
    { method: 'GET', pathname: '/api/running/v1/ai/insights/staleness' },
    {
      statusCode: 200,
      body: { data: { is_stale: false, latest_activity_at: null, latest_insight_at: null } },
    }
  )
}

// Stub the insights list endpoint.
// Uses pathname-based URL object so Cypress matches the path exactly (ignoring query params)
// without accidentally matching /ai/insights/staleness (a sub-path).
const stubInsights = (body) => {
  cy.intercept({ method: 'GET', pathname: INSIGHTS_PATH }, { statusCode: 200, body }).as(
    'getInsights'
  )
}

const visitAndWait = () => {
  cy.viewport(1280, 900)
  cy.visit(ANALYTICS_URL, { failOnStatusCode: false, timeout: 30000 })
  cy.wait('@getActivities', { timeout: 15000 })
  cy.get(AI_CARD, { timeout: 15000 }).scrollIntoView()
}

// ---------------------------------------------------------------------------
// A. Auth guard
// ---------------------------------------------------------------------------

describe('Analytics AI Card UI — auth guard', () => {
  it('unauthenticated visit redirects to /login', () => {
    cy.clearAllCookies()
    cy.clearAllLocalStorage()
    cy.visit(ANALYTICS_URL, { failOnStatusCode: false })
    cy.url().should('include', '/login')
  })
})

// ---------------------------------------------------------------------------
// B. Loading skeleton — insights fetch in-flight
// ---------------------------------------------------------------------------

describe('Analytics AI Card UI — loading skeleton', () => {
  beforeEach(() => {
    setupPageStubs()
    // Delay response so loading skeleton is still visible when assertions run
    cy.intercept({ method: 'GET', pathname: INSIGHTS_PATH }, (req) => {
      req.reply({ delay: 5000, statusCode: 200, body: { data: [] } })
    }).as('getInsights')
    visitAndWait()
  })

  it('renders AI card wrapper and loading skeleton while fetch is in-flight', () => {
    cy.get(AI_CARD).scrollIntoView().should('exist')
    cy.get(AI_LOADING).scrollIntoView().should('exist')
  })
})

// ---------------------------------------------------------------------------
// C. Empty state
// ---------------------------------------------------------------------------

describe('Analytics AI Card UI — empty state', () => {
  beforeEach(() => {
    setupPageStubs()
    stubInsights({ data: [] })
    visitAndWait()
    cy.get(AI_EMPTY, { timeout: 10000 }).scrollIntoView()
  })

  it('shows empty state copy and enabled Generate Insights button', () => {
    cy.get(AI_EMPTY).should('be.visible').and('contain.text', 'No recommendations yet')
    cy.get(AI_GENERATE_BTN)
      .scrollIntoView()
      .should('be.visible')
      .and('contain.text', 'Generate Insights')
      .and('not.be.disabled')
  })
})

// ---------------------------------------------------------------------------
// D. Generate flow — clicking "Generate Insights" fires POST to generate endpoint
// ---------------------------------------------------------------------------

describe('Analytics AI Card UI — generate flow', () => {
  beforeEach(() => {
    setupPageStubs()
    stubInsights({ data: [] })
    visitAndWait()
    cy.get(AI_EMPTY, { timeout: 10000 }).scrollIntoView()
  })

  it('clicking Generate Insights fires POST with analytics_summary type', () => {
    cy.intercept('POST', GENERATE_URL, {
      statusCode: 200,
      body: { queued: true, message: 'Analytics summary queued' },
    }).as('postGenerate')

    // After POST succeeds, component calls GET again — stub it to return pending
    // so the generate button disappears (empty state is replaced by pending state)
    cy.intercept(
      { method: 'GET', pathname: INSIGHTS_PATH },
      {
        statusCode: 200,
        body: { data: [pendingInsight()] },
      }
    ).as('getInsightsAfterGenerate')

    cy.get(AI_GENERATE_BTN).scrollIntoView().click()
    cy.wait('@postGenerate')

    // POST must have been called with analytics_summary type
    cy.get('@postGenerate')
      .its('request.body')
      .should('deep.include', { type: 'analytics_summary' })

    // After generate, the empty state should be replaced by pending or another state
    cy.get(AI_EMPTY, { timeout: 10000 }).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// E. Content state
// ---------------------------------------------------------------------------

describe('Analytics AI Card UI — content state (valid insight)', () => {
  beforeEach(() => {
    setupPageStubs()
    stubInsights({ data: [completedInsight()] })
    visitAndWait()
    cy.get(AI_CONTENT, { timeout: 10000 }).scrollIntoView()
  })

  it('renders content with recommendation text, Refresh button; hides loading/empty/error', () => {
    cy.get(AI_CONTENT).should('be.visible').and('contain.text', 'Great consistency this week')
    cy.get(AI_REFRESH_BTN).scrollIntoView().should('be.visible').and('contain.text', 'Refresh')
    cy.get(AI_LOADING).should('not.exist')
    cy.get(AI_EMPTY).should('not.exist')
    cy.get(AI_ERROR).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// F. Staleness badge — insight older than 24h
// ---------------------------------------------------------------------------

describe('Analytics AI Card UI — staleness badge (stale insight)', () => {
  beforeEach(() => {
    setupPageStubs()
    stubInsights({
      data: [
        completedInsight({
          id: 'insight-stale',
          content: '## Stale\n\nOld recommendation.',
          created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
        }),
      ],
    })
    visitAndWait()
    cy.get(AI_CONTENT, { timeout: 10000 }).scrollIntoView()
  })

  it('shows staleness badge when insight is older than 24 hours', () => {
    cy.get(AI_STALENESS_BADGE)
      .scrollIntoView()
      .should('be.visible')
      .and('contain.text', 'Outdated')
      .and('contain.text', 'newer activity data available')
  })
})

// ---------------------------------------------------------------------------
// G. No staleness badge — insight within 24h
// ---------------------------------------------------------------------------

describe('Analytics AI Card UI — no staleness badge (fresh insight)', () => {
  beforeEach(() => {
    setupPageStubs()
    stubInsights({
      data: [
        completedInsight({
          id: 'insight-fresh',
          content: '## Fresh\n\nCurrent recommendation.',
          created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        }),
      ],
    })
    visitAndWait()
    cy.get(AI_CONTENT, { timeout: 10000 }).scrollIntoView()
  })

  it('does not show staleness badge when insight is fresh (within 24h)', () => {
    cy.get(AI_STALENESS_BADGE).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// H. Error state
// ---------------------------------------------------------------------------

describe('Analytics AI Card UI — error state (insights fetch fails)', () => {
  beforeEach(() => {
    setupPageStubs()
    cy.intercept(
      { method: 'GET', pathname: INSIGHTS_PATH },
      {
        statusCode: 500,
        body: { error: 'Internal server error' },
      }
    ).as('getInsights')
    visitAndWait()
    cy.get(AI_ERROR, { timeout: 10000 }).scrollIntoView()
  })

  it('shows error container with retry button; hides generate button', () => {
    cy.get(AI_ERROR).should('be.visible').and('contain.text', 'Could not load recommendations')
    cy.get(AI_RETRY_BTN).scrollIntoView().should('be.visible').and('contain.text', 'Try again')
    cy.get(AI_GENERATE_BTN).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// I. Retry flow — clicking Try again re-fetches to empty state
// ---------------------------------------------------------------------------

describe('Analytics AI Card UI — retry after error', () => {
  beforeEach(() => {
    setupPageStubs()
    cy.intercept(
      { method: 'GET', pathname: INSIGHTS_PATH },
      {
        statusCode: 500,
        body: { error: 'Server error' },
      }
    ).as('getInsights')
    visitAndWait()
    cy.get(AI_ERROR, { timeout: 10000 }).scrollIntoView()
  })

  it('clicking Try again re-fetches and shows empty state on success', () => {
    cy.intercept(
      { method: 'GET', pathname: INSIGHTS_PATH },
      { statusCode: 200, body: { data: [] } }
    ).as('getInsightsRetry')
    cy.get(AI_RETRY_BTN).click()
    cy.get(AI_EMPTY, { timeout: 10000 }).scrollIntoView().should('be.visible')
    cy.get(AI_ERROR).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// J. History modal — ≥2 completed insights
// ---------------------------------------------------------------------------

describe('Analytics AI Card UI — history modal (≥2 insights)', () => {
  beforeEach(() => {
    setupPageStubs()
    stubInsights({
      data: [
        completedInsight({
          id: 'insight-2',
          content: '## Week 2\n\nGood progress.',
          created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        }),
        completedInsight({
          id: 'insight-1',
          content: '## Week 1\n\nKeep it consistent.',
          created_at: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
        }),
      ],
    })
    visitAndWait()
    cy.get(AI_CONTENT, { timeout: 10000 }).scrollIntoView()
  })

  it('shows history button and clicking it opens the history modal', () => {
    cy.get(AI_HISTORY_BTN)
      .scrollIntoView()
      .should('be.visible')
      .and('contain.text', 'History')
      .click()
    cy.get(AI_HISTORY_MODAL)
      .should('be.visible')
      .within(() => {
        cy.contains('Analysis History').should('be.visible')
      })
  })
})

// ---------------------------------------------------------------------------
// K. History button absent for single insight
// ---------------------------------------------------------------------------

describe('Analytics AI Card UI — history button absent (1 insight)', () => {
  beforeEach(() => {
    setupPageStubs()
    stubInsights({
      data: [
        completedInsight({
          id: 'insight-only',
          content: '## Solo\n\nOnly one insight.',
        }),
      ],
    })
    visitAndWait()
    cy.get(AI_CONTENT, { timeout: 10000 }).scrollIntoView()
  })

  it('does not show history button when only 1 completed insight exists', () => {
    cy.get(AI_HISTORY_BTN).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// L. Refresh flow
// ---------------------------------------------------------------------------

describe('Analytics AI Card UI — refresh from content state', () => {
  beforeEach(() => {
    setupPageStubs()
    stubInsights({
      data: [
        completedInsight({
          id: 'insight-content',
          content: '## Current\n\nYou are doing well.',
          created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        }),
      ],
    })
    visitAndWait()
    cy.get(AI_CONTENT, { timeout: 10000 }).scrollIntoView()
  })

  it('clicking Refresh fires POST to generate endpoint', () => {
    cy.intercept('POST', GENERATE_URL, { statusCode: 200, body: { queued: true } }).as(
      'postRefresh'
    )
    cy.get(AI_REFRESH_BTN).scrollIntoView().click()
    cy.wait('@postRefresh').its('request.method').should('eq', 'POST')
  })
})

// ---------------------------------------------------------------------------
// M. Generate error in empty state
// ---------------------------------------------------------------------------

describe('Analytics AI Card UI — generate error (POST fails)', () => {
  beforeEach(() => {
    setupPageStubs()
    stubInsights({ data: [] })
    visitAndWait()
    cy.get(AI_EMPTY, { timeout: 10000 }).scrollIntoView()
  })

  it('shows inline error when POST generate fails', () => {
    cy.intercept('POST', GENERATE_URL, {
      statusCode: 500,
      body: { error: 'Internal server error' },
    }).as('postGenerateFail')
    cy.get(AI_GENERATE_BTN).scrollIntoView().click()
    cy.wait('@postGenerateFail')
    cy.get(AI_EMPTY)
      .scrollIntoView()
      .within(() => {
        cy.contains('Failed to start analysis').should('be.visible')
      })
  })
})

// ---------------------------------------------------------------------------
// N. Pending state on initial load
// ---------------------------------------------------------------------------

describe('Analytics AI Card UI — pending on initial load', () => {
  beforeEach(() => {
    setupPageStubs()
    stubInsights({ data: [pendingInsight()] })
    visitAndWait()
    cy.get(AI_PENDING, { timeout: 10000 }).scrollIntoView()
  })

  it('shows pending shimmer, hides empty and content containers', () => {
    cy.get(AI_PENDING).should('be.visible')
    cy.get(AI_EMPTY).should('not.exist')
    cy.get(AI_CONTENT).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// O. Dual-role JSON format — Running Coach + Performance Analyst + Summary
//    The RoleInsight component parses JSON content produced by the updated
//    generateAnalyticsSummary Inngest function (feat: dual-role format #118).
//    Each section (weekly_distance, pace_trend, etc.) is stored as a JSON
//    string with keys: running_coach, performance_analyst, summary.
// ---------------------------------------------------------------------------

// Dual-role JSON content fixture — matches the schema from buildAnalyticsSummaryPrompt
const dualRoleContent = JSON.stringify({
  running_coach:
    'Focus on building your aerobic base by keeping 80% of runs in Zone 1–2. Your current volume is solid — aim for one quality session per week at tempo effort.',
  performance_analyst:
    'Your weekly distance averaged 42 km over the past 4 weeks with a slight upward trend (+8%). EF sits at 1.72 m/min/bpm, within the moderate range for a developing runner.',
  summary:
    'Solid aerobic volume with room to improve efficiency — prioritize easy pace discipline.',
})

describe('Analytics AI Card UI — dual-role JSON content (Running Coach format)', () => {
  beforeEach(() => {
    setupPageStubs()
    stubInsights({
      data: [
        completedInsight({
          id: 'insight-dual-role',
          content: dualRoleContent,
          created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        }),
      ],
    })
    visitAndWait()
    cy.get(AI_CONTENT, { timeout: 10000 }).scrollIntoView()
  })

  it('renders Running Coach card with violet label and coaching advice text', () => {
    // The RoleInsight component renders a violet-bordered card with "Running Coach" label
    cy.get(AI_CONTENT)
      .scrollIntoView()
      .within(() => {
        cy.contains('Running Coach').should('be.visible')
        cy.contains('aerobic base').should('be.visible')
      })
  })

  it('renders Performance Analyst card with blue label and data-driven text', () => {
    cy.get(AI_CONTENT)
      .scrollIntoView()
      .within(() => {
        cy.contains('Performance Analyst').should('be.visible')
        cy.contains('weekly distance').should('be.visible')
      })
  })

  it('renders Summary card with the single most important takeaway', () => {
    cy.get(AI_CONTENT)
      .scrollIntoView()
      .within(() => {
        cy.contains('Summary').should('be.visible')
        cy.contains('Solid aerobic volume').should('be.visible')
      })
  })

  it('shows all three role cards in one content block', () => {
    // All three sections must coexist inside the content container
    cy.get(AI_CONTENT)
      .scrollIntoView()
      .within(() => {
        cy.contains('Running Coach').should('exist')
        cy.contains('Performance Analyst').should('exist')
        cy.contains('Summary').should('exist')
      })
  })
})

// ---------------------------------------------------------------------------
// P. Legacy markdown format fallback
//    When content is NOT valid JSON the RoleInsight component falls back to
//    renderMarkdown — this preserves compatibility with pre-#118 insights.
// ---------------------------------------------------------------------------

describe('Analytics AI Card UI — legacy markdown format (fallback rendering)', () => {
  beforeEach(() => {
    setupPageStubs()
    stubInsights({
      data: [
        completedInsight({
          id: 'insight-legacy-markdown',
          // Old format: plain markdown — not valid JSON
          content:
            '## Weekly Distance\n\nGreat consistency this week. Keep it up.\n\n- 42 km total\n- 4 sessions',
          created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        }),
      ],
    })
    visitAndWait()
    cy.get(AI_CONTENT, { timeout: 10000 }).scrollIntoView()
  })

  it('renders legacy markdown content without three role cards', () => {
    // Fallback path: text should appear but no role-specific labels
    cy.get(AI_CONTENT)
      .scrollIntoView()
      .within(() => {
        cy.contains('Great consistency this week').should('be.visible')
        // Role-specific headings must NOT appear in the markdown fallback
        cy.contains('Running Coach').should('not.exist')
        cy.contains('Performance Analyst').should('not.exist')
      })
  })
})

// ---------------------------------------------------------------------------
// Q. History modal — dual-role JSON format items render correctly
//    History items expand via accordion; each uses RoleInsight so the
//    dual-role cards must also render inside the history sheet.
// ---------------------------------------------------------------------------

describe('Analytics AI Card UI — history modal with dual-role JSON items', () => {
  beforeEach(() => {
    setupPageStubs()
    stubInsights({
      data: [
        // Most recent — dual-role JSON format
        completedInsight({
          id: 'insight-dual-recent',
          content: dualRoleContent,
          created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        }),
        // Older — also dual-role JSON format
        completedInsight({
          id: 'insight-dual-older',
          content: JSON.stringify({
            running_coach: 'Last week you ran well. Consider adding one long run.',
            performance_analyst:
              'Volume was 38 km — slightly below target. Pace was consistent across sessions.',
            summary: 'Consistent week — add volume gradually.',
          }),
          created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        }),
      ],
    })
    visitAndWait()
    cy.get(AI_CONTENT, { timeout: 10000 }).scrollIntoView()
  })

  it('opens history modal and expanding an item renders dual-role cards', () => {
    // Open history modal — button is visible because ≥2 completed insights
    cy.get(AI_HISTORY_BTN).scrollIntoView().should('be.visible').click()
    cy.get(AI_HISTORY_MODAL).should('be.visible')

    // Expand the first history accordion item
    cy.get(AI_HISTORY_MODAL).within(() => {
      cy.get('button[aria-expanded]').first().click()
      // After expanding, the dual-role cards should appear inside the modal
      cy.contains('Running Coach').should('be.visible')
      cy.contains('Performance Analyst').should('be.visible')
      cy.contains('Summary').should('be.visible')
    })
  })
})
