// Generated by Cypress Author — 2026-06-09
// UI-only spec: cy.visit + DOM assertions.
// Covers: PersonalBestsTable component on the analytics page.
// Issue: #174 (Personal Bests table)
//
// AUTH STRATEGY:
//   All UI describes use cy.setupApiAuthCookies() + stubs so the analytics page
//   renders a controlled state. The personal-bests endpoint is stubbed per block.

import constants from '../../../fixtures/app-constants.json'

Cypress.on('uncaught:exception', (err) => {
  if (
    err.message.includes('ServiceWorker') ||
    err.message.includes('serviceWorker') ||
    err.message.includes('sw.js')
  ) {
    return false
  }
})

const IDS = constants.test_ids.running_analytics
const ANALYTICS_URL = constants.routes.running_analytics
const PERSONAL_BESTS_EP = constants.endpoints.running_analytics.personal_bests

// ---------------------------------------------------------------------------
// Shared page stubs — keep other analytics sections quiet
// ---------------------------------------------------------------------------

const stubPageDeps = () => {
  cy.intercept('GET', '**/rest/v1/rt_users*', {
    statusCode: 200,
    body: [{ id: 'test-user-id', onboarding_complete: true }],
  }).as('rtUsersCheck')

  cy.intercept('GET', '/api/running/v1/activities*', {
    statusCode: 200,
    body: { data: [], meta: { total: 0, page: 1, limit: 200 } },
  }).as('getActivities')

  cy.intercept('GET', '/api/running/v1/performance-trends*', {
    statusCode: 200,
    body: { data: [] },
  }).as('getPerformanceTrends')

  cy.intercept('GET', '/api/running/v1/dashboard*', {
    statusCode: 200,
    body: {
      data: {
        weekly_stats: {
          current: { distance_m: 0, duration_sec: 0, count: 0, avg_pace_sec_per_km: null },
          prev: { distance_m: 0, duration_sec: 0, count: 0, avg_pace_sec_per_km: null },
        },
        training_load: {
          acwr: null,
          acute_load_7d: null,
          chronic_load_28d: null,
          status: 'no_data',
        },
        recent_activities: [],
        calendar_activities: [],
        health_today: { logged: false, data: null },
      },
    },
  }).as('getDashboard')

  // Keep vo2max-stat, target-effort, and AI endpoints quiet
  cy.intercept('GET', '/api/running/v1/analytics/vo2max-stat', {
    statusCode: 200,
    body: { data: { empty: true } },
  }).as('getVo2maxStat')

  cy.intercept('GET', '/api/running/v1/analytics/target-effort', {
    statusCode: 200,
    body: { data: { status: 'no_goal', currentVo2max: null, requiredVo2max: null } },
  }).as('getTargetEffort')

  cy.intercept('GET', '/api/running/v1/ai/insights*', {
    statusCode: 200,
    body: { data: [] },
  }).as('getInsights')

  cy.intercept('GET', '/api/running/v1/ai/insights/staleness', {
    statusCode: 200,
    body: { data: { is_stale: false } },
  }).as('getStaleness')
}

const visitAndWait = () => {
  cy.viewport(1280, 900)
  cy.visit(ANALYTICS_URL)
  cy.wait('@getActivities')
}

// ---------------------------------------------------------------------------
// A. Auth guard
// ---------------------------------------------------------------------------

describe('Personal Bests UI — auth guard', () => {
  it('unauthenticated visit redirects to /login', () => {
    cy.clearAllCookies()
    cy.clearAllLocalStorage()
    cy.visit(ANALYTICS_URL, { failOnStatusCode: false })
    cy.url().should('include', '/login')
  })
})

// ---------------------------------------------------------------------------
// B. Loading state
// ---------------------------------------------------------------------------

describe('Personal Bests UI — loading state', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubPageDeps()

    // Delay personal-bests so the loading skeleton is visible
    cy.intercept('GET', PERSONAL_BESTS_EP, (req) => {
      req.reply({ delay: 3000, statusCode: 200, body: { data: {}, message: 'OK' } })
    }).as('getPersonalBests')
  })

  it('shows loading skeleton while personal bests are fetching', () => {
    visitAndWait()
    cy.get(`#${IDS.personal_bests_section}`).scrollIntoView()
    cy.get(`#${IDS.personal_bests_loading}`).should('exist')
  })
})

// ---------------------------------------------------------------------------
// C. Happy path — table renders with full data
// ---------------------------------------------------------------------------

describe('Personal Bests UI — table renders with data', () => {
  const DISTANCES = ['1 mile', '5K', '10K', '15K', 'Half-Marathon']

  const makeBest = (rank, timeSec, paceSec) => ({
    rank,
    elapsed_time_sec: timeSec,
    pace_sec_per_km: paceSec,
    date: '2026-01-15T08:00:00Z',
    activity_id: `act-pb-${rank}`,
    pr_rank: rank === 1 ? 1 : null,
  })

  const stubWithData = () => {
    const data = {
      '1 mile': [makeBest(1, 420, 261), makeBest(2, 435, 270)],
      '5K': [makeBest(1, 1350, 270), makeBest(2, 1380, 276)],
      '10K': [makeBest(1, 2880, 288), makeBest(2, 2940, 294)],
      '15K': [makeBest(1, 4500, 300)],
      'Half-Marathon': [makeBest(1, 6300, 299)],
    }
    cy.intercept('GET', PERSONAL_BESTS_EP, {
      statusCode: 200,
      body: { data, message: 'OK' },
    }).as('getPersonalBests')
  }

  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubPageDeps()
    stubWithData()
    visitAndWait()
    cy.wait('@getPersonalBests')
  })

  it('renders #personalBestsSection_analyticsPage', () => {
    cy.get(`#${IDS.personal_bests_section}`).scrollIntoView().should('be.visible')
  })

  it('renders #personalBestsTable_analyticsPage after data loads', () => {
    cy.get(`#${IDS.personal_bests_table}`).scrollIntoView().should('be.visible')
  })

  it('does not render loading skeleton after data loads', () => {
    cy.get(`#${IDS.personal_bests_table}`).scrollIntoView()
    cy.get(`#${IDS.personal_bests_loading}`).should('not.exist')
  })

  it('shows all 5 distance column headers', () => {
    cy.get(`#${IDS.personal_bests_table}`).scrollIntoView()
    DISTANCES.forEach((d) => {
      cy.get(`#${IDS.personal_bests_table}`).within(() => {
        cy.contains(d).should('be.visible')
      })
    })
  })

  it('renders rank-1 row for 5K distance', () => {
    // ID pattern: personalBestsRow_{distance-key}_{rank}_analyticsPage
    cy.get('#personalBestsRow_5K_1_analyticsPage').scrollIntoView().should('be.visible')
  })

  it('rank-1 row shows formatted time and pace', () => {
    cy.get('#personalBestsRow_5K_1_analyticsPage')
      .scrollIntoView()
      .within(() => {
        // 1350 sec = 22:30
        cy.contains('22:30').should('be.visible')
        // paceSec 270 = 4:30 /km
        cy.contains('4:30 /km').should('be.visible')
      })
  })

  it('rank-1 row shows the date', () => {
    cy.get('#personalBestsRow_5K_1_analyticsPage')
      .scrollIntoView()
      .within(() => {
        cy.contains('15 Jan 2026').should('be.visible')
      })
  })

  it('rank-2 row is rendered below rank-1 for a distance with multiple entries', () => {
    cy.get('#personalBestsRow_5K_2_analyticsPage').scrollIntoView().should('be.visible')
  })

  it('renders 1-mile row with correct time format (no hours)', () => {
    // 420 sec = 7:00
    cy.get('#personalBestsRow_1-mile_1_analyticsPage')
      .scrollIntoView()
      .within(() => {
        cy.contains('7:00').should('be.visible')
      })
  })

  it('Half-Marathon time renders with hours when over 60 min', () => {
    // 6300 sec = 1:45:00
    cy.get('#personalBestsRow_Half-Marathon_1_analyticsPage')
      .scrollIntoView()
      .within(() => {
        cy.contains('1:45:00').should('be.visible')
      })
  })
})

// ---------------------------------------------------------------------------
// D. Empty state — all distances have no entries
// ---------------------------------------------------------------------------

describe('Personal Bests UI — empty distances show dash', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubPageDeps()

    cy.intercept('GET', PERSONAL_BESTS_EP, {
      statusCode: 200,
      body: {
        data: {
          '1 mile': [],
          '5K': [],
          '10K': [],
          '15K': [],
          'Half-Marathon': [],
        },
        message: 'OK',
      },
    }).as('getPersonalBests')

    visitAndWait()
    cy.wait('@getPersonalBests')
  })

  it('renders #personalBestsTable_analyticsPage even with empty data', () => {
    cy.get(`#${IDS.personal_bests_table}`).scrollIntoView().should('be.visible')
  })

  it('shows em-dash placeholder for each empty distance column', () => {
    // Each empty distance column renders a "—" placeholder
    cy.get(`#${IDS.personal_bests_table}`)
      .scrollIntoView()
      .within(() => {
        // There should be multiple dash placeholders (one per empty distance)
        cy.contains('—').should('exist')
      })
  })

  it('does not render any personalBestsRow elements', () => {
    cy.get('[id^="personalBestsRow_"]').should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// E. Error state — 500 from API
// ---------------------------------------------------------------------------

describe('Personal Bests UI — error state', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubPageDeps()

    cy.intercept('GET', PERSONAL_BESTS_EP, {
      statusCode: 500,
      body: {},
    }).as('getPersonalBests')

    visitAndWait()
    cy.wait('@getPersonalBests')
  })

  it('renders #personalBestsError_analyticsPage', () => {
    cy.get(`#${IDS.personal_bests_error}`).scrollIntoView().should('be.visible')
  })

  it('shows an error message in the error container', () => {
    cy.get(`#${IDS.personal_bests_error}`)
      .scrollIntoView()
      .should('contain.text', 'Failed to load personal bests')
  })

  it('does not render #personalBestsTable_analyticsPage in error state', () => {
    cy.get(`#${IDS.personal_bests_table}`).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// F. Row click — navigates to activity detail page
// ---------------------------------------------------------------------------

describe('Personal Bests UI — row click navigates to activity', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubPageDeps()

    cy.intercept('GET', PERSONAL_BESTS_EP, {
      statusCode: 200,
      body: {
        data: {
          '1 mile': [],
          '5K': [
            {
              rank: 1,
              elapsed_time_sec: 1350,
              pace_sec_per_km: 270,
              date: '2026-01-15T08:00:00Z',
              activity_id: 'activity-abc-123',
              pr_rank: 1,
            },
          ],
          '10K': [],
          '15K': [],
          'Half-Marathon': [],
        },
        message: 'OK',
      },
    }).as('getPersonalBests')

    visitAndWait()
    cy.wait('@getPersonalBests')
  })

  it('clicking a row navigates to the activity detail page', () => {
    cy.on('uncaught:exception', () => false)

    cy.intercept('GET', '/api/running/v1/activities/activity-abc-123*', {
      statusCode: 200,
      body: { data: { id: 'activity-abc-123' } },
    }).as('getActivity')

    cy.get('#personalBestsRow_5K_1_analyticsPage').scrollIntoView().click()
    cy.url().should('include', '/main/running/activities/activity-abc-123')
  })
})
