// Generated by Cypress Author — 2026-06-09
// API-only spec: cy.request only — no cy.visit, no DOM assertions.
// Covers: GET /api/running/v1/analytics/personal-bests
// Issue: #174 (Personal Bests table)

import constants from '../../../fixtures/app-constants.json'

const PERSONAL_BESTS_EP = constants.endpoints.running_analytics.personal_bests

// ---------------------------------------------------------------------------
// A. Auth guard — no session → 401
// ---------------------------------------------------------------------------

describe('Personal Bests API — auth guard', () => {
  it('returns 401 when unauthenticated', () => {
    cy.request({
      method: 'GET',
      url: PERSONAL_BESTS_EP,
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(401)
      expect(res.body).to.have.property('error')
    })
  })
})

// ---------------------------------------------------------------------------
// B. Authenticated — top-level response shape
// ---------------------------------------------------------------------------

describe('Personal Bests API — authenticated response shape', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 with a top-level data object', () => {
    cy.request({
      method: 'GET',
      url: PERSONAL_BESTS_EP,
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('data')
      expect(res.body).to.have.property('message', 'OK')
    })
  })

  it('data contains all 5 expected distance keys', () => {
    const expectedDistances = ['1 mile', '5K', '10K', '15K', 'Half-Marathon']

    cy.request({
      method: 'GET',
      url: PERSONAL_BESTS_EP,
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(200)
      const data = res.body.data
      expectedDistances.forEach((distance) => {
        expect(data).to.have.property(distance)
        expect(data[distance]).to.be.an('array')
      })
    })
  })

  it('each distance entry array has at most 5 items', () => {
    cy.request({
      method: 'GET',
      url: PERSONAL_BESTS_EP,
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(200)
      const data = res.body.data
      Object.values(data).forEach((entries) => {
        expect(entries.length).to.be.lte(5)
      })
    })
  })
})

// ---------------------------------------------------------------------------
// C. Entry shape — required fields present when entries exist
// ---------------------------------------------------------------------------

describe('Personal Bests API — entry field shape', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('each entry includes required fields when present', () => {
    cy.request({
      method: 'GET',
      url: PERSONAL_BESTS_EP,
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(200)
      const data = res.body.data

      // Find the first distance that actually has entries
      const firstNonEmpty = Object.entries(data).find(([, entries]) => entries.length > 0)

      if (!firstNonEmpty) {
        // No data in the test account — validate shape cannot be checked, skip
        cy.log('No personal best entries found for this account — field shape skipped')
        return
      }

      const [, entries] = firstNonEmpty
      const entry = entries[0]

      expect(entry).to.have.property('rank')
      expect(entry.rank).to.be.a('number')
      expect(entry).to.have.property('elapsed_time_sec')
      expect(entry.elapsed_time_sec).to.be.a('number')
      expect(entry).to.have.property('date')
      expect(entry).to.have.property('activity_id')
      // pace_sec_per_km may be null for 0-distance entries but key must exist
      expect(entry).to.have.property('pace_sec_per_km')
    })
  })

  it('rank of top entry is 1', () => {
    cy.request({
      method: 'GET',
      url: PERSONAL_BESTS_EP,
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(200)
      const data = res.body.data

      const firstNonEmpty = Object.entries(data).find(([, entries]) => entries.length > 0)
      if (!firstNonEmpty) return

      const [, entries] = firstNonEmpty
      expect(entries[0].rank).to.eq(1)
    })
  })

  it('entries within a distance are ordered rank ascending', () => {
    cy.request({
      method: 'GET',
      url: PERSONAL_BESTS_EP,
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(200)
      const data = res.body.data

      Object.entries(data).forEach(([, entries]) => {
        if (entries.length < 2) return
        for (let i = 1; i < entries.length; i++) {
          expect(entries[i].rank).to.be.gte(entries[i - 1].rank)
        }
      })
    })
  })
})
