// Generated by Cypress Author — 2026-08-10
// API-only spec: cy.request only — no cy.visit, no DOM assertions.
// Covers:
//   GET /api/running/v1/analytics/vo2max-target  (#741)
//   PUT /api/running/v1/analytics/vo2max-target  (#741)
//
// rt_users.vo2max_target is reset to NULL for the test user before this
// suite runs and after it finishes, so PUT tests stay idempotent.

import constants from '../../../fixtures/app-constants.json'

const VO2MAX_TARGET_EP = constants.endpoints.running_analytics.vo2max_target

// ─── vo2max-target — DB cleanup ────────────────────────────────────────────

before(() => {
  cy.resetVo2maxTargetInDb()
})

after(() => {
  cy.resetVo2maxTargetInDb()
})

// ─── GET vo2max-target ──────────────────────────────────────────────────────

describe('VO2max Target API — GET auth guard', () => {
  it('returns 401 when unauthenticated', () => {
    cy.getVo2maxTargetNoAuth().then((res) => {
      expect(res.status).to.eq(401)
    })
  })
})

describe('VO2max Target API — GET when no target set', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    cy.resetVo2maxTargetInDb()
  })

  it('returns 200 with data.vo2max_target null', () => {
    cy.getVo2maxTarget().then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('success', true)
      expect(res.body).to.have.property('data')
      expect(res.body.data).to.have.property('vo2max_target', null)
    })
  })
})

describe('VO2max Target API — GET after target is set', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 with data.vo2max_target as the persisted number', () => {
    cy.putVo2maxTarget({ vo2max_target: 55 }).then((putRes) => {
      expect(putRes.status).to.eq(200)
      cy.getVo2maxTarget().then((getRes) => {
        expect(getRes.status).to.eq(200)
        expect(getRes.body.data.vo2max_target).to.eq(55)
      })
    })
  })
})

// ─── PUT vo2max-target ──────────────────────────────────────────────────────

describe('VO2max Target API — PUT auth guard', () => {
  it('returns 401 when unauthenticated', () => {
    cy.putVo2maxTargetNoAuth({ vo2max_target: 50 }).then((res) => {
      expect(res.status).to.eq(401)
    })
  })
})

describe('VO2max Target API — PUT validation', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 400 for malformed JSON body', () => {
    cy.getCookie('sb-access-token').then((cookie) => {
      cy.request({
        method: 'PUT',
        url: VO2MAX_TARGET_EP,
        headers: {
          ...(cookie?.value ? { Authorization: `Bearer ${cookie.value}` } : {}),
          'Content-Type': 'application/json',
        },
        body: 'not-json-at-all',
        failOnStatusCode: false,
      }).then((res) => {
        expect(res.status).to.eq(400)
      })
    })
  })

  it('returns 400 for vo2max_target below min (9)', () => {
    cy.putVo2maxTarget({ vo2max_target: 9 }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('success', false)
    })
  })

  it('returns 400 for vo2max_target above max (91)', () => {
    cy.putVo2maxTarget({ vo2max_target: 91 }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('success', false)
    })
  })

  it('returns 400 for vo2max_target with wrong type (string)', () => {
    cy.putVo2maxTarget({ vo2max_target: 'fifty' }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('success', false)
    })
  })
})

describe('VO2max Target API — PUT success', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 with data.vo2max_target 50 for a valid value', () => {
    cy.putVo2maxTarget({ vo2max_target: 50 }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('success', true)
      expect(res.body.data).to.have.property('vo2max_target', 50)
    })
  })

  it('returns 200 with data.vo2max_target 10 for boundary min value', () => {
    cy.putVo2maxTarget({ vo2max_target: 10 }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body.data).to.have.property('vo2max_target', 10)
    })
  })

  it('returns 200 with data.vo2max_target 90 for boundary max value', () => {
    cy.putVo2maxTarget({ vo2max_target: 90 }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body.data).to.have.property('vo2max_target', 90)
    })
  })

  it('returns 200 with data.vo2max_target null when clearing the target', () => {
    cy.putVo2maxTarget({ vo2max_target: null }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('success', true)
      expect(res.body.data).to.have.property('vo2max_target', null)
    })
  })
})

describe('VO2max Target API — persistence across GET and PUT', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('GET reflects the value set by a prior PUT', () => {
    cy.putVo2maxTarget({ vo2max_target: 42 }).then(() => {
      cy.getVo2maxTarget().then((res) => {
        expect(res.status).to.eq(200)
        expect(res.body.data.vo2max_target).to.eq(42)
      })
    })
  })

  it('GET returns null after a PUT that clears the target', () => {
    cy.putVo2maxTarget({ vo2max_target: 42 }).then(() => {
      cy.putVo2maxTarget({ vo2max_target: null }).then(() => {
        cy.getVo2maxTarget().then((res) => {
          expect(res.status).to.eq(200)
          expect(res.body.data.vo2max_target).to.be.null
        })
      })
    })
  })
})
