// Generated by Cypress Author on 2026-07-06.
// API-only spec: no cy.visit, no DOM assertions.
// Covers GET / POST / PATCH / DELETE for /api/running/v1/routes

const validRoute = () => ({
  name: 'Cypress Test Route',
  waypoints: [
    [106.8456, -6.2088],
    [106.847, -6.21],
  ],
  encoded_polyline: '_qekA_qekA??',
  distance_m: 200,
})

// GET /routes

describe('Route Builder API — GET list (authenticated)', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 with a data array', () => {
    cy.getRoutes().then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('data')
      expect(res.body.data).to.be.an('array')
    })
  })

  it('each entry has required fields when list is non-empty', () => {
    cy.getRoutes().then((res) => {
      const entries = res.body.data
      if (entries.length === 0) return
      const entry = entries[0]
      expect(entry).to.have.property('id')
      expect(entry).to.have.property('name')
      expect(entry).to.have.property('distance_m').and.be.a('number')
      expect(entry).to.have.property('encoded_polyline')
      expect(entry).to.have.property('created_at')
    })
  })

  it('each entry includes a waypoints field', () => {
    cy.getRoutes().then((res) => {
      const entries = res.body.data
      if (entries.length === 0) return
      expect(entries[0]).to.have.property('waypoints')
    })
  })
})

describe('Route Builder API — GET list (unauthenticated)', () => {
  beforeEach(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
  })

  it('returns 401 without a session', () => {
    cy.getRoutesNoAuth().then((res) => {
      expect(res.status).to.eq(401)
    })
  })
})

// POST /routes

describe('Route Builder API — POST save (authenticated)', () => {
  const createdIds = []

  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  after(() => {
    cy.setupApiAuthCookies()
    createdIds.forEach((id) => cy.deleteRoute(id))
  })

  it('creates a route and returns 201 with the saved record', () => {
    cy.postRoute(validRoute()).then((res) => {
      expect(res.status).to.eq(201)
      const route = res.body.data
      expect(route).to.have.property('id')
      expect(route.name).to.eq('Cypress Test Route')
      expect(route.distance_m).to.eq(200)
      expect(route.encoded_polyline).to.eq('_qekA_qekA??')
      createdIds.push(route.id)
    })
  })

  it('returns 422 when name is missing', () => {
    const { name, ...body } = validRoute()
    cy.postRoute(body).then((res) => {
      expect(res.status).to.eq(422)
    })
  })

  it('returns 422 when name is an empty string', () => {
    cy.postRoute({ ...validRoute(), name: '' }).then((res) => {
      expect(res.status).to.eq(422)
    })
  })

  it('returns 422 when waypoints has fewer than 2 points', () => {
    cy.postRoute({ ...validRoute(), waypoints: [[-6.2088, 106.8456]] }).then((res) => {
      expect(res.status).to.eq(422)
    })
  })

  it('returns 422 when encoded_polyline is missing', () => {
    const { encoded_polyline, ...body } = validRoute()
    cy.postRoute(body).then((res) => {
      expect(res.status).to.eq(422)
    })
  })

  it('returns 422 when distance_m is 0', () => {
    cy.postRoute({ ...validRoute(), distance_m: 0 }).then((res) => {
      expect(res.status).to.eq(422)
    })
  })

  it('returns 422 when name exceeds 100 characters', () => {
    cy.postRoute({ ...validRoute(), name: 'a'.repeat(101) }).then((res) => {
      expect(res.status).to.eq(422)
    })
  })
})

describe('Route Builder API — POST save (unauthenticated)', () => {
  beforeEach(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
  })

  it('returns 401 without a session', () => {
    cy.postRouteNoAuth(validRoute()).then((res) => {
      expect(res.status).to.eq(401)
    })
  })
})

// PATCH /routes/:id

describe('Route Builder API — PATCH rename (authenticated)', () => {
  let routeId

  before(() => {
    cy.setupApiAuthCookies()
    cy.postRoute(validRoute()).then((res) => {
      if (res.status === 201) routeId = res.body.data.id
    })
  })

  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  after(() => {
    if (routeId) {
      cy.setupApiAuthCookies()
      cy.deleteRoute(routeId)
    }
  })

  it('returns 200 with the updated name', function () {
    if (!routeId) this.skip()
    cy.patchRoute(routeId, { name: 'Renamed Cypress Route' }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body.data.name).to.eq('Renamed Cypress Route')
    })
  })

  it('returns 400 when name is an empty string', function () {
    if (!routeId) this.skip()
    cy.patchRoute(routeId, { name: '' }).then((res) => {
      expect(res.status).to.eq(400)
    })
  })

  it('returns 400 when name is missing', function () {
    if (!routeId) this.skip()
    cy.patchRoute(routeId, {}).then((res) => {
      expect(res.status).to.eq(400)
    })
  })

  it('returns 400 when name exceeds 100 characters', function () {
    if (!routeId) this.skip()
    cy.patchRoute(routeId, { name: 'a'.repeat(101) }).then((res) => {
      expect(res.status).to.eq(400)
    })
  })

  // updateRoute() uses .single() — an update matching zero rows throws,
  // which the route handler's catch-all turns into a 500 (no 404 check exists).
  it('returns 500 for an id that does not belong to the authenticated user', () => {
    const nonExistentId = '00000000-0000-0000-0000-000000000000'
    cy.patchRoute(nonExistentId, { name: 'Should not update' }).then((res) => {
      expect(res.status).to.eq(500)
    })
  })
})

describe('Route Builder API — PATCH rename (unauthenticated)', () => {
  beforeEach(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
  })

  it('returns 401 without a session', () => {
    cy.patchRouteNoAuth('any-id', { name: 'Unauth rename' }).then((res) => {
      expect(res.status).to.eq(401)
    })
  })
})

// DELETE /routes/:id

describe('Route Builder API — DELETE (authenticated)', () => {
  let routeId

  before(() => {
    cy.setupApiAuthCookies()
    cy.postRoute(validRoute()).then((res) => {
      if (res.status === 201) routeId = res.body.data.id
    })
  })

  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 with a confirmation message on successful delete', function () {
    if (!routeId) this.skip()
    cy.deleteRoute(routeId).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('message')
      routeId = null
    })
  })

  // deleteRoute() does not check affected row count, so deleting an id that
  // does not belong to the user (or no longer exists) still resolves 200.
  it('returns 200 (no-op) for an id that does not belong to the authenticated user', () => {
    const nonExistentId = '00000000-0000-0000-0000-000000000000'
    cy.deleteRoute(nonExistentId).then((res) => {
      expect(res.status).to.eq(200)
    })
  })
})

describe('Route Builder API — DELETE (unauthenticated)', () => {
  beforeEach(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
  })

  it('returns 401 without a session', () => {
    cy.deleteRouteNoAuth('any-id').then((res) => {
      expect(res.status).to.eq(401)
    })
  })
})
