// Generated by Cypress Author — 2026-06-21
// Issue #438: Trading Settings — API test coverage

const VALID_SETTINGS = {
  initial_margin: 5000000,
  bi_risk_free_rate: 6.5,
  personal_risk_free_rate: 8.0,
  margin_of_error: 15,
}

describe('Trading Settings API', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  // ─── GET /api/trade/v1/settings ──────────────────────────────────────────────

  describe('GET /api/trade/v1/settings', () => {
    it('returns 200 with valid session', () => {
      cy.GetTradeSettings().then((res) => {
        expect(res.status).to.eq(200)
      })
    })

    it('returns 401 when unauthenticated', () => {
      cy.clearCookies()
      cy.GetTradeSettingsNoAuth().then((res) => {
        expect(res.status).to.eq(401)
        expect(res.body.error).to.eq('Unauthorized')
      })
    })

    it('returns correct response shape — success + settingsList', () => {
      cy.GetTradeSettings().then((res) => {
        expect(res.body).to.have.property('success', true)
        expect(res.body).to.have.property('settingsList').that.is.an('object')

        const { settingsList } = res.body
        expect(settingsList).to.have.property('initial_margin')
        expect(settingsList).to.have.property('bi_risk_free_rate')
        expect(settingsList).to.have.property('personal_risk_free_rate')
        expect(settingsList).to.have.property('margin_of_error')
      })
    })

    it('settingsList field types are numeric-parseable', () => {
      cy.GetTradeSettings().then((res) => {
        const { settingsList } = res.body
        // Supabase numeric columns may return as strings — assert they are number-parseable and finite
        expect(Number.isFinite(Number(settingsList.initial_margin))).to.eq(true)
        expect(Number.isFinite(Number(settingsList.bi_risk_free_rate))).to.eq(true)
        expect(Number.isFinite(Number(settingsList.personal_risk_free_rate))).to.eq(true)
        expect(Number.isFinite(Number(settingsList.margin_of_error))).to.eq(true)
      })
    })

    it('responds within 1000ms', () => {
      const start = Date.now()
      cy.GetTradeSettings().then(() => {
        expect(Date.now() - start).to.be.lte(1000)
      })
    })
  })

  // ─── PUT /api/trade/v1/settings/update ───────────────────────────────────────

  describe('PUT /api/trade/v1/settings/update', () => {
    it('returns 200 with valid payload and session', () => {
      cy.UpdateTradeSettings(VALID_SETTINGS).then((res) => {
        expect(res.status).to.eq(200)
      })
    })

    it('returns 401 when unauthenticated', () => {
      cy.clearCookies()
      cy.UpdateTradeSettingsNoAuth(VALID_SETTINGS).then((res) => {
        expect(res.status).to.eq(401)
        expect(res.body.error).to.eq('Unauthorized')
      })
    })

    it('returns correct response shape — success + settings + message', () => {
      cy.UpdateTradeSettings(VALID_SETTINGS).then((res) => {
        expect(res.body).to.have.property('success', true)
        expect(res.body).to.have.property('settings').that.is.an('object')
        expect(res.body).to.have.property('message', 'Settings updated successfully')
      })
    })

    it('response.settings reflects the values sent in the request', () => {
      cy.UpdateTradeSettings(VALID_SETTINGS).then((res) => {
        const { settings } = res.body
        // Supabase numeric columns are returned as strings from upsert — coerce before comparing
        expect(Number(settings.initial_margin)).to.eq(VALID_SETTINGS.initial_margin)
        expect(Number(settings.bi_risk_free_rate)).to.eq(VALID_SETTINGS.bi_risk_free_rate)
        expect(Number(settings.personal_risk_free_rate)).to.eq(
          VALID_SETTINGS.personal_risk_free_rate
        )
        expect(Number(settings.margin_of_error)).to.eq(VALID_SETTINGS.margin_of_error)
      })
    })

    it('returns 400 when bi_risk_free_rate > 100', () => {
      cy.UpdateTradeSettings({ ...VALID_SETTINGS, bi_risk_free_rate: 101 }).then((res) => {
        expect(res.status).to.eq(400)
        expect(res.body.success).to.eq(false)
        expect(res.body.error).to.include('BI risk free rate')
      })
    })

    it('returns 400 when initial_margin < 0', () => {
      cy.UpdateTradeSettings({ ...VALID_SETTINGS, initial_margin: -1 }).then((res) => {
        expect(res.status).to.eq(400)
        expect(res.body.success).to.eq(false)
        expect(res.body.error).to.include('Initial margin')
      })
    })

    it('returns 400 when personal_risk_free_rate > 100', () => {
      cy.UpdateTradeSettings({ ...VALID_SETTINGS, personal_risk_free_rate: 150 }).then((res) => {
        expect(res.status).to.eq(400)
        expect(res.body.success).to.eq(false)
        expect(res.body.error).to.include('Personal risk free rate')
      })
    })

    it('returns 400 when margin_of_error > 100', () => {
      cy.UpdateTradeSettings({ ...VALID_SETTINGS, margin_of_error: 200 }).then((res) => {
        expect(res.status).to.eq(400)
        expect(res.body.success).to.eq(false)
        expect(res.body.error).to.include('Margin of error')
      })
    })

    it('responds within 1000ms', () => {
      const start = Date.now()
      cy.UpdateTradeSettings(VALID_SETTINGS).then(() => {
        expect(Date.now() - start).to.be.lte(1000)
      })
    })
  })

  // ─── DB comparison ────────────────────────────────────────────────────────────

  describe('DB comparison', () => {
    it('value written via PUT is readable back from the database', () => {
      const uniqueMargin = 7500000

      cy.UpdateTradeSettings({ ...VALID_SETTINGS, initial_margin: uniqueMargin }).then((res) => {
        expect(res.status).to.eq(200)
      })

      cy.getTradeSettingsFromDb().then((dbRow) => {
        expect(dbRow).to.not.be.null
        // Supabase numeric columns are returned as strings — coerce before comparing
        expect(Number(dbRow.initial_margin)).to.eq(uniqueMargin)
      })
    })

    it('GET returns the same value that was written to the database', () => {
      const uniqueRate = 7.25

      cy.UpdateTradeSettings({ ...VALID_SETTINGS, bi_risk_free_rate: uniqueRate }).then((res) => {
        expect(res.status).to.eq(200)
      })

      cy.GetTradeSettings().then((res) => {
        // GET parses the DB value — may return as number or string depending on ORM path
        expect(Number(res.body.settingsList.bi_risk_free_rate)).to.eq(uniqueRate)
      })

      cy.getTradeSettingsFromDb().then((dbRow) => {
        // Supabase numeric columns are returned as strings — coerce before comparing
        expect(Number(dbRow.bi_risk_free_rate)).to.eq(uniqueRate)
      })
    })
  })
})
