// Generated by Cypress Author — 2026-05-26
// Covers: HrZonesChart + AIInsightCard on the Activity Detail page
//   /main/running/activities/:id
//
// HrZonesChart states:
//   - empty state when activity has no zone data
//   - Z1-Z5 rows with label, HR range, percentage, duration when data present
//   - always renders section root (hrZonesSection)
//
// AIInsightCard states:
//   - loading skeleton while insight fetch is in-flight
//   - empty state with focus buttons when no insight exists (null response)
//   - generate → pending state when POST succeeds
//   - content state when insight is completed + is_valid + has content
//   - error state with retry when GET insight fetch fails
//   - completed + invalid falls back to empty/focus-button state

import constants from '../../../fixtures/app-constants.json'

const IDS = constants.test_ids.running_activity_detail
const ACTIVITY_ID = 'test-activity-id-hrzones-ai'
const DETAIL_URL = `/main/running/activities/${ACTIVITY_ID}`
const AI_EP = constants.endpoints.running_ai_insights.list
const AI_GEN_EP = constants.endpoints.running_ai_insights.generate

// ---------------------------------------------------------------------------
// Shared fixtures
// ---------------------------------------------------------------------------

const baseActivity = {
  id: ACTIVITY_ID,
  name: 'Long Run with Zones',
  activity_type: 'Run',
  source: 'strava',
  started_at: '2026-05-26T06:00:00Z',
  distance_m: 15000,
  moving_time_sec: 5400,
  duration_sec: 5460,
  avg_pace_sec_per_km: 360,
  avg_hr: 148,
  max_hr: 172,
  avg_cadence: 83,
  elevation_gain_m: 80,
  calories: 900,
  pr_count: 0,
  workout_type: null,
  summary_polyline: null,
  gear: null,
  device_name: null,
  notes: null,
  weather_summary: null,
  zones: null,
}

const hrZonesData = {
  heart_rate: {
    zones: [
      { min: 0, max: 114, time: 600 }, // Z1 Recovery
      { min: 115, max: 152, time: 1800 }, // Z2 Aerobic
      { min: 153, max: 171, time: 2100 }, // Z3 Tempo
      { min: 172, max: 190, time: 600 }, // Z4 Threshold
      { min: 191, max: 220, time: 300 }, // Z5 VO2max
    ],
  },
}

const dashboardFixture = {
  training_load: { next_race_goal: null },
  weekly_stats: null,
  ytd_stats: null,
  recent_activities: [],
  health_checkin: null,
}

// ---------------------------------------------------------------------------
// Shared stubs — reused across all describe blocks
// ---------------------------------------------------------------------------

const stubRtUsers = () => {
  cy.intercept('GET', '**/rest/v1/rt_users*', {
    statusCode: 200,
    body: [{ id: 'test-user-id', onboarding_complete: true }],
  }).as('rtUsersCheck')
}

const stubActivity = (overrides = {}) => {
  cy.intercept('GET', `/api/running/v1/activities/${ACTIVITY_ID}`, {
    statusCode: 200,
    body: {
      activity: { ...baseActivity, ...overrides },
      splits: [],
      laps: [],
      best_efforts: [],
      photos: [],
    },
  }).as('getActivity')
}

const stubDashboard = () => {
  cy.intercept('GET', '/api/running/v1/dashboard', {
    statusCode: 200,
    body: { data: dashboardFixture },
  }).as('getDashboard')
}

const stubRaceLog = () => {
  cy.intercept('GET', '/api/running/v1/race-log*', {
    statusCode: 200,
    body: { data: [] },
  }).as('getRaceLog')
}

const stubStreams = () => {
  cy.intercept('GET', `/api/running/v1/activities/*/streams*`, {
    statusCode: 200,
    body: {
      meta: {
        has_hr: false,
        has_cadence: false,
        has_altitude: false,
        total_points: 0,
        returned_points: 0,
        resolution: '10s',
      },
      data: [],
    },
  }).as('getStreams')
}

const stubInsight = (body, statusCode = 200) => {
  // fetchActivityInsight always calls res.json() and returns data.data?.[0] ?? null
  // For "no insight" pass { statusCode: 200, body: { data: [] } }
  // For a real insight pass { statusCode: 200, body: { data: [insightObj] } }
  // For fetch error pass a non-2xx statusCode with an error body
  cy.intercept('GET', `${AI_EP}*`, { statusCode, body }).as('getInsight')
}

const visitAndWait = () => {
  cy.viewport(1280, 720)
  cy.visit(DETAIL_URL)
  cy.wait('@getActivity')
}

// ---------------------------------------------------------------------------
// A. Auth guard
// ---------------------------------------------------------------------------

describe('Activity Detail (HR Zones + AI Insight) — Auth guard', () => {
  it('unauthenticated visit redirects to /login', () => {
    cy.clearAllCookies()
    cy.clearAllLocalStorage()
    cy.visit(DETAIL_URL, { failOnStatusCode: false })
    cy.url().should('include', '/login')
  })
})

// ---------------------------------------------------------------------------
// B. HrZonesChart — empty state (no zone data)
// ---------------------------------------------------------------------------

describe('HrZonesChart — empty state when no zone data', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    // Activity with zones: null (default)
    stubActivity()
    stubDashboard()
    stubRaceLog()
    stubStreams()
    stubInsight({ data: [] })
    visitAndWait()
  })

  it('hrZonesSection is always rendered', () => {
    cy.get(`#${IDS.hr_zones_section}`).should('exist')
  })

  it('shows "Zone data not available" when activity.zones is null', () => {
    cy.get(`#${IDS.hr_zones_empty}`).should('exist').and('contain.text', 'Zone data not available')
  })

  it('does not render zone bar rows when zones is null', () => {
    // No percentage text should appear in the section
    cy.get(`#${IDS.hr_zones_section}`).should('not.contain.text', '%')
  })
})

// ---------------------------------------------------------------------------
// C. HrZonesChart — happy path (Z1-Z5 data present)
// ---------------------------------------------------------------------------

describe('HrZonesChart — renders Z1-Z5 rows when zone data is present', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubActivity({ zones: hrZonesData })
    stubDashboard()
    stubRaceLog()
    stubStreams()
    stubInsight({ data: [] })
    visitAndWait()
  })

  it('does not show empty state when zones are present', () => {
    cy.get(`#${IDS.hr_zones_empty}`).should('not.exist')
  })

  it('renders 5 zone rows', () => {
    // Each zone row has a label like "Z1 Recovery", "Z2 Aerobic", etc.
    cy.get(`#${IDS.hr_zones_section}`).within(() => {
      cy.contains('Z1 Recovery').should('exist')
      cy.contains('Z2 Aerobic').should('exist')
      cy.contains('Z3 Tempo').should('exist')
      cy.contains('Z4 Threshold').should('exist')
      cy.contains('Z5 VO2max').should('exist')
    })
  })

  it('renders HR range labels for each zone', () => {
    cy.get(`#${IDS.hr_zones_section}`).within(() => {
      // Z1 should say "< 114 bpm" and Z5 "> 191 bpm"
      cy.contains('< 114 bpm').should('exist')
      cy.contains('> 191 bpm').should('exist')
      cy.contains('115–152 bpm').should('exist')
    })
  })

  it('renders percentage and duration for each zone', () => {
    // Total time = 600+1800+2100+600+300 = 5400
    // Z2: 1800/5400 = 33%
    cy.get(`#${IDS.hr_zones_section}`).within(() => {
      cy.contains('33%').should('exist')
      // Z3: 2100/5400 = 39%
      cy.contains('39%').should('exist')
    })
  })

  it('renders a filled bar for each zone (has style with backgroundColor)', () => {
    cy.get(`#${IDS.hr_zones_section}`).within(() => {
      // Each zone bar has an inline backgroundColor style
      cy.get('div[style*="background-color"]').should('have.length', 5)
    })
  })
})

// ---------------------------------------------------------------------------
// D. AIInsightCard — loading state
// ---------------------------------------------------------------------------

describe('AIInsightCard — loading skeleton while fetch is in-flight', () => {
  it('shows loading skeleton before insight fetch resolves', () => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubActivity()
    stubDashboard()
    stubRaceLog()
    stubStreams()

    // Delay insight response to catch loading state before fetch resolves
    cy.intercept('GET', `${AI_EP}*`, (req) => {
      req.reply((res) => {
        res.setDelay(600)
        res.send({ statusCode: 200, body: { data: [] } })
      })
    }).as('getInsightDelayed')

    cy.viewport(1280, 720)
    cy.visit(DETAIL_URL)
    cy.wait('@getActivity')

    cy.get(`#${IDS.ai_insight_card}`).should('exist')
    cy.get(`#${IDS.ai_insight_loading}`).should('exist')
  })
})

// ---------------------------------------------------------------------------
// E. AIInsightCard — empty state (no insight)
// ---------------------------------------------------------------------------

describe('AIInsightCard — empty state with focus buttons when no insight exists', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubActivity()
    stubDashboard()
    stubRaceLog()
    stubStreams()
    stubInsight({ data: [] })
    visitAndWait()
    cy.wait('@getInsight')
  })

  it('card root element is always rendered', () => {
    // Card layout changed in v1.2 — no longer a bordered card, now a space-y-4 container
    cy.get(`#${IDS.ai_insight_card}`).should('exist')
  })

  it('shows "AI Coach" label and BETA badge', () => {
    cy.get(`#${IDS.ai_insight_card}`).within(() => {
      cy.contains('AI Coach').should('be.visible')
      cy.contains('BETA').should('be.visible')
    })
  })

  it('shows empty state with coaching prompt text', () => {
    // Text changed in v1.2 to "Get AI-powered coaching insights..."
    cy.get(`#${IDS.ai_insight_empty}`)
      .scrollIntoView()
      .should('be.visible')
      .and('contain.text', 'Choose a focus to start')
  })

  it('renders focus buttons for generating an insight', () => {
    cy.get(`[id^="${IDS.ai_insight_generate_btn}_"]`).should('have.length.gte', 1)
  })

  it('does not show loading, pending, content or error states', () => {
    cy.get(`#${IDS.ai_insight_loading}`).should('not.exist')
    cy.get(`#${IDS.ai_insight_pending}`).should('not.exist')
    cy.get(`#${IDS.ai_insight_content}`).should('not.exist')
    cy.get(`#${IDS.ai_insight_error}`).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// F. AIInsightCard — generate → pending state
// ---------------------------------------------------------------------------

describe('AIInsightCard — clicking generate triggers POST and shows pending state', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubActivity()
    stubDashboard()
    stubRaceLog()
    stubStreams()
    stubInsight({ data: [] })

    cy.intercept('POST', AI_GEN_EP, {
      statusCode: 202,
      body: { message: 'Generation queued' },
    }).as('postGenerate')

    visitAndWait()
    cy.wait('@getInsight')
  })

  it('clicking the first focus button calls POST generate and transitions to pending state', () => {
    cy.get(`[id^="${IDS.ai_insight_generate_btn}_"]`).first().click()
    cy.wait('@postGenerate')

    cy.get(`#${IDS.ai_insight_pending}`).should('be.visible')
    cy.get(`#${IDS.ai_insight_pending}`).within(() => {
      cy.contains('Analyzing your run...').should('be.visible')
      cy.contains('Usually').should('be.visible')
    })
  })

  it('pending state shows a Refresh button', () => {
    cy.get(`[id^="${IDS.ai_insight_generate_btn}_"]`).first().click()
    cy.wait('@postGenerate')

    cy.get(`#${IDS.ai_insight_pending}`).within(() => {
      // Pending state uses aiInsightRefresh — distinct from aiInsightRetry in error state
      cy.get(`#${IDS.ai_insight_refresh}`).should('be.visible').and('contain.text', 'Refresh')
    })
  })
})

// ---------------------------------------------------------------------------
// G. AIInsightCard — content state (completed + valid)
// ---------------------------------------------------------------------------

describe('AIInsightCard — content state when insight is completed and valid', () => {
  const insightFixture = {
    id: 'insight-001',
    insight_type: 'post_activity',
    status: 'completed',
    is_valid: true,
    title: 'Post-Run Analysis',
    content:
      '## Summary\n\nGreat aerobic run today.\n\n## Recommendations\n\n- Keep the easy pace\n- Add strides next week',
    data_refs: { focus: 'general' },
    acknowledged: false,
    created_at: '2026-05-26T09:00:00Z',
  }

  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubActivity()
    stubDashboard()
    stubRaceLog()
    stubStreams()
    stubInsight({ data: [insightFixture] })
    visitAndWait()
    cy.wait('@getInsight')
  })

  it('renders aiInsightContent section', () => {
    cy.get(`#${IDS.ai_insight_content}`).scrollIntoView().should('be.visible')
  })

  it('renders markdown section headers from content', () => {
    cy.get(`#${IDS.ai_insight_content}`).within(() => {
      cy.contains('Summary').should('exist')
      cy.contains('Recommendations').should('exist')
    })
  })

  it('renders list items from bullet points in content', () => {
    cy.get(`#${IDS.ai_insight_content}`).within(() => {
      cy.contains('Keep the easy pace').should('exist')
      cy.contains('Add strides next week').should('exist')
    })
  })

  it('shows re-analyze focus buttons below the content', () => {
    cy.get(`#${IDS.ai_insight_content}`).within(() => {
      cy.get(`[id^="${IDS.ai_insight_generate_btn}_"]`).should('have.length.gte', 1)
    })
  })

  it('does not show loading, empty, pending or error states', () => {
    cy.get(`#${IDS.ai_insight_loading}`).should('not.exist')
    cy.get(`#${IDS.ai_insight_empty}`).should('not.exist')
    cy.get(`#${IDS.ai_insight_pending}`).should('not.exist')
    cy.get(`#${IDS.ai_insight_error}`).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// H. AIInsightCard — error state when fetch fails
// ---------------------------------------------------------------------------

describe('AIInsightCard — error state when GET insight fetch fails', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubActivity()
    stubDashboard()
    stubRaceLog()
    stubStreams()
    stubInsight({ error: 'Internal server error' }, 500)
    // 500 causes res.json() to throw after !res.ok check → loadError=true in component
    visitAndWait()
    cy.wait('@getInsight')
  })

  it('shows aiInsightError state after a fetch failure', () => {
    cy.get(`#${IDS.ai_insight_error}`).should('exist')
    cy.get(`#${IDS.ai_insight_error}`).within(() => {
      // Text changed in v1.2 from "Failed to load" to "Could not load analysis."
      cy.contains('Could not load analysis').should('exist')
    })
  })

  it('shows a retry button in the error state', () => {
    cy.get(`#${IDS.ai_insight_retry}`).scrollIntoView().should('be.visible')
  })

  it('clicking retry re-fetches and shows empty state on null response', () => {
    // Stub success BEFORE clicking so the intercept is in place when the request fires
    cy.intercept('GET', `${AI_EP}*`, { statusCode: 200, body: { data: [] } }).as('getInsightRetry')

    cy.get(`#${IDS.ai_insight_retry}`).click()
    cy.wait('@getInsightRetry')

    cy.get(`#${IDS.ai_insight_empty}`).should('be.visible')
    cy.get(`#${IDS.ai_insight_error}`).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// I. AIInsightCard — completed but invalid → falls back to empty (focus buttons)
// ---------------------------------------------------------------------------

describe('AIInsightCard — completed but invalid insight shows empty/focus state', () => {
  const invalidInsight = {
    id: 'insight-002',
    insight_type: 'post_activity',
    status: 'completed',
    is_valid: false,
    title: null,
    content: null,
    data_refs: null,
    acknowledged: false,
    created_at: '2026-05-26T09:00:00Z',
  }

  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubActivity()
    stubDashboard()
    stubRaceLog()
    stubStreams()
    stubInsight({ data: [invalidInsight] })
    visitAndWait()
    cy.wait('@getInsight')
  })

  it('shows empty state (focus buttons) when insight is completed but is_valid=false', () => {
    cy.get('#aiInsightInvalid_activityDetailPage').scrollIntoView().should('be.visible')
    cy.get(`[id^="${IDS.ai_insight_generate_btn}_"]`).should('have.length.gte', 1)
  })

  it('does not render aiInsightContent for invalid insight', () => {
    cy.get(`#${IDS.ai_insight_content}`).should('not.exist')
  })
})
