// Generated by Cypress Author — 2026-05-31
// Updated by Cypress Author — 2026-06-11 (removed suites A–D; RPE moved to rpe-section-ui.cy.js)
// Covers: AI Coach improvements on the Activity Detail page
//   /main/running/activities/:id
//
// Suites:
//   E. Focus buttons render (Performance & Pace, Recovery & Load, etc.)
//   F. Loading state — shimmer skeleton visible when pending stub
//   G. Rotating copy during pending (cy.clock, advance 6s)
//   H. Long-wait hint after 60s (cy.clock, advance 61000ms)
//   I. Activity comparison — section and trigger render in content state
//   J. Activity comparison — popover opens on desktop (1280×720)
//   K. Activity comparison — activity list renders inside popover
//   L. Get Recommendation button fires compare_activity focus

import constants from '../../../fixtures/app-constants.json'

const IDS = constants.test_ids.running_activity_detail
const ACTIVITY_ID = 'test-activity-id-aicoach-improvements'
const DETAIL_URL = `/main/running/activities/${ACTIVITY_ID}`
const AI_EP = constants.endpoints.running_ai_insights.list
const AI_GEN_EP = constants.endpoints.running_ai_insights.generate
const ACTIVITIES_EP = constants.endpoints.running_manual.activities

// ---------------------------------------------------------------------------
// Shared fixtures
// ---------------------------------------------------------------------------

const baseActivity = {
  id: ACTIVITY_ID,
  name: 'Morning Easy Run',
  activity_type: 'Run',
  source: 'strava',
  started_at: '2026-05-31T06:00:00Z',
  distance_m: 10000,
  moving_time_sec: 3600,
  duration_sec: 3650,
  avg_pace_sec_per_km: 360,
  avg_hr: 145,
  max_hr: 168,
  avg_cadence: 82,
  elevation_gain_m: 50,
  calories: 700,
  pr_count: 0,
  workout_type: null,
  summary_polyline: null,
  gear: null,
  device_name: null,
  notes: null,
  weather_summary: null,
  zones: null,
}

// A completed, valid insight fixture used across content-state suites
const completedInsight = {
  id: 'insight-aicoach-001',
  insight_type: 'post_activity',
  status: 'completed',
  is_valid: true,
  title: 'Post-Run Analysis',
  content:
    '## Summary\n\nSolid aerobic run.\n\n## Recommendations\n\n- Maintain this easy pace\n- Add strides on Tuesday',
  data_refs: { focus: 'general' },
  acknowledged: false,
  created_at: '2026-05-31T08:00:00Z',
}

// ---------------------------------------------------------------------------
// Shared stub helpers — mirrors the pattern from activity-detail-ui.cy.js
// ---------------------------------------------------------------------------

const stubRtUsers = () => {
  cy.intercept('GET', '**/rest/v1/rt_users*', {
    statusCode: 200,
    body: [{ id: 'test-user-id', onboarding_complete: true }],
  }).as('rtUsersCheck')
}

const stubActivity = (overrides = {}) => {
  cy.intercept('GET', `/api/running/v1/activities/${ACTIVITY_ID}`, {
    statusCode: 200,
    body: {
      activity: { ...baseActivity, ...overrides },
      splits: [],
      laps: [],
      best_efforts: [],
      photos: [],
    },
  }).as('getActivity')
}

const stubDashboard = () => {
  cy.intercept('GET', '/api/running/v1/dashboard', {
    statusCode: 200,
    body: {
      data: {
        training_load: { next_race_goal: null },
        weekly_stats: null,
        ytd_stats: null,
        recent_activities: [],
        health_checkin: null,
      },
    },
  }).as('getDashboard')
}

const stubRaceLog = () => {
  cy.intercept('GET', '/api/running/v1/race-log*', {
    statusCode: 200,
    body: { data: [] },
  }).as('getRaceLog')
}

const stubStreams = () => {
  cy.intercept('GET', `/api/running/v1/activities/*/streams*`, {
    statusCode: 200,
    body: {
      meta: {
        has_hr: false,
        has_cadence: false,
        has_altitude: false,
        total_points: 0,
        returned_points: 0,
        resolution: '10s',
      },
      data: [],
    },
  }).as('getStreams')
}

// stubInsight stubs GET for AI insights list endpoint
// Pass { data: [] } for no insight, { data: [insightObj] } for existing insight,
// or { status: 'pending' } body for pending state
const stubInsight = (body, statusCode = 200) => {
  cy.intercept('GET', `${AI_EP}*`, { statusCode, body }).as('getInsight')
}

const stubInsightPending = () => {
  cy.intercept('GET', `${AI_EP}*`, {
    statusCode: 200,
    body: {
      data: [
        {
          id: 'insight-pending-001',
          insight_type: 'post_activity',
          status: 'pending',
          is_valid: true,
          title: null,
          content: null,
          data_refs: null,
          acknowledged: false,
          created_at: '2026-05-31T08:00:00Z',
        },
      ],
    },
  }).as('getInsightPending')
}

const stubGeneratePost = () => {
  cy.intercept('POST', AI_GEN_EP, {
    statusCode: 202,
    body: { queued: true, message: 'Analisis sedang diproses' },
  }).as('postGenerate')
}

// Stub the activities list for comparison popover
const stubActivitiesList = (items = []) => {
  cy.intercept('GET', `${ACTIVITIES_EP}*`, {
    statusCode: 200,
    body: items,
  }).as('getActivities')
}

const visitAndWait = () => {
  cy.viewport(1280, 720)
  cy.setupApiAuthCookies()
  cy.visit(DETAIL_URL)
  cy.wait('@getActivity')
}

// ---------------------------------------------------------------------------
// E. Focus buttons render in empty state
// ---------------------------------------------------------------------------

describe('AI Coach — focus buttons render', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubActivity()
    stubDashboard()
    stubRaceLog()
    stubStreams()
    stubInsight({ data: [] })
    visitAndWait()
    cy.wait('@getInsight')
  })

  it('Performance & Pace focus button renders', () => {
    cy.get(`#aiInsightGenerateBtn_performance_activityDetailPage`)
      .scrollIntoView()
      .should('be.visible')
      .and('contain.text', 'Performance & Pace')
  })

  it('Recovery & Load focus button renders', () => {
    cy.get(`#aiInsightGenerateBtn_recovery_activityDetailPage`)
      .scrollIntoView()
      .should('be.visible')
      .and('contain.text', 'Recovery & Load')
  })

  it('Race Tips focus button renders', () => {
    cy.get(`#aiInsightGenerateBtn_next_race_activityDetailPage`)
      .scrollIntoView()
      .should('be.visible')
      .and('contain.text', 'Race Tips')
  })

  it('Next Training focus button renders', () => {
    cy.get(`#aiInsightGenerateBtn_next_training_activityDetailPage`)
      .scrollIntoView()
      .should('be.visible')
      .and('contain.text', 'Next Training')
  })

  it('at least 4 focus buttons are rendered', () => {
    cy.get(`[id^="${IDS.ai_insight_generate_btn}_"]`).should('have.length.gte', 4)
  })
})

// ---------------------------------------------------------------------------
// F. Loading state — shimmer skeleton visible when pending stub
// ---------------------------------------------------------------------------

describe('AI Coach — loading skeleton while fetch is in-flight', () => {
  it('shows shimmer loading skeleton before insight fetch resolves', () => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubActivity()
    stubDashboard()
    stubRaceLog()
    stubStreams()

    // Delay the insight response so loading state is catchable
    cy.intercept('GET', `${AI_EP}*`, (req) => {
      req.reply((res) => {
        res.setDelay(700)
        res.send({ statusCode: 200, body: { data: [] } })
      })
    }).as('getInsightDelayed')

    cy.viewport(1280, 720)
    cy.visit(DETAIL_URL)
    cy.wait('@getActivity')

    cy.get(`#${IDS.ai_insight_loading}`).should('exist')
  })

  it('shows pending shimmer skeleton when insight status is pending', () => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubActivity()
    stubDashboard()
    stubRaceLog()
    stubStreams()
    stubInsightPending()
    visitAndWait()
    cy.wait('@getInsightPending')

    cy.get(`#${IDS.ai_insight_pending_skeleton}`).should('exist')
    cy.get(`#${IDS.ai_insight_pending_bar}`).should('exist')
  })
})

// ---------------------------------------------------------------------------
// G. Rotating copy during pending (cy.clock, advance 6s)
// ---------------------------------------------------------------------------

describe('AI Coach — rotating status copy during pending state', () => {
  it('shows initial copy at 0s and different copy after 6s', () => {
    // Use cy.clock() before visit so the component initialises with controlled time
    cy.clock()

    cy.setupApiAuthCookies()
    stubRtUsers()
    stubActivity()
    stubDashboard()
    stubRaceLog()
    stubStreams()
    stubInsightPending()

    cy.viewport(1280, 720)
    cy.visit(DETAIL_URL)
    cy.wait('@getActivity')
    cy.wait('@getInsightPending')

    // Ensure the pending section is fully rendered before ticking the clock,
    // so the fake setInterval(1000) timer is registered before cy.tick fires it
    cy.get(`#${IDS.ai_insight_pending}`).should('exist')

    // At 0s elapsed: first copy bucket applies (< 5s)
    cy.get(`#${IDS.ai_insight_pending_status}`)
      .should('exist')
      .and('contain.text', 'Reading your run data...')

    // Advance clock 6 seconds to reach the second copy bucket (5–15s)
    cy.tick(6000)

    cy.get(`#${IDS.ai_insight_pending_status}`).should(
      'contain.text',
      'Analyzing pace, HR zones, and splits...'
    )
  })
})

// ---------------------------------------------------------------------------
// H. Long-wait hint after 60s (cy.clock, advance 61000ms)
// ---------------------------------------------------------------------------

describe('AI Coach — long-wait hint appears after 60 seconds', () => {
  it('long-wait hint is hidden initially and appears after 60s', () => {
    cy.clock()

    cy.setupApiAuthCookies()
    stubRtUsers()
    stubActivity()
    stubDashboard()
    stubRaceLog()
    stubStreams()
    stubInsightPending()

    cy.viewport(1280, 720)
    cy.visit(DETAIL_URL)
    cy.wait('@getActivity')
    cy.wait('@getInsightPending')

    // Ensure the pending section is fully rendered before ticking the clock,
    // so the fake setTimeout(60000) timer is registered before cy.tick fires it
    cy.get(`#${IDS.ai_insight_pending}`).should('exist')

    // Long-wait hint should NOT exist before 60s
    cy.get(`#${IDS.ai_insight_long_wait_hint}`).should('not.exist')

    // Advance clock past the 60s threshold
    cy.tick(61000)

    cy.get(`#${IDS.ai_insight_long_wait_hint}`)
      .should('exist')
      .and('contain.text', 'This is taking longer than usual')
  })

  it('long-wait hint contains a "Try again" action button', () => {
    cy.clock()

    cy.setupApiAuthCookies()
    stubRtUsers()
    stubActivity()
    stubDashboard()
    stubRaceLog()
    stubStreams()
    stubInsightPending()

    cy.viewport(1280, 720)
    cy.visit(DETAIL_URL)
    cy.wait('@getActivity')
    cy.wait('@getInsightPending')

    cy.tick(61000)

    cy.get(`#${IDS.ai_insight_long_wait_hint}`)
      .scrollIntoView()
      .within(() => {
        cy.contains('Try again').should('be.visible')
      })
  })
})

// ---------------------------------------------------------------------------
// I. Activity comparison — section and trigger render in content state
// ---------------------------------------------------------------------------

describe('AI Coach — comparison section renders in content state', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubActivity()
    stubDashboard()
    stubRaceLog()
    stubStreams()
    stubInsight({ data: [completedInsight] })
    visitAndWait()
    cy.wait('@getInsight')
  })

  it('compare section is rendered when insight is completed', () => {
    cy.get(`#${IDS.ai_insight_compare_section}`).scrollIntoView().should('exist').and('be.visible')
  })

  it('compare trigger button is rendered inside compare section', () => {
    cy.get(`#${IDS.ai_insight_compare_section}`).within(() => {
      cy.get(`#${IDS.ai_insight_compare_trigger}`)
        .scrollIntoView()
        .should('exist')
        .and('be.visible')
    })
  })

  it('compare trigger button contains "Compare with another run" text', () => {
    cy.get(`#${IDS.ai_insight_compare_trigger}`)
      .scrollIntoView()
      .should('contain.text', 'Compare with another run')
  })

  it('compare section and trigger are absent in empty state', () => {
    // Content state is rendered; scroll into view before checking visibility
    cy.get(`#${IDS.ai_insight_content}`).scrollIntoView().should('be.visible')
    cy.get(`#${IDS.ai_insight_compare_section}`).should('exist')
    // Confirm no Get Recommendation btn (needs a selected activity first)
    cy.get(`#${IDS.ai_insight_get_recommendation_btn}`).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// J. Activity comparison — popover opens on desktop (1280×720)
// ---------------------------------------------------------------------------

describe('AI Coach — comparison popover opens on desktop viewport', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubActivity()
    stubDashboard()
    stubRaceLog()
    stubStreams()
    stubInsight({ data: [completedInsight] })
    // Stub activities list for when popover fetches
    stubActivitiesList([])
    cy.viewport(1280, 720)
    cy.visit(DETAIL_URL)
    cy.wait('@getActivity')
    cy.wait('@getInsight')
  })

  it('clicking compare trigger opens the comparison popover on desktop', () => {
    cy.get(`#${IDS.ai_insight_compare_trigger}`).scrollIntoView().click()

    cy.get(`#${IDS.ai_insight_compare_popover}`).should('exist').and('be.visible')
  })

  it('popover does not show the sheet variant on desktop', () => {
    cy.get(`#${IDS.ai_insight_compare_trigger}`).scrollIntoView().click()

    cy.get(`#${IDS.ai_insight_compare_sheet}`).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// K. Activity comparison — activity list renders inside popover
// ---------------------------------------------------------------------------

describe('AI Coach — activity list renders inside comparison popover', () => {
  const comparisonActivities = [
    {
      id: 'compare-act-001',
      name: 'Morning Run',
      started_at: '2026-05-20T06:00:00Z',
      distance_m: 8000,
      avg_pace_sec_per_km: 370,
    },
    {
      id: 'compare-act-002',
      name: 'Easy Recovery',
      started_at: '2026-05-18T07:00:00Z',
      distance_m: 5000,
      avg_pace_sec_per_km: 400,
    },
  ]

  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubActivity()
    stubDashboard()
    stubRaceLog()
    stubStreams()
    stubInsight({ data: [completedInsight] })
    stubActivitiesList(comparisonActivities)
    cy.viewport(1280, 720)
    cy.visit(DETAIL_URL)
    cy.wait('@getActivity')
    cy.wait('@getInsight')
  })

  it('comparison command container is rendered inside the popover', () => {
    cy.get(`#${IDS.ai_insight_compare_trigger}`).scrollIntoView().click()
    cy.wait('@getActivities')

    cy.get(`#${IDS.ai_insight_compare_popover}`)
      .should('be.visible')
      .within(() => {
        cy.get(`#${IDS.ai_insight_compare_command}`).should('exist')
      })
  })

  it('activity list shows the stubbed activities grouped by month', () => {
    cy.get(`#${IDS.ai_insight_compare_trigger}`).scrollIntoView().click()
    cy.wait('@getActivities')

    cy.get(`#${IDS.ai_insight_compare_popover}`).within(() => {
      // en-US locale: toLocaleDateString('en-US', { day: 'numeric', month: 'short' }) → "May 20"
      cy.contains('May 20').should('exist')
      cy.contains('May 18').should('exist')
    })
  })

  it('selecting an activity from the list closes the popover', () => {
    cy.get(`#${IDS.ai_insight_compare_trigger}`).scrollIntoView().click()
    cy.wait('@getActivities')

    // Click the first activity button in the popover list
    cy.get(`#${IDS.ai_insight_compare_popover}`).find('button').first().click()

    // Popover closes after selection (allow time for Radix animation)
    cy.get(`#${IDS.ai_insight_compare_popover}`, { timeout: 8000 }).should('not.exist')
    // Compare pill appears with the selected activity info
    cy.get(`#${IDS.ai_insight_compare_pill}`).should('exist')
  })
})

// ---------------------------------------------------------------------------
// L. Get Recommendation button fires compare_activity focus
// ---------------------------------------------------------------------------

describe('AI Coach — Get Recommendation button fires compare_activity generate', () => {
  const comparisonActivities = [
    {
      id: 'compare-act-003',
      name: 'Interval Session',
      started_at: '2026-05-15T05:30:00Z',
      distance_m: 6000,
      avg_pace_sec_per_km: 320,
    },
  ]

  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubActivity()
    stubDashboard()
    stubRaceLog()
    stubStreams()
    stubInsight({ data: [completedInsight] })
    stubActivitiesList(comparisonActivities)
    stubGeneratePost()
    cy.viewport(1280, 720)
    cy.visit(DETAIL_URL)
    cy.wait('@getActivity')
    cy.wait('@getInsight')
  })

  it('Get Recommendation button is not visible until a comparison activity is selected', () => {
    cy.get(`#${IDS.ai_insight_get_recommendation_btn}`).should('not.exist')
  })

  it('Get Recommendation button appears after selecting a comparison activity', () => {
    // Open popover and select an activity
    cy.get(`#${IDS.ai_insight_compare_trigger}`).scrollIntoView().click()
    cy.wait('@getActivities')

    cy.get(`#${IDS.ai_insight_compare_popover}`).within(() => {
      cy.contains('May 15').click()
    })

    // Get Recommendation button should now be visible
    cy.get(`#${IDS.ai_insight_get_recommendation_btn}`)
      .scrollIntoView()
      .should('be.visible')
      .and('contain.text', 'Get Recommendation')
  })

  it('clicking Get Recommendation fires POST generate with compare_activity focus', () => {
    // Select a comparison activity first
    cy.get(`#${IDS.ai_insight_compare_trigger}`).scrollIntoView().click()
    cy.wait('@getActivities')

    cy.get(`#${IDS.ai_insight_compare_popover}`).within(() => {
      cy.contains('May 15').click()
    })

    // Click Get Recommendation
    cy.get(`#${IDS.ai_insight_get_recommendation_btn}`).scrollIntoView().click()

    // POST generate should have been called
    cy.wait('@postGenerate').then((interception) => {
      expect(interception.request.body).to.have.property('focus', 'compare_activity')
    })
  })

  it('Get Recommendation transitions card to pending state after POST', () => {
    // After POST returns 202, component sets insight to pending
    cy.get(`#${IDS.ai_insight_compare_trigger}`).scrollIntoView().click()
    cy.wait('@getActivities')

    cy.get(`#${IDS.ai_insight_compare_popover}`).within(() => {
      cy.contains('May 15').click()
    })

    // Stub subsequent GET to return pending
    cy.intercept('GET', `${AI_EP}*`, {
      statusCode: 200,
      body: {
        data: [
          {
            id: 'insight-compare-pending',
            insight_type: 'post_activity',
            status: 'pending',
            is_valid: true,
            title: null,
            content: null,
            data_refs: { focus: 'compare_activity' },
            acknowledged: false,
            created_at: '2026-05-31T09:00:00Z',
          },
        ],
      },
    }).as('getInsightPendingCompare')

    cy.get(`#${IDS.ai_insight_get_recommendation_btn}`).scrollIntoView().click()
    cy.wait('@postGenerate')

    // Card should now show pending state
    cy.get(`#${IDS.ai_insight_pending}`).should('exist')
  })
})
