// Generated by Cypress Author — 2026-05-26
// Covers: AI Insight endpoints
//   GET  /api/running/v1/ai/insights?activity_id=&type=post_activity
//     - 200 with insight object when one exists
//     - 204 / null body when no insight exists
//     - insight shape validation (id, status, is_valid, content, data_refs)
//     - 401 without auth
//   POST /api/running/v1/ai/insights/generate
//     - 202 with queued message for valid activity
//     - 400 for missing activity_id
//     - 401 without auth

import constants from '../../../fixtures/app-constants.json'

const LIST_EP = constants.endpoints.running_ai_insights.list
const GENERATE_EP = constants.endpoints.running_ai_insights.generate
const ACTIVITIES_BASE = constants.endpoints.running_manual.activities

// ---------------------------------------------------------------------------
// A. GET insights — Authenticated
// ---------------------------------------------------------------------------

describe('AI Insights API — GET (authenticated)', () => {
  let activityId

  before(() => {
    cy.setupApiAuthCookies()
    cy.request({
      method: 'GET',
      url: ACTIVITIES_BASE,
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(200)
      const activities = res.body?.data ?? res.body
      if (Array.isArray(activities) && activities.length > 0) {
        activityId = activities[0].id
      }
    })
  })

  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 or 204 for a valid activity_id → insight found or no content', function () {
    if (!activityId) this.skip()
    cy.request({
      method: 'GET',
      url: LIST_EP,
      qs: { activity_id: activityId, type: 'post_activity' },
      failOnStatusCode: false,
    }).then((res) => {
      // 200 = insight exists, 204 = no insight yet (both are valid)
      expect(res.status).to.be.oneOf([200, 204])
    })
  })

  it('insight object has required fields when status 200', function () {
    if (!activityId) this.skip()
    cy.request({
      method: 'GET',
      url: LIST_EP,
      qs: { activity_id: activityId, type: 'post_activity' },
      failOnStatusCode: false,
    }).then((res) => {
      if (res.status !== 200 || !res.body) {
        cy.log('No insight found for this activity — skipping field assertions')
        return
      }
      const raw = res.body.data ?? res.body
      const insight = Array.isArray(raw) ? raw[0] : raw
      if (!insight) {
        cy.log('No insight for this activity — skipping field assertions')
        return
      }
      expect(insight).to.have.property('id')
      expect(insight).to.have.property('status')
      expect(insight).to.have.property('is_valid')
      expect(insight).to.have.property('insight_type')
    })
  })

  it('insight status is one of: pending, completed, failed', function () {
    if (!activityId) this.skip()
    cy.request({
      method: 'GET',
      url: LIST_EP,
      qs: { activity_id: activityId, type: 'post_activity' },
      failOnStatusCode: false,
    }).then((res) => {
      if (res.status !== 200 || !res.body) {
        cy.log('No insight — skipping status assertion')
        return
      }
      const raw = res.body.data ?? res.body
      const insight = Array.isArray(raw) ? raw[0] : raw
      if (!insight) {
        cy.log('No insight — skipping status assertion')
        return
      }
      expect(['pending', 'completed', 'failed']).to.include(insight.status)
    })
  })

  it('completed insight with is_valid=true has a content string', function () {
    if (!activityId) this.skip()
    cy.request({
      method: 'GET',
      url: LIST_EP,
      qs: { activity_id: activityId, type: 'post_activity' },
      failOnStatusCode: false,
    }).then((res) => {
      if (res.status !== 200 || !res.body) return
      const insight = res.body.data ?? res.body
      if (insight.status !== 'completed' || !insight.is_valid) {
        cy.log('Insight not completed+valid — skipping content assertion')
        return
      }
      expect(insight.content).to.be.a('string').and.have.length.greaterThan(0)
    })
  })
})

// ---------------------------------------------------------------------------
// B. GET insights — Unauthenticated
// ---------------------------------------------------------------------------

describe('AI Insights API — GET (unauthenticated)', () => {
  it('returns 401 without a session', () => {
    cy.clearAllCookies()
    cy.request({
      method: 'GET',
      url: LIST_EP,
      qs: { activity_id: 'any-id', type: 'post_activity' },
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(401)
    })
  })
})

// ---------------------------------------------------------------------------
// C. POST generate — Authenticated
// ---------------------------------------------------------------------------

describe('AI Insights API — POST generate (authenticated)', () => {
  let activityId

  before(() => {
    cy.setupApiAuthCookies()
    cy.request({
      method: 'GET',
      url: ACTIVITIES_BASE,
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(200)
      const activities = res.body?.data ?? res.body
      if (Array.isArray(activities) && activities.length > 0) {
        activityId = activities[0].id
      }
    })
  })

  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 202 with queued message for a valid activity_id', function () {
    if (!activityId) this.skip()
    cy.request({
      method: 'POST',
      url: GENERATE_EP,
      body: { activity_id: activityId, focus: 'general' },
      failOnStatusCode: false,
    }).then((res) => {
      // 202 = queued, 200 = accepted, 429 = rate limited (all valid for this action)
      expect(res.status).to.be.oneOf([200, 202, 429])
    })
  })

  it('returns 400 when activity_id is missing from request body', () => {
    cy.request({
      method: 'POST',
      url: GENERATE_EP,
      body: { focus: 'performance' },
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(422)
    })
  })
})

// ---------------------------------------------------------------------------
// D. POST generate — Unauthenticated
// ---------------------------------------------------------------------------

describe('AI Insights API — POST generate (unauthenticated)', () => {
  it('returns 401 without a session', () => {
    cy.clearAllCookies()
    cy.request({
      method: 'POST',
      url: GENERATE_EP,
      body: { activity_id: 'any-id', focus: 'general' },
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(401)
    })
  })
})
