// Generated by Cypress Author — 2026-05-26
// Covers: HR Zones data via GET /api/running/v1/activities/:id
//   - zones field presence and shape when present
//   - zones.heart_rate.zones[] array structure
//   - activity without HR zones returns null or empty zones
//   - 401 when unauthenticated
//   - 404 for activity not owned by user

import constants from '../../../fixtures/app-constants.json'

const ACTIVITIES_BASE = constants.endpoints.running_manual.activities

// ---------------------------------------------------------------------------
// A. Authenticated — zones field shape
// ---------------------------------------------------------------------------

describe('HR Zones API — Authenticated (via GET activity)', () => {
  let activityId

  before(() => {
    cy.setupApiAuthCookies()
    // Fetch the first available activity to use as a real ID
    cy.request({
      method: 'GET',
      url: ACTIVITIES_BASE,
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(200)
      const activities = res.body?.data ?? res.body
      if (Array.isArray(activities) && activities.length > 0) {
        activityId = activities[0].id
      }
    })
  })

  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('activity detail response includes a zones field (object or null)', function () {
    if (!activityId) this.skip()
    cy.request({
      method: 'GET',
      url: `${ACTIVITIES_BASE}/${activityId}`,
    }).then((res) => {
      expect(res.status).to.eq(200)
      const { activity } = res.body
      // zones can be null (no HR data) or an object
      expect(activity).to.have.property('zones')
      if (activity.zones !== null) {
        expect(activity.zones).to.be.an('object')
      }
    })
  })

  it('zones.heart_rate.zones is an array when HR zone data is present', function () {
    if (!activityId) this.skip()
    cy.request({
      method: 'GET',
      url: `${ACTIVITIES_BASE}/${activityId}`,
    }).then((res) => {
      expect(res.status).to.eq(200)
      const { activity } = res.body
      if (!activity.zones || !activity.zones.heart_rate) {
        cy.log('No HR zone data on this activity — skipping zone array assertions')
        return
      }
      expect(activity.zones.heart_rate).to.have.property('zones')
      expect(activity.zones.heart_rate.zones).to.be.an('array')
    })
  })

  it('each HR zone entry has min, max, and time fields', function () {
    if (!activityId) this.skip()
    cy.request({
      method: 'GET',
      url: `${ACTIVITIES_BASE}/${activityId}`,
    }).then((res) => {
      expect(res.status).to.eq(200)
      const { activity } = res.body
      const hrZones = activity.zones?.heart_rate?.zones
      if (!hrZones || hrZones.length === 0) {
        cy.log('No HR zones on this activity — skipping field assertions')
        return
      }
      hrZones.forEach((zone) => {
        expect(zone).to.have.property('min')
        expect(zone).to.have.property('max')
        expect(zone).to.have.property('time')
        expect(zone.time).to.be.a('number')
      })
    })
  })

  it('HR zones array has exactly 5 entries when present', function () {
    if (!activityId) this.skip()
    cy.request({
      method: 'GET',
      url: `${ACTIVITIES_BASE}/${activityId}`,
    }).then((res) => {
      expect(res.status).to.eq(200)
      const { activity } = res.body
      const hrZones = activity.zones?.heart_rate?.zones
      if (!hrZones || hrZones.length === 0) {
        cy.log('No HR zones on this activity — skipping zone count assertion')
        return
      }
      expect(hrZones).to.have.length(5)
    })
  })
})

// ---------------------------------------------------------------------------
// B. Unauthenticated — 401
// ---------------------------------------------------------------------------

describe('HR Zones API — Unauthenticated', () => {
  it('returns 401 when no session is present', () => {
    cy.clearAllCookies()
    cy.request({
      method: 'GET',
      url: `${ACTIVITIES_BASE}/any-id`,
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(401)
    })
  })
})

// ---------------------------------------------------------------------------
// C. Ownership — 404 for activity not belonging to user
// ---------------------------------------------------------------------------

describe('HR Zones API — Ownership check', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 404 when activity ID does not belong to the authenticated user', () => {
    const nonExistentId = '00000000-0000-0000-0000-000000000000'
    cy.request({
      method: 'GET',
      url: `${ACTIVITIES_BASE}/${nonExistentId}`,
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(404)
    })
  })
})
