export const RPE_LEVELS = [
  {
    value: 1,
    label: 'Very Easy',
    breathing: 'Full conversation, nasal breathing',
    zone: 'Z1',
    use: 'Walk / warm-up',
    bg: '#16a34a',
    bgLight: '#dcfce7',
    text: '#fff',
  },
  {
    value: 2,
    label: 'Easy',
    breathing: 'Easy conversation',
    zone: 'Z1',
    use: 'Recovery jog',
    bg: '#22c55e',
    bgLight: '#dcfce7',
    text: '#fff',
  },
  {
    value: 3,
    label: 'Light',
    breathing: 'Comfortable, full sentences',
    zone: 'Z2',
    use: 'Long easy run',
    bg: '#4ade80',
    bgLight: '#dcfce7',
    text: '#166534',
  },
  {
    value: 4,
    label: 'Moderate',
    breathing: 'Sentences with occasional breath',
    zone: 'Z2',
    use: 'Aerobic base',
    bg: '#a3e635',
    bgLight: '#f7fee7',
    text: '#365314',
  },
  {
    value: 5,
    label: 'Steady',
    breathing: 'Short sentences, audible breathing',
    zone: 'Z3',
    use: 'Steady run',
    bg: '#eab308',
    bgLight: '#fefce8',
    text: '#fff',
  },
  {
    value: 6,
    label: 'Moderately Hard',
    breathing: '1–2 words at a time',
    zone: 'Z3',
    use: 'Marathon pace',
    bg: '#f97316',
    bgLight: '#fff7ed',
    text: '#fff',
  },
  {
    value: 7,
    label: 'Hard',
    breathing: 'Single words, focused',
    zone: 'Z4',
    use: 'Tempo / threshold',
    bg: '#ea580c',
    bgLight: '#fff7ed',
    text: '#fff',
  },
  {
    value: 8,
    label: 'Very Hard',
    breathing: 'Cannot talk, mouth breathing',
    zone: 'Z4',
    use: 'Cruise intervals',
    bg: '#ef4444',
    bgLight: '#fef2f2',
    text: '#fff',
  },
  {
    value: 9,
    label: 'Extremely Hard',
    breathing: 'Gasping',
    zone: 'Z5',
    use: 'VO2max intervals',
    bg: '#dc2626',
    bgLight: '#fef2f2',
    text: '#fff',
  },
  {
    value: 10,
    label: 'Max Effort',
    breathing: 'All-out, unsustainable >~1 min',
    zone: 'Z5+',
    use: 'Sprint / final kick',
    bg: '#991b1b',
    bgLight: '#fef2f2',
    text: '#fff',
  },
]
