// Generated by Cypress Author — 2026-08-10
export async function resetVo2maxTarget(supabase, userId) {
  const { data, error } = await supabase
    .from('rt_users')
    .update({ vo2max_target: null })
    .eq('id', userId)
    .select('vo2max_target')
    .maybeSingle()

  if (error) throw new Error(`DB query failed: ${error.message}`)
  return data
}
