// Generated by Cypress Author — 2026-05-28
// Covers: Race Log page UI — /main/running/race-log and /main/running/race-log/:id
//
// States tested:
//   - loading: skeleton (visible while fetch is in-flight)
//   - error: error container with "Try again" retry button
//   - empty: Medal icon + "No races logged yet" + CTA button
//   - list: renders race table rows ordered by race_date DESC (each row navigates to detail on click)
//
// Race table row:
//   - title, DNF badge, distance label (type column), date, dist, time, pace, place (#), male (#)
//   - clicking a row navigates to /main/running/race-log/:id
//   - no inline edit/delete buttons on list rows
//
// Add modal (RaceFormModal):
//   - id="raceLogFormModal" on DialogContent
//   - id="raceDate" on calendar popover trigger Button (NOT an input — use .click() + gridcell)
//   - id="dnf" on DNF Checkbox (Radix: <button role="checkbox">)
//   - id="finishTime" on finish time Input
//   - after successful save: modal closes and router navigates to new entry's detail page
//
// Edit modal (EditRaceModal — detail page only):
//   - only accessible from /main/running/race-log/:id
//   - edit button (id="editRaceBtn_raceDetailPage") is inside ActivitySection which only renders
//     when activity data is loaded; stub activity fetch to reveal the button
//   - id="editRaceModal_raceDetailPage" on DialogContent
//   - id="editRaceSaveBtn_raceDetailPage" on save button
//   - title input id="editRaceTitle" (NOT raceTitle)
//
// Delete confirmation (detail page only):
//   - id="deleteRaceBtn_raceDetailPage" on delete button
//   - id="deleteRaceConfirmBtn_raceDetailPage" on confirm button in AlertDialog

import constants from '../../../fixtures/app-constants.json'

const IDS = constants.test_ids.race_log
const RACE_LOG_URL = constants.routes.running_race_log
const LIST_EP = constants.endpoints.running_race_log.list
const DETAIL_EP = constants.endpoints.running_race_log.detail
const ACTIVITIES_EP = constants.endpoints.running_manual.activities

// ---------------------------------------------------------------------------
// Shared fixtures
// ---------------------------------------------------------------------------

const entry1 = {
  id: 'race-entry-1',
  title: 'Jakarta Marathon 2025',
  race_date: '2025-11-16',
  distance_m: 42195,
  finish_time_sec: 14400,
  avg_pace_sec_per_km: 341,
  avg_hr: 158,
  elevation_gain_m: 120,
  position_place: 42,
  position_male: 8,
  did_not_finish: false,
  activity_id: 'strava-act-1',
  notes: 'Good conditions, slight headwind on km 30-35.',
  created_at: '2025-11-16T12:00:00Z',
}

const entry2 = {
  id: 'race-entry-2',
  title: 'Bali Half Marathon 2025',
  race_date: '2025-08-10',
  distance_m: 21097.5,
  finish_time_sec: 6300,
  avg_pace_sec_per_km: 299,
  avg_hr: 165,
  elevation_gain_m: 210,
  position_place: null,
  position_male: null,
  did_not_finish: false,
  activity_id: null,
  notes: null,
  created_at: '2025-08-10T08:00:00Z',
}

const dnfEntry = {
  id: 'race-entry-3',
  title: 'Bromo Ultra DNF',
  race_date: '2025-06-01',
  distance_m: 50000,
  finish_time_sec: null,
  avg_pace_sec_per_km: null,
  avg_hr: null,
  elevation_gain_m: 800,
  position_place: null,
  position_male: null,
  did_not_finish: true,
  activity_id: null,
  notes: null,
  created_at: '2025-06-01T05:00:00Z',
}

// Minimal activity object used to stub the activity fetch on the detail page.
// ActivitySection only renders when activity data resolves, and the edit button
// lives inside ActivitySection.
const minimalActivity = {
  activity: {
    id: 'strava-act-1',
    name: 'Morning Run',
    started_at: '2025-11-16T05:00:00Z',
    distance_m: 42195,
    duration_sec: 14400,
    moving_time_sec: 14200,
    avg_pace_sec_per_km: 341,
    avg_hr: 158,
    activity_type: 'Run',
    source: 'strava',
    gear: null,
    zones: null,
    summary_polyline: null,
    aerobic_decoupling: null,
    efficiency_factor: null,
    device_name: null,
    description: null,
    weather_summary: null,
    elevation_gain_m: 120,
    elevation_loss_m: null,
    elev_high_m: null,
    elev_low_m: null,
    avg_cadence: null,
    device_watts: null,
    avg_watts: null,
    weighted_avg_watts: null,
    avg_temp_c: null,
    calories: null,
    relative_effort: null,
    perceived_exertion: null,
    kilojoules: null,
    pr_count: 0,
    achievement_count: 0,
    kudos_count: 0,
    max_hr: null,
    max_pace_sec_per_km: null,
    estimated_vo2max: null,
  },
  splits: [],
  laps: [],
  best_efforts: [],
  photos: [],
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const stubRtUsers = () => {
  cy.intercept('GET', '**/rest/v1/rt_users*', {
    statusCode: 200,
    body: [{ id: 'test-user-id', onboarding_complete: true }],
  }).as('rtUsersCheck')
}

const stubRaceLog = (entries = [], statusCode = 200) => {
  cy.intercept('GET', `${LIST_EP}*`, {
    statusCode,
    body: statusCode === 200 ? { data: entries, message: 'ok' } : { error: 'Server error' },
  }).as('getRaceLog')
}

const visitPage = () => {
  cy.viewport(1280, 720)
  cy.visit(RACE_LOG_URL)
}

// ---------------------------------------------------------------------------
// A. Auth guard
// ---------------------------------------------------------------------------

describe('Race Log — Auth guard', () => {
  it('unauthenticated visit redirects to /login', () => {
    cy.clearAllCookies()
    cy.clearAllLocalStorage()
    cy.visit(RACE_LOG_URL, { failOnStatusCode: false })
    cy.url().should('include', '/login')
  })
})

// ---------------------------------------------------------------------------
// B. Loading state
// ---------------------------------------------------------------------------

describe('Race Log — Loading skeleton', () => {
  it('shows skeleton while fetch is in-flight', () => {
    cy.setupApiAuthCookies()
    stubRtUsers()

    cy.intercept('GET', `${LIST_EP}*`, (req) => {
      req.reply((res) => {
        res.setDelay(600)
        res.send({ statusCode: 200, body: { data: [entry1], message: 'ok' } })
      })
    }).as('getRaceLogDelayed')

    visitPage()

    // Skeleton is nested inside the table wrapper which is shown even during loading
    cy.get(`[id="${IDS.loading_skeleton}"]`).should('exist').and('be.visible')
    // List wrapper is also present while loading (table shows skeleton rows inside it)
    cy.get(`[id="${IDS.list}"]`).should('exist')
  })
})

// ---------------------------------------------------------------------------
// C. Error state
// ---------------------------------------------------------------------------

describe('Race Log — Error state', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubRaceLog([], 500)
    visitPage()
    cy.wait('@getRaceLog')
  })

  it('renders error container with an alert role', () => {
    cy.get(`[id="${IDS.error}"]`).should('be.visible').and('have.attr', 'role', 'alert')
  })

  it('shows a "Try again" retry button', () => {
    cy.get(`[id="${IDS.error}"]`).within(() => {
      cy.contains('button', 'Try again').should('be.visible')
    })
  })

  it('retry button triggers a new fetch and shows list', () => {
    stubRaceLog([entry1])
    cy.get(`[id="${IDS.error}"]`).within(() => {
      cy.contains('button', 'Try again').click()
    })
    cy.get(`[id="${IDS.list}"]`).should('be.visible')
  })
})

// ---------------------------------------------------------------------------
// D. Empty state
// ---------------------------------------------------------------------------

describe('Race Log — Empty state', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubRaceLog([])
    visitPage()
    cy.wait('@getRaceLog')
  })

  it('renders empty state when data array is empty', () => {
    cy.get(`[id="${IDS.empty_state}"]`).should('be.visible')
  })

  it('shows "No races logged yet" message', () => {
    cy.get(`[id="${IDS.empty_state}"]`).should('contain.text', 'No races logged yet')
  })

  it('has a "Log your first race" CTA button', () => {
    cy.get(`[id="${IDS.empty_state}"]`).within(() => {
      cy.contains('button', 'Log your first race').should('be.visible')
    })
  })

  it('does not render loading skeleton or list', () => {
    cy.get(`[id="${IDS.loading_skeleton}"]`).should('not.exist')
    cy.get(`[id="${IDS.list}"]`).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// E. Race list — table rendering
// ---------------------------------------------------------------------------

describe('Race Log — Race list renders correctly', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubRaceLog([entry1, entry2, dnfEntry])
    visitPage()
    cy.wait('@getRaceLog')
  })

  it('renders the race list with correct number of rows', () => {
    cy.get(`[id="${IDS.list}"]`).should('be.visible')
    cy.get(`[id="${IDS.card}"]`).should('have.length', 3)
  })

  it('renders race title on each row', () => {
    cy.get(`[id="${IDS.list}"]`).within(() => {
      cy.contains('Jakarta Marathon 2025').should('be.visible')
      cy.contains('Bali Half Marathon 2025').should('be.visible')
      cy.contains('Bromo Ultra DNF').should('be.visible')
    })
  })

  it('shows DNF badge on did_not_finish entry', () => {
    cy.get(`[id="${IDS.list}"]`).within(() => {
      cy.contains('DNF').should('be.visible')
    })
  })

  it('shows finish time on rows that have it', () => {
    cy.get(`[id="${IDS.list}"]`).within(() => {
      // entry1 finish_time = 14400 sec = 04:00:00
      cy.contains('04:00:00').should('exist')
    })
  })

  it('shows position_place when set', () => {
    cy.get(`[id="${IDS.list}"]`).within(() => {
      cy.contains('#42').should('be.visible')
    })
  })

  it('shows position_male when set', () => {
    cy.get(`[id="${IDS.list}"]`).within(() => {
      cy.contains('#8').should('be.visible')
    })
  })

  it('clicking a row navigates to the race detail page', () => {
    // Stub the detail page fetch so the detail page can render
    cy.intercept('GET', `${DETAIL_EP}/${entry1.id}`, {
      statusCode: 200,
      body: { data: entry1, message: 'ok' },
    }).as('getDetail')

    cy.get(`[id="${IDS.card}"]`).first().click()
    cy.url().should('include', `/main/running/race-log/${entry1.id}`)
  })

  it('does not render empty state when list is populated', () => {
    cy.get(`[id="${IDS.empty_state}"]`).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// F. Page header + add button
// ---------------------------------------------------------------------------

describe('Race Log — Page header and add button', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubRaceLog([entry1])
    visitPage()
    cy.wait('@getRaceLog')
  })

  it('renders the page root element', () => {
    cy.get(`[id="${IDS.page}"]`).should('exist')
  })

  it('renders "Log race" add button in header', () => {
    cy.get(`[id="${IDS.add_btn}"]`).should('be.visible')
  })

  it('add button has sufficient touch target size (≥ 32px height)', () => {
    cy.get(`[id="${IDS.add_btn}"]`).invoke('outerHeight').should('be.gte', 32)
  })
})

// ---------------------------------------------------------------------------
// G. Add race modal — open / close
// ---------------------------------------------------------------------------

describe('Race Log — Add modal (open/close)', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubRaceLog([])
    visitPage()
    cy.wait('@getRaceLog')
  })

  it('modal is not visible on initial load', () => {
    cy.get(`[id="${IDS.form_modal}"]`).should('not.exist')
  })

  it('opens the add modal when "Log race" is clicked', () => {
    cy.get(`[id="${IDS.add_btn}"]`).click()
    cy.get(`[id="${IDS.form_modal}"]`).should('be.visible')
    cy.contains('Log a Race').should('be.visible')
  })

  it('closes the modal when Cancel is clicked', () => {
    cy.get(`[id="${IDS.add_btn}"]`).click()
    cy.get(`[id="${IDS.form_modal}"]`).should('be.visible')
    cy.get(`[id="${IDS.form_modal}"]`).within(() => {
      cy.contains('button', 'Cancel').click()
    })
    cy.get(`[id="${IDS.form_modal}"]`).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// H. Add race modal — validation
// ---------------------------------------------------------------------------

describe('Race Log — Add modal form validation', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubRaceLog([])
    visitPage()
    cy.wait('@getRaceLog')
    cy.get(`[id="${IDS.add_btn}"]`).click()
    cy.get(`[id="${IDS.form_modal}"]`).should('be.visible')
  })

  it('shows validation errors when submitting empty form', () => {
    cy.get(`[id="${IDS.save_btn}"]`).click()
    // Zod errors on required fields should surface as role="alert" elements
    cy.get(`[id="${IDS.form_modal}"]`).within(() => {
      cy.get('[role="alert"]').should('exist')
    })
  })

  it('finish time field is hidden when DNF checkbox is checked', () => {
    cy.get(`[id="${IDS.form_modal}"]`).within(() => {
      cy.get('input#finishTime').should('exist')
      // DNF is a Radix Checkbox rendered as <button role="checkbox">
      cy.get('button[role="checkbox"]#dnf').click()
      cy.get('input#finishTime').should('not.exist')
    })
  })

  it('finish time field reappears when DNF checkbox is unchecked', () => {
    cy.get(`[id="${IDS.form_modal}"]`).within(() => {
      cy.get('button[role="checkbox"]#dnf').click()
      cy.get('input#finishTime').should('not.exist')
      cy.get('button[role="checkbox"]#dnf').click()
      cy.get('input#finishTime').should('exist')
    })
  })
})

// ---------------------------------------------------------------------------
// I. Add race modal — successful save
// ---------------------------------------------------------------------------
// After a successful POST, RaceFormModal calls onSaved(result.data) then onClose().
// The page's onSaved handler navigates away to /main/running/race-log/:id.
// So the list page is no longer visible — assert on URL and modal closing instead.

describe('Race Log — Add modal successful save', () => {
  const newEntry = {
    id: 'new-entry-id',
    title: 'Test 10K',
    race_date: '2025-12-01',
    distance_m: 10000,
    finish_time_sec: 3000,
    avg_pace_sec_per_km: 300,
    avg_hr: null,
    elevation_gain_m: null,
    position_place: null,
    position_male: null,
    did_not_finish: false,
    activity_id: null,
    notes: null,
    created_at: '2025-12-01T10:00:00Z',
  }

  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubRaceLog([])
    visitPage()
    cy.wait('@getRaceLog')

    cy.intercept('POST', LIST_EP, {
      statusCode: 201,
      body: { data: newEntry, message: 'Created' },
    }).as('createRace')
  })

  it('closes modal and navigates to new entry detail page after successful save', () => {
    cy.get(`[id="${IDS.add_btn}"]`).click()
    cy.get(`[id="${IDS.form_modal}"]`).should('be.visible')

    // Fill title
    cy.get('#raceTitle').type('Test 10K')

    // Pick date using calendar popover (raceDate is a Button, not an input)
    cy.get('#raceDate').click()
    cy.get('[role="gridcell"] button:not([disabled])').first().click()

    // Select distance preset
    cy.get(`[id="${IDS.form_modal}"]`).within(() => {
      cy.get('[role="combobox"]').first().click()
    })
    cy.get('[role="option"]').contains('10K').click()

    // Fill finish time
    cy.get('#finishTime').type('00:50:00')

    cy.get(`[id="${IDS.save_btn}"]`).click()
    cy.wait('@createRace')

    // Modal closes and page navigates to detail (list no longer visible)
    cy.get(`[id="${IDS.form_modal}"]`).should('not.exist')
    cy.url().should('include', newEntry.id)
  })

  it('shows server error message when POST fails', () => {
    cy.intercept('POST', LIST_EP, {
      statusCode: 500,
      body: { error: 'Internal server error' },
    }).as('createRaceFail')

    cy.get(`[id="${IDS.add_btn}"]`).click()
    cy.get('#raceTitle').type('Fail Race')

    // Pick date using calendar popover
    cy.get('#raceDate').click()
    cy.get('[role="gridcell"] button:not([disabled])').first().click()

    cy.get(`[id="${IDS.form_modal}"]`).within(() => {
      cy.get('[role="combobox"]').first().click()
    })
    cy.get('[role="option"]').contains('5K').click()

    cy.get('#finishTime').type('00:20:00')

    cy.get(`[id="${IDS.save_btn}"]`).click()
    cy.wait('@createRaceFail')

    // Modal stays open and shows server error
    cy.get(`[id="${IDS.form_modal}"]`).should('be.visible')
    cy.get(`[id="${IDS.form_modal}"]`).within(() => {
      cy.get('[role="alert"]').should('exist')
    })
  })
})

// ---------------------------------------------------------------------------
// J. Edit modal — detail page (pre-fill and update)
// ---------------------------------------------------------------------------
// Edit is only available on the detail page. ActivitySection (which contains
// editRaceBtn_raceDetailPage) only renders when activity data is loaded.
// Stub both the detail endpoint and the activity endpoint to ensure the
// edit button becomes visible.

describe('Race Log — Edit modal on detail page', () => {
  const DETAIL_URL = `${RACE_LOG_URL}/${entry1.id}`
  const PATCH_EP = `${DETAIL_EP}/${entry1.id}`

  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()

    // Stub detail page fetch
    cy.intercept('GET', `${DETAIL_EP}/${entry1.id}`, {
      statusCode: 200,
      body: { data: entry1, message: 'ok' },
    }).as('getDetailJ')

    // Stub activity fetch so ActivitySection (and edit button) renders
    cy.intercept('GET', `${ACTIVITIES_EP}/${entry1.activity_id}`, {
      statusCode: 200,
      body: minimalActivity,
    }).as('getActivityJ')

    // Stub subjective health fetch that fires after activity loads
    cy.intercept('GET', '**/api/running/v1/health/subjective*', {
      statusCode: 200,
      body: null,
    }).as('healthJ')

    cy.viewport(1280, 720)
    cy.visit(DETAIL_URL)
    cy.wait('@getDetailJ')
    cy.wait('@getActivityJ')
  })

  it('opens edit modal with pre-filled title when edit button is clicked', () => {
    cy.get(`[id="${IDS.edit_btn}"]`).should('be.visible').click()
    cy.get(`[id="${IDS.edit_modal}"]`).should('be.visible')
    cy.contains('Edit Race Entry').should('be.visible')
    // Edit modal uses id="editRaceTitle", not raceTitle
    cy.get('#editRaceTitle').should('have.value', entry1.title)
  })

  it('updates entry and closes modal on successful PATCH', () => {
    const updatedEntry = { ...entry1, title: 'Jakarta Marathon 2025 Updated' }
    cy.intercept('PATCH', PATCH_EP, {
      statusCode: 200,
      body: { data: updatedEntry, message: 'Updated' },
    }).as('updateRaceJ')

    cy.get(`[id="${IDS.edit_btn}"]`).click()
    cy.get(`[id="${IDS.edit_modal}"]`).should('be.visible')

    cy.get('#editRaceTitle').clear().type('Jakarta Marathon 2025 Updated')
    cy.get(`[id="${IDS.edit_save_btn}"]`).click()
    cy.wait('@updateRaceJ')

    cy.get(`[id="${IDS.edit_modal}"]`).should('not.exist')
  })

  it('shows server error inside edit modal when PATCH fails', () => {
    cy.intercept('PATCH', PATCH_EP, {
      statusCode: 500,
      body: { error: 'Internal server error' },
    }).as('updateRaceFailJ')

    cy.get(`[id="${IDS.edit_btn}"]`).click()
    cy.get(`[id="${IDS.edit_modal}"]`).should('be.visible')

    cy.get('#editRaceTitle').clear().type('Will Fail')
    cy.get(`[id="${IDS.edit_save_btn}"]`).click()
    cy.wait('@updateRaceFailJ')

    // Modal stays open on error
    cy.get(`[id="${IDS.edit_modal}"]`).should('be.visible')
    cy.get(`[id="${IDS.edit_modal}"]`).within(() => {
      cy.get('[role="alert"]').should('exist')
    })
  })
})

// ---------------------------------------------------------------------------
// K. Delete confirmation dialog — detail page
// ---------------------------------------------------------------------------

describe('Race Log — Delete confirmation dialog on detail page', () => {
  const DETAIL_URL = `${RACE_LOG_URL}/${entry1.id}`

  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()

    cy.intercept('GET', `${DETAIL_EP}/${entry1.id}`, {
      statusCode: 200,
      body: { data: entry1, message: 'ok' },
    }).as('getDetailK')

    // Stub activity fetch (needed for the page to finish loading entry data)
    cy.intercept('GET', `${ACTIVITIES_EP}/${entry1.activity_id}`, {
      statusCode: 200,
      body: minimalActivity,
    }).as('getActivityK')

    cy.intercept('GET', '**/api/running/v1/health/subjective*', {
      statusCode: 200,
      body: null,
    }).as('healthK')

    cy.viewport(1280, 720)
    cy.visit(DETAIL_URL)
    cy.wait('@getDetailK')
  })

  it('opens AlertDialog when delete button is clicked', () => {
    cy.get(`[id="${IDS.delete_btn}"]`).click()
    cy.contains('Delete this race entry?').should('be.visible')
  })

  it('shows the entry title in the confirmation dialog', () => {
    cy.get(`[id="${IDS.delete_btn}"]`).click()
    cy.get('[role="alertdialog"]').should('be.visible').contains(entry1.title)
  })

  it('closes dialog without deleting when Cancel is clicked', () => {
    cy.get(`[id="${IDS.delete_btn}"]`).click()
    cy.contains('Delete this race entry?').should('be.visible')
    cy.contains('button', 'Cancel').click()
    cy.contains('Delete this race entry?').should('not.exist')
    // Entry is still present (page did not navigate away)
    cy.get(`[id="${IDS.detail_page}"]`).should('exist')
  })

  it('deletes entry and navigates back to race log list on confirm', () => {
    cy.intercept('DELETE', `${DETAIL_EP}/${entry1.id}`, {
      statusCode: 200,
      body: { message: 'Deleted' },
    }).as('deleteRaceK')

    cy.get(`[id="${IDS.delete_btn}"]`).click()
    cy.get(`[id="${IDS.delete_confirm_btn}"]`).click()
    cy.wait('@deleteRaceK')

    // After delete, page navigates back to /main/running/race-log
    cy.url().should('include', '/main/running/race-log')
    cy.url().should('not.include', entry1.id)
  })
})

// ---------------------------------------------------------------------------
// L. Mobile responsive
// ---------------------------------------------------------------------------

describe('Race Log — Mobile responsive (375px)', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubRaceLog([entry1])
    cy.viewport(375, 812)
    cy.visit(RACE_LOG_URL)
    cy.wait('@getRaceLog')
  })

  it('renders page without horizontal overflow', () => {
    cy.get('body').then(($body) => {
      expect($body[0].scrollWidth).to.be.lte($body[0].clientWidth + 5)
    })
  })

  it('add button is visible on mobile', () => {
    cy.get(`[id="${IDS.add_btn}"]`).should('be.visible')
  })

  it('race table rows are visible on mobile', () => {
    // id="raceLogCard" is placed on each <TableRow> — should be visible
    cy.get(`[id="${IDS.card}"]`).should('be.visible')
  })
})
