// Generated by Cypress Author — 2026-06-02
// UI-only spec: uses cy.visit + DOM assertions.
// API commands in before()/beforeEach() are for stub setup only — no real DB writes.
// Covers UpcomingRacesSection and UpcomingRaceCard interactions on the race-log page.

import { TEST_IDS } from '../../../fixtures/test-ids.js'
import { ROUTES } from '../../../fixtures/routes.js'
import { RUNNING_ENDPOINTS } from '../../../fixtures/endpoints.js'

const IDS = TEST_IDS.upcoming_races
const RACE_LOG_URL = ROUTES.running_race_log
const UPCOMING_EP = RUNNING_ENDPOINTS.UPCOMING_RACES
const RACE_LOG_EP = RUNNING_ENDPOINTS.RACE_LOG_LIST

// ─────────────────────────────────────────────────────────────────────────────
// Shared stubs / fixtures
// ─────────────────────────────────────────────────────────────────────────────

const upcomingRace1 = {
  id: 'upcoming-1',
  title: 'Bali Marathon 2099',
  race_date: '2099-12-01',
  distance_m: 42195,
  location: 'Bali, Indonesia',
  notes: 'Target sub-4h',
  linked_activity_id: null,
  finish_time_sec: null,
  position_place: null,
  position_male: null,
  created_at: '2099-01-01T00:00:00Z',
}

const upcomingRace2 = {
  id: 'upcoming-2',
  title: 'Jakarta 10K 2099',
  race_date: '2099-06-15',
  distance_m: 10000,
  location: null,
  notes: null,
  linked_activity_id: null,
  finish_time_sec: null,
  position_place: null,
  position_male: null,
  created_at: '2099-01-02T00:00:00Z',
}

// Race with a linked activity — unlocks "Save as completed" button
const linkedRace = {
  id: 'upcoming-linked',
  title: 'Linked Activity Race',
  race_date: '2099-09-20',
  distance_m: 21097.5,
  location: null,
  notes: null,
  linked_activity_id: 'strava-act-linked',
  finish_time_sec: null,
  position_place: null,
  position_male: null,
  created_at: '2099-01-03T00:00:00Z',
}

// Stub the rt_users check (onboarding gate)
const stubRtUsers = () => {
  cy.intercept('GET', '**/rest/v1/rt_users*', {
    statusCode: 200,
    body: [{ id: 'test-user-id', onboarding_complete: true }],
  }).as('rtUsersCheck')
}

// Stub the race-log (completed races) list so the list section renders minimally
const stubRaceLog = (entries = []) => {
  cy.intercept('GET', `${RACE_LOG_EP}*`, {
    statusCode: 200,
    body: { data: entries, message: 'ok' },
  }).as('getRaceLog')
}

// Stub the upcoming races list
const stubUpcoming = (races = [], statusCode = 200) => {
  cy.intercept('GET', `${UPCOMING_EP}*`, {
    statusCode,
    body: statusCode === 200 ? { data: races, message: 'OK' } : { error: 'Server error' },
  }).as('getUpcoming')
}

const visitPage = () => {
  cy.viewport(1280, 720)
  cy.visit(RACE_LOG_URL)
}

// ─────────────────────────────────────────────────────────────────────────────
// Auth guard
// ─────────────────────────────────────────────────────────────────────────────

describe('Upcoming Races — Auth guard', () => {
  it('unauthenticated visit redirects to /login', () => {
    cy.clearAllCookies()
    cy.clearAllLocalStorage()
    cy.visit(RACE_LOG_URL, { failOnStatusCode: false })
    cy.url().should('include', '/login')
  })
})

// ─────────────────────────────────────────────────────────────────────────────
// Section renders on page
// ─────────────────────────────────────────────────────────────────────────────

describe('Upcoming Races — Section renders', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubRaceLog([])
    stubUpcoming([upcomingRace1])
    visitPage()
    cy.wait('@getUpcoming')
  })

  it('renders the Upcoming Races section with a heading', () => {
    cy.get(`[id="${IDS.section}"]`).should('exist')
    cy.get(`[id="${IDS.section}"]`).should('contain.text', 'Upcoming Races')
  })

  it('renders the "Add upcoming race" button inside the section header', () => {
    cy.get(`[id="${IDS.add_btn}"]`).should('be.visible')
  })

  it('"Add upcoming race" button has sufficient touch target height (≥ 32px)', () => {
    cy.get(`[id="${IDS.add_btn}"]`)
      .invoke('outerHeight')
      .then((h) => expect(Math.ceil(h)).to.be.gte(32))
  })
})

// ─────────────────────────────────────────────────────────────────────────────
// Empty state
// ─────────────────────────────────────────────────────────────────────────────

describe('Upcoming Races — Empty state', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubRaceLog([])
    stubUpcoming([])
    visitPage()
    cy.wait('@getUpcoming')
  })

  it('renders empty state when no upcoming races exist', () => {
    cy.get(`[id="${IDS.empty_state}"]`).should('be.visible')
  })

  it('shows "No upcoming races" message', () => {
    cy.get(`[id="${IDS.empty_state}"]`).should('contain.text', 'No upcoming races')
  })

  it('has an "Add upcoming race" CTA button inside the empty state', () => {
    cy.get(`[id="${IDS.empty_state}"]`).within(() => {
      cy.contains('button', 'Add upcoming race').should('be.visible')
    })
  })

  it('does not render any race cards', () => {
    // Card IDs are dynamic: upcomingRaceCard_{id}_raceLogPage
    cy.get('[id^="upcomingRaceCard_"]').should('not.exist')
  })
})

// ─────────────────────────────────────────────────────────────────────────────
// Error state
// ─────────────────────────────────────────────────────────────────────────────

describe('Upcoming Races — Error state', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubRaceLog([])
    stubUpcoming([], 500)
    visitPage()
    cy.wait('@getUpcoming')
  })

  it('shows a "Try again" button when the fetch fails', () => {
    cy.get(`[id="${IDS.section}"]`).within(() => {
      cy.contains('button', 'Try again').should('be.visible')
    })
  })

  it('retry button triggers a new fetch and renders the section successfully', () => {
    stubUpcoming([upcomingRace1])
    cy.get(`[id="${IDS.section}"]`).within(() => {
      cy.contains('button', 'Try again').click()
    })
    cy.wait('@getUpcoming')
    cy.get('[id^="upcomingRaceCard_"]').should('exist')
  })
})

// ─────────────────────────────────────────────────────────────────────────────
// Race cards — render correctly
// ─────────────────────────────────────────────────────────────────────────────

describe('Upcoming Races — Card renders correctly', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubRaceLog([])
    stubUpcoming([upcomingRace1, upcomingRace2])
    visitPage()
    cy.wait('@getUpcoming')
  })

  it('renders a card for each upcoming race', () => {
    cy.get('[id^="upcomingRaceCard_"]').should('have.length', 2)
  })

  it('shows the race title on each card', () => {
    cy.contains('Bali Marathon 2099').should('be.visible')
    cy.contains('Jakarta 10K 2099').should('be.visible')
  })

  it('shows the location when provided', () => {
    cy.contains('Bali, Indonesia').should('be.visible')
  })

  it('shows the countdown badge for each card', () => {
    // Both races are far in the future — badge shows "X days"
    cy.get('[id^="upcomingRaceCard_"]')
      .first()
      .within(() => {
        cy.get('span')
          .contains(/days|Race week!/i)
          .should('be.visible')
      })
  })

  it('shows the info guide (amber alert) when no activity is linked', () => {
    // Both stub races have linked_activity_id: null
    cy.get(`[id="${IDS.info_guide}"]`).should('exist').and('have.attr', 'role', 'alert')
  })

  it('shows "Link activity" button on unlinked cards', () => {
    cy.get(`[id="${IDS.link_activity_btn}"]`).first().should('be.visible')
  })

  it('shows "Add to Calendar" button on each card', () => {
    cy.get(`[id="${IDS.add_to_calendar_btn}"]`).first().should('be.visible')
  })

  it('does not show "Save as completed" button on unlinked cards', () => {
    cy.get(`[id="${IDS.save_as_completed_btn}"]`).should('not.exist')
  })

  it('shows "Save as completed" button only on a linked card', () => {
    // Re-stub with a linked race only
    stubUpcoming([linkedRace])
    // Reload — use cy.visit to get fresh state
    cy.visit(RACE_LOG_URL)
    cy.wait('@getUpcoming')
    cy.get(`[id="${IDS.save_as_completed_btn}"]`).should('be.visible')
  })
})

// ─────────────────────────────────────────────────────────────────────────────
// Add modal (open / close)
// ─────────────────────────────────────────────────────────────────────────────

describe('Upcoming Races — Add modal open/close', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubRaceLog([])
    stubUpcoming([])
    visitPage()
    cy.wait('@getUpcoming')
  })

  it('add modal is not visible on initial load', () => {
    cy.get(`[id="${IDS.form_modal}"]`).should('not.exist')
  })

  it('opens the add modal when "Add upcoming race" header button is clicked', () => {
    cy.get(`[id="${IDS.add_btn}"]`).click()
    cy.get(`[id="${IDS.form_modal}"]`).should('be.visible')
    cy.contains('Add Upcoming Race').should('be.visible')
  })

  it('opens the add modal when CTA button inside empty state is clicked', () => {
    cy.get(`[id="${IDS.empty_state}"]`).within(() => {
      cy.contains('button', 'Add upcoming race').click()
    })
    cy.get(`[id="${IDS.form_modal}"]`).should('be.visible')
  })

  it('closes the modal when Cancel is clicked', () => {
    cy.get(`[id="${IDS.add_btn}"]`).click()
    cy.get(`[id="${IDS.form_modal}"]`).should('be.visible')
    cy.get(`[id="${IDS.form_modal}"]`).within(() => {
      cy.contains('button', 'Cancel').click()
    })
    cy.get(`[id="${IDS.form_modal}"]`).should('not.exist')
  })
})

// ─────────────────────────────────────────────────────────────────────────────
// Add modal — form validation
// ─────────────────────────────────────────────────────────────────────────────

describe('Upcoming Races — Add modal form validation', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubRaceLog([])
    stubUpcoming([])
    visitPage()
    cy.wait('@getUpcoming')
    cy.get(`[id="${IDS.add_btn}"]`).click()
    cy.get(`[id="${IDS.form_modal}"]`).should('be.visible')
  })

  it('shows validation errors when submitting an empty form', () => {
    cy.get(`[id="${IDS.save_btn}"]`).click()
    cy.get(`[id="${IDS.form_modal}"]`).within(() => {
      cy.get('[role="alert"]').should('exist')
    })
  })

  it('shows an error for an empty title field', () => {
    cy.get(`[id="${IDS.save_btn}"]`).click()
    cy.get('#upcomingRaceTitleError').should('be.visible')
  })
})

// ─────────────────────────────────────────────────────────────────────────────
// Add modal — successful save
// ─────────────────────────────────────────────────────────────────────────────

describe('Upcoming Races — Add modal successful save', () => {
  const newRace = {
    id: 'new-upcoming-id',
    title: 'New Test Race',
    race_date: '2099-12-31',
    distance_m: 10000,
    location: null,
    notes: null,
    linked_activity_id: null,
    finish_time_sec: null,
    position_place: null,
    position_male: null,
    created_at: '2099-01-01T00:00:00Z',
  }

  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubRaceLog([])
    stubUpcoming([])
    visitPage()
    cy.wait('@getUpcoming')

    cy.intercept('POST', UPCOMING_EP, {
      statusCode: 201,
      body: { data: newRace, message: 'Upcoming race created' },
    }).as('createUpcoming')
  })

  it('closes modal and adds card to the section after successful save', () => {
    cy.get(`[id="${IDS.add_btn}"]`).click()
    cy.get(`[id="${IDS.form_modal}"]`).should('be.visible')

    // Fill required fields
    cy.get('#upcomingRaceTitle').type('New Test Race')

    // Pick a date via the calendar popover
    cy.get('#upcomingRaceDate').click()
    cy.get('[role="gridcell"] button:not([disabled])').last().click()

    // Select a distance preset
    cy.get(`[id="${IDS.form_modal}"]`).within(() => {
      cy.get('[role="combobox"]').first().click()
    })
    cy.get('[role="option"]').contains('10K').click()

    cy.get(`[id="${IDS.save_btn}"]`).click()
    cy.wait('@createUpcoming')

    // Modal closes on success
    cy.get(`[id="${IDS.form_modal}"]`).should('not.exist')
    // The new card should appear in the section
    cy.contains('New Test Race').should('be.visible')
  })

  it('shows server error message when POST returns 500', () => {
    cy.intercept('POST', UPCOMING_EP, {
      statusCode: 500,
      body: { error: 'Internal server error' },
    }).as('createUpcomingFail')

    cy.get(`[id="${IDS.add_btn}"]`).click()
    cy.get('#upcomingRaceTitle').type('Will Fail Race')

    cy.get('#upcomingRaceDate').click()
    cy.get('[role="gridcell"] button:not([disabled])').last().click()

    cy.get(`[id="${IDS.form_modal}"]`).within(() => {
      cy.get('[role="combobox"]').first().click()
    })
    cy.get('[role="option"]').contains('5K').click()

    cy.get(`[id="${IDS.save_btn}"]`).click()
    cy.wait('@createUpcomingFail')

    // Modal stays open on error
    cy.get(`[id="${IDS.form_modal}"]`).should('be.visible')
    cy.get(`[id="${IDS.form_modal}"]`).within(() => {
      cy.get('[role="alert"]').should('exist')
    })
  })
})

// ─────────────────────────────────────────────────────────────────────────────
// Edit modal (per-card)
// ─────────────────────────────────────────────────────────────────────────────

describe('Upcoming Races — Edit modal', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubRaceLog([])
    stubUpcoming([upcomingRace1])
    visitPage()
    cy.wait('@getUpcoming')
  })

  it('edit modal is not visible on initial load', () => {
    // Edit modal shares the same form modal ID
    cy.get(`[id="${IDS.form_modal}"]`).should('not.exist')
  })

  it('opens the edit modal with pre-filled title when pencil icon is clicked', () => {
    cy.get('[id^="upcomingRaceCard_"]')
      .first()
      .within(() => {
        cy.get('[aria-label="Edit upcoming race"]').click()
      })
    cy.get(`[id="${IDS.form_modal}"]`).should('be.visible')
    cy.contains('Edit Upcoming Race').should('be.visible')
    cy.get('#upcomingRaceTitle').should('have.value', upcomingRace1.title)
  })

  it('updates card in list and closes modal after successful PATCH', () => {
    const updatedRace = { ...upcomingRace1, title: 'Bali Marathon 2099 Updated' }
    cy.intercept('PATCH', `${UPCOMING_EP}/${upcomingRace1.id}`, {
      statusCode: 200,
      body: { data: updatedRace, message: 'Upcoming race updated' },
    }).as('patchUpcoming')

    cy.get('[id^="upcomingRaceCard_"]')
      .first()
      .within(() => {
        cy.get('[aria-label="Edit upcoming race"]').click()
      })
    cy.get(`[id="${IDS.form_modal}"]`).should('be.visible')
    cy.get('#upcomingRaceTitle').clear().type('Bali Marathon 2099 Updated')
    cy.get(`[id="${IDS.save_btn}"]`).click()
    cy.wait('@patchUpcoming')

    // Modal closes
    cy.get(`[id="${IDS.form_modal}"]`).should('not.exist')
  })

  it('shows server error inside edit modal when PATCH fails', () => {
    cy.intercept('PATCH', `${UPCOMING_EP}/${upcomingRace1.id}`, {
      statusCode: 500,
      body: { error: 'Internal server error' },
    }).as('patchFail')

    cy.get('[id^="upcomingRaceCard_"]')
      .first()
      .within(() => {
        cy.get('[aria-label="Edit upcoming race"]').click()
      })
    cy.get(`[id="${IDS.form_modal}"]`).should('be.visible')
    cy.get('#upcomingRaceTitle').clear().type('Will Fail')
    cy.get(`[id="${IDS.save_btn}"]`).click()
    cy.wait('@patchFail')

    // Modal stays open on error
    cy.get(`[id="${IDS.form_modal}"]`).should('be.visible')
    cy.get(`[id="${IDS.form_modal}"]`).within(() => {
      cy.get('[role="alert"]').should('exist')
    })
  })
})

// ─────────────────────────────────────────────────────────────────────────────
// Delete confirmation dialog (per-card)
// ─────────────────────────────────────────────────────────────────────────────

describe('Upcoming Races — Delete confirmation dialog', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubRaceLog([])
    stubUpcoming([upcomingRace1])
    visitPage()
    cy.wait('@getUpcoming')
  })

  it('opens the delete confirmation dialog when trash icon is clicked', () => {
    cy.get(`[id="${IDS.delete_btn}"]`).first().click()
    cy.contains('Delete upcoming race?').should('be.visible')
  })

  it('shows the race title in the confirmation dialog', () => {
    cy.get(`[id="${IDS.delete_btn}"]`).first().click()
    cy.get('[role="dialog"]').should('be.visible').and('contain.text', upcomingRace1.title)
  })

  it('closes the dialog without deleting when Cancel is clicked', () => {
    cy.get(`[id="${IDS.delete_btn}"]`).first().click()
    cy.contains('Delete upcoming race?').should('be.visible')
    cy.contains('button', 'Cancel').click()
    cy.contains('Delete upcoming race?').should('not.exist')
    // Card is still present
    cy.get('[id^="upcomingRaceCard_"]').should('have.length', 1)
  })

  it('removes the card from the list after confirming delete', () => {
    cy.intercept('DELETE', `${UPCOMING_EP}/${upcomingRace1.id}`, {
      statusCode: 200,
      body: { message: 'Deleted' },
    }).as('deleteUpcoming')

    cy.get(`[id="${IDS.delete_btn}"]`).first().click()
    cy.get(`[id="${IDS.delete_confirm_btn}"]`).click()
    cy.wait('@deleteUpcoming')

    // Card is removed and empty state appears
    cy.get('[id^="upcomingRaceCard_"]').should('not.exist')
    cy.get(`[id="${IDS.empty_state}"]`).should('be.visible')
  })
})

// ─────────────────────────────────────────────────────────────────────────────
// Mobile responsive (375px)
// ─────────────────────────────────────────────────────────────────────────────

describe('Upcoming Races — Mobile responsive (375px)', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubRaceLog([])
    stubUpcoming([upcomingRace1])
    cy.viewport(375, 812)
    cy.visit(RACE_LOG_URL)
    cy.wait('@getUpcoming')
  })

  it('renders the section without horizontal overflow', () => {
    cy.get('body').then(($body) => {
      expect($body[0].scrollWidth).to.be.lte($body[0].clientWidth + 5)
    })
  })

  it('"Add upcoming race" button is visible on mobile', () => {
    cy.get(`[id="${IDS.add_btn}"]`).should('be.visible')
  })

  it('upcoming race card is visible on mobile', () => {
    cy.get('[id^="upcomingRaceCard_"]').should('be.visible')
  })
})
