// Generated by Cypress Author — 2026-08-10
import { resetVo2maxTarget } from '../../../support/db/running/user/userDb.js'

export const userTasks = (supabaseAdmin) => ({
  async resetVo2maxTarget({ userId }) {
    return resetVo2maxTarget(supabaseAdmin, userId)
  },
})
