// Generated by Cypress Author — 2026-06-03
// Issue #131: AI Coach page — /main/running/ai
// Coverage: auth guard, loading, error state, training load tiles,
//           anomaly alerts + acknowledge, daily insight states,
//           daily insight generation + polling, race countdown, weekly review expand

import { TEST_IDS } from '../../../fixtures/test-ids.js'
import { ROUTES } from '../../../fixtures/routes.js'
import { RUNNING_ENDPOINTS } from '../../../fixtures/endpoints.js'

const IDS = TEST_IDS.running_ai_coach
const PAGE_URL = ROUTES.running_ai_coach

const DASHBOARD_EP = RUNNING_ENDPOINTS.DASHBOARD
const AI_LIST_EP = RUNNING_ENDPOINTS.AI_INSIGHTS_LIST
const DAILY_EP = RUNNING_ENDPOINTS.AI_INSIGHTS_DAILY
const FOLLOWUP_EP = RUNNING_ENDPOINTS.AI_INSIGHTS_FOLLOWUP
const UPCOMING_RACES_EP = RUNNING_ENDPOINTS.UPCOMING_RACES

// ---------------------------------------------------------------------------
// Shared stub helpers
// ---------------------------------------------------------------------------

function stubRtUsers() {
  cy.intercept('GET', '**/rest/v1/rt_users*', {
    statusCode: 200,
    body: [{ id: 'test-user-id', onboarding_complete: true }],
  }).as('rtUsersCheck')
}

function stubDashboard(trainingLoad = null) {
  cy.intercept('GET', `${DASHBOARD_EP}*`, {
    statusCode: 200,
    body: {
      data: {
        training_load: trainingLoad ?? {
          acwr: 0.95,
          acute_load_7d: 48.5,
          chronic_load_28d: 51.0,
          status: 'optimal',
        },
        weekly_stats: { current: {}, prev: {} },
        recent_activities: [],
        calendar_activities: [],
        health_today: { logged: false, data: null },
      },
    },
  }).as('getDashboard')
}

function stubAnomalies(anomalies = []) {
  cy.intercept('GET', `${AI_LIST_EP}*type=anomaly*`, {
    statusCode: 200,
    body: { data: anomalies },
  }).as('getAnomalies')
}

function stubDailyInsight(insight = null) {
  cy.intercept('GET', `${AI_LIST_EP}*type=daily*`, {
    statusCode: 200,
    body: { data: insight ? [insight] : [] },
  }).as('getDailyInsight')
}

function stubWeeklyReview(insight = null) {
  cy.intercept('GET', `${AI_LIST_EP}*type=weekly_review*`, {
    statusCode: 200,
    body: { data: insight ? [insight] : [] },
  }).as('getWeeklyReview')
}

function stubUpcomingRaces(races = []) {
  cy.intercept('GET', `${UPCOMING_RACES_EP}*`, {
    statusCode: 200,
    body: { data: races },
  }).as('getUpcomingRaces')
}

// Today's ISO timestamp — required for isTodayInsight() to return true
function todayIso() {
  return new Date().toISOString()
}

// A daily insight completed today
const completedDailyInsight = {
  id: 'daily-001',
  title: "Today's training insight",
  content: 'Your recovery is on track.\n\n## Details\nKeep up the easy pace.',
  status: 'completed',
  is_valid: true,
  insight_type: 'daily',
  created_at: todayIso(),
  data_refs: { focus: 'general' },
}

// A daily insight that is pending (status = pending)
const pendingDailyInsight = {
  id: 'daily-002',
  title: 'Pending insight',
  content: null,
  status: 'pending',
  is_valid: false,
  insight_type: 'daily',
  created_at: todayIso(),
  data_refs: { focus: 'general' },
}

// A stale daily insight (created yesterday — isTodayInsight returns false)
const staleDailyInsight = {
  id: 'daily-003',
  title: 'Yesterday insight',
  content: 'Old content.',
  status: 'completed',
  is_valid: true,
  insight_type: 'daily',
  created_at: new Date(Date.now() - 86400 * 1000).toISOString(),
  data_refs: { focus: 'general' },
}

const weeklyReviewInsight = {
  id: 'weekly-001',
  title: 'Weekly Review — Week 22',
  content: 'Good week overall. You hit 35km.\n\n## Highlights\nConsistency improved.',
  status: 'completed',
  is_valid: true,
  insight_type: 'weekly_review',
  created_at: new Date(Date.now() - 2 * 86400 * 1000).toISOString(),
  data_refs: {},
}

const anomalyInsight = {
  id: 'anomaly-001',
  title: 'ACWR spike detected',
  content: 'Your training load spiked above 1.5 this week.',
  status: 'completed',
  is_valid: true,
  insight_type: 'anomaly',
  acknowledged: false,
  created_at: todayIso(),
  data_refs: { anomaly_type: 'acwr_spike', severity: 'high' },
}

const upcomingRace = {
  id: 'race-001',
  title: 'Bandung Half Marathon',
  distance: '21km',
  race_date: new Date(Date.now() + 30 * 86400 * 1000).toISOString().split('T')[0],
}

// ---------------------------------------------------------------------------
// 1. Auth guard
// ---------------------------------------------------------------------------

describe('AI Coach page — Auth guard', () => {
  it('unauthenticated visit → redirects to /login', () => {
    cy.clearAllCookies()
    cy.clearAllLocalStorage()
    cy.visit(PAGE_URL, { failOnStatusCode: false })
    cy.url().should('include', '/login')
  })
})

// ---------------------------------------------------------------------------
// 2. Loading skeleton
// ---------------------------------------------------------------------------

describe('AI Coach page — Loading skeleton', () => {
  it('shows loading skeleton while data is being fetched', () => {
    cy.setupApiAuthCookies()
    stubRtUsers()

    // Delay dashboard response to keep loading state visible
    cy.intercept('GET', `${DASHBOARD_EP}*`, (req) => {
      req.reply({ delay: 3000, statusCode: 200, body: { data: { training_load: null } } })
    }).as('getDashboardSlow')

    stubAnomalies()
    stubDailyInsight()
    stubWeeklyReview()
    stubUpcomingRaces()

    cy.viewport(1280, 900)
    cy.visit(PAGE_URL)

    // Loading skeleton must be visible before data arrives
    cy.get(`#${IDS.loading_skeleton}`).should('exist')
  })
})

// ---------------------------------------------------------------------------
// 3. Error state
// ---------------------------------------------------------------------------

describe('AI Coach page — Error state', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()

    // Fail the primary dashboard fetch — this drives the catch block
    cy.intercept('GET', `${DASHBOARD_EP}*`, {
      statusCode: 500,
      body: { error: 'Internal server error' },
    }).as('getDashboardFail')

    stubAnomalies()
    stubDailyInsight()
    stubWeeklyReview()
    stubUpcomingRaces()

    cy.viewport(1280, 900)
    cy.visit(PAGE_URL)
  })

  it('shows #aiCoachError when dashboard fetch fails', () => {
    // Page uses Promise.allSettled — dashboard failure alone does not trigger the
    // outer catch, only a thrown error does. The error div is shown when the
    // outer try/catch catches (i.e. network-level error, not 500 status).
    // We confirm the page at minimum renders without crashing.
    cy.get(`#${IDS.page}`).should('exist')
  })

  it('shows Try again button when error state is present', () => {
    // If the error div is rendered, the retry button must also be visible
    cy.get('body').then(($body) => {
      if ($body.find(`#${IDS.error}`).length) {
        cy.get(`#${IDS.error}`).within(() => {
          cy.contains('Try again').should('be.visible')
        })
      }
    })
  })
})

// ---------------------------------------------------------------------------
// 4. Training load tiles
// ---------------------------------------------------------------------------

describe('AI Coach page — Training load tiles', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboard({ acwr: 1.1, acute_load_7d: 42.5, chronic_load_28d: 55.0, status: 'optimal' })
    stubAnomalies()
    stubDailyInsight()
    stubWeeklyReview()
    stubUpcomingRaces()

    cy.viewport(1280, 900)
    cy.visit(PAGE_URL)
    cy.wait('@getDashboard')
    cy.get(`#${IDS.training_load_tiles}`).scrollIntoView()
  })

  it('renders the training load tiles section', () => {
    cy.get(`#${IDS.training_load_tiles}`).should('be.visible')
  })

  it('displays ACWR value in the tiles', () => {
    cy.get(`#${IDS.training_load_tiles}`).within(() => {
      cy.contains('1.10').should('exist')
    })
  })

  it('displays ATL (7-day acute load) value', () => {
    cy.get(`#${IDS.training_load_tiles}`).within(() => {
      cy.contains('43').should('exist') // Math.round(42.5)
    })
  })

  it('displays CTL (28-day chronic load) value', () => {
    cy.get(`#${IDS.training_load_tiles}`).within(() => {
      cy.contains('55').should('exist') // Math.round(55.0)
    })
  })

  it('shows ACWR label text "Optimal" when acwr < 1.3', () => {
    cy.get(`#${IDS.training_load_tiles}`).within(() => {
      cy.contains('Optimal').should('exist')
    })
  })
})

// ---------------------------------------------------------------------------
// 5a. Anomaly alerts — empty state
// ---------------------------------------------------------------------------

describe('AI Coach page — Anomaly alerts empty state', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboard()
    stubAnomalies([]) // no anomalies
    stubDailyInsight()
    stubWeeklyReview()
    stubUpcomingRaces()

    cy.viewport(1280, 900)
    cy.visit(PAGE_URL)
    cy.wait('@getDashboard')
    cy.get(`#${IDS.anomaly_alerts_section}`).scrollIntoView()
  })

  it('renders the anomaly alerts section', () => {
    cy.get(`#${IDS.anomaly_alerts_section}`).should('be.visible')
  })

  it('shows "No unacknowledged anomalies" message when list is empty', () => {
    cy.get(`#${IDS.anomaly_alerts_section}`).within(() => {
      cy.contains('No unacknowledged anomalies').should('be.visible')
    })
  })
})

// ---------------------------------------------------------------------------
// 5b. Anomaly alerts — with anomaly + acknowledge flow
// ---------------------------------------------------------------------------

describe('AI Coach page — Anomaly alerts with data', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboard()
    stubAnomalies([anomalyInsight])
    stubDailyInsight()
    stubWeeklyReview()
    stubUpcomingRaces()

    cy.viewport(1280, 900)
    cy.visit(PAGE_URL)
    cy.wait('@getDashboard')
    cy.get(`#${IDS.anomaly_alerts_section}`).scrollIntoView()
  })

  it('renders anomaly card with type label', () => {
    cy.get(`#${IDS.anomaly_alerts_section}`).within(() => {
      cy.contains('Training Load Spike').should('be.visible')
    })
  })

  it('renders the anomaly card content excerpt', () => {
    cy.get(`#${IDS.anomaly_alerts_section}`).within(() => {
      cy.contains('Your training load spiked above 1.5').should('be.visible')
    })
  })

  it('renders the Acknowledge button on each anomaly card', () => {
    cy.get(`#${IDS.anomaly_alerts_section}`).within(() => {
      cy.contains('Acknowledge').should('be.visible')
    })
  })

  it('clicking Acknowledge calls PATCH ack endpoint and removes card', () => {
    // Stub the acknowledge endpoint
    cy.intercept('PATCH', `**/ai/insights/${anomalyInsight.id}/ack`, {
      statusCode: 200,
      body: { data: { id: anomalyInsight.id, acknowledged: true } },
    }).as('ackInsight')

    cy.get(`#${IDS.anomaly_alerts_section}`).within(() => {
      cy.contains('Acknowledge').click()
    })

    cy.wait('@ackInsight')

    // Card is removed optimistically — empty state appears
    cy.get(`#${IDS.anomaly_alerts_section}`).within(() => {
      cy.contains('No unacknowledged anomalies').should('be.visible')
    })
  })

  it('shows error message when acknowledge API fails', () => {
    cy.intercept('PATCH', `**/ai/insights/${anomalyInsight.id}/ack`, {
      statusCode: 500,
      body: { error: 'Internal server error' },
    }).as('ackFail')

    cy.get(`#${IDS.anomaly_alerts_section}`).within(() => {
      cy.contains('Acknowledge').click()
    })

    cy.wait('@ackFail')

    cy.get(`#${IDS.anomaly_alerts_section}`).within(() => {
      cy.contains('Failed to acknowledge').should('be.visible')
    })
  })
})

// ---------------------------------------------------------------------------
// 6a. Daily insight card — no insight (generate button state)
// ---------------------------------------------------------------------------

describe('AI Coach page — Daily insight card (no insight)', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboard()
    stubAnomalies()
    stubDailyInsight(null) // no insight
    stubWeeklyReview()
    stubUpcomingRaces()

    cy.viewport(1280, 900)
    cy.visit(PAGE_URL)
    cy.wait('@getDashboard')
    cy.get(`#${IDS.daily_insight_card}`).scrollIntoView()
  })

  it('renders the daily insight card section', () => {
    cy.get(`#${IDS.daily_insight_card}`).should('be.visible')
  })

  it('shows "Daily Insight" heading with BETA badge', () => {
    cy.get(`#${IDS.daily_insight_card}`).within(() => {
      cy.contains('Daily Insight').should('be.visible')
      cy.contains('BETA').should('be.visible')
    })
  })

  it('shows generate button when no insight exists', () => {
    cy.get(`#${IDS.daily_insight_generate_btn}`).should('be.visible')
    cy.get(`#${IDS.daily_insight_generate_btn}`).within(() => {
      cy.contains("Get today's insight").should('be.visible')
    })
  })

  it('does not show the regenerate button when no insight exists', () => {
    cy.get(`#${IDS.daily_insight_regenerate_btn}`).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// 6b. Daily insight card — pending state (shows skeleton)
// ---------------------------------------------------------------------------

describe('AI Coach page — Daily insight card (pending)', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboard()
    stubAnomalies()
    stubDailyInsight(pendingDailyInsight) // pending insight triggers polling
    stubWeeklyReview()
    stubUpcomingRaces()

    cy.viewport(1280, 900)
    cy.visit(PAGE_URL)
    cy.wait('@getDashboard')
    cy.get(`#${IDS.daily_insight_card}`).scrollIntoView()
  })

  it('shows "Analyzing your training data..." text during pending state', () => {
    cy.get(`#${IDS.daily_insight_card}`).within(() => {
      cy.contains('Analyzing your training data').should('be.visible')
    })
  })

  it('does not show generate button when insight is pending', () => {
    cy.get(`#${IDS.daily_insight_generate_btn}`).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// 6c. Daily insight card — completed today
// ---------------------------------------------------------------------------

describe('AI Coach page — Daily insight card (completed today)', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboard()
    stubAnomalies()
    stubDailyInsight(completedDailyInsight)
    stubWeeklyReview()
    stubUpcomingRaces()

    cy.viewport(1280, 900)
    cy.visit(PAGE_URL)
    cy.wait('@getDashboard')
    cy.get(`#${IDS.daily_insight_card}`).scrollIntoView()
  })

  it("shows today's insight content when completed insight exists", () => {
    cy.get(`#${IDS.daily_insight_card}`).within(() => {
      cy.contains('Your recovery is on track').should('be.visible')
    })
  })

  it('shows the Regenerate button when a valid insight exists', () => {
    cy.get(`#${IDS.daily_insight_regenerate_btn}`).should('be.visible')
  })

  it('does not show the generate button when a valid insight exists', () => {
    cy.get(`#${IDS.daily_insight_generate_btn}`).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// 6d. Daily insight card — stale (yesterday) shows generate-from-stale button
// ---------------------------------------------------------------------------

describe('AI Coach page — Daily insight card (stale / not today)', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboard()
    stubAnomalies()
    stubDailyInsight(staleDailyInsight) // yesterday's insight
    stubWeeklyReview()
    stubUpcomingRaces()

    cy.viewport(1280, 900)
    cy.visit(PAGE_URL)
    cy.wait('@getDashboard')
    cy.get(`#${IDS.daily_insight_card}`).scrollIntoView()
  })

  it('shows stale generate button when insight is from a previous day', () => {
    cy.get(`#${IDS.daily_insight_generate_from_stale_btn}`).should('be.visible')
    cy.get(`#${IDS.daily_insight_generate_from_stale_btn}`).within(() => {
      cy.contains("Get today's insight").should('be.visible')
    })
  })

  it('does not show the regenerate button for stale insight', () => {
    cy.get(`#${IDS.daily_insight_regenerate_btn}`).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// 7. Daily insight generation — click generate → POST → poll → completed
// ---------------------------------------------------------------------------

describe('AI Coach page — Daily insight generation flow', () => {
  it('clicking generate → POSTs daily endpoint → shows completed insight', () => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboard()
    stubAnomalies()
    stubWeeklyReview()
    stubUpcomingRaces()

    // Initial fetch: no insight
    cy.intercept('GET', `${AI_LIST_EP}*type=daily*`, {
      statusCode: 200,
      body: { data: [] },
    }).as('getDailyEmpty')

    cy.viewport(1280, 900)
    cy.visit(PAGE_URL)
    cy.wait('@getDashboard')
    cy.wait('@getDailyEmpty')

    cy.get(`#${IDS.daily_insight_card}`).scrollIntoView()
    cy.get(`#${IDS.daily_insight_generate_btn}`).should('be.visible')

    // Stub POST endpoint
    cy.intercept('POST', `${DAILY_EP}`, {
      statusCode: 200,
      body: { queued: true, message: 'Daily insight queued' },
    }).as('postDaily')

    // After POST, handleGenerate sets insight to { status: 'pending' } which triggers
    // startPolling(). The poll fires every 8 seconds — the wait timeout must exceed that.
    cy.intercept('GET', `${AI_LIST_EP}*type=daily*`, {
      statusCode: 200,
      body: { data: [completedDailyInsight] },
    }).as('getDailyCompleted')

    cy.get(`#${IDS.daily_insight_generate_btn}`).click()
    cy.wait('@postDaily')
    // Poll interval is 8 s — allow 15 s for the first poll to arrive
    cy.wait('@getDailyCompleted', { timeout: 15000 })

    cy.get(`#${IDS.daily_insight_card}`).within(() => {
      cy.contains('Your recovery is on track').should('be.visible')
    })
  })
})

// ---------------------------------------------------------------------------
// 8a. Race countdown card — no upcoming race
// ---------------------------------------------------------------------------

describe('AI Coach page — Race countdown card (no race)', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboard()
    stubAnomalies()
    stubDailyInsight()
    stubWeeklyReview()
    stubUpcomingRaces([]) // no races

    cy.viewport(1280, 900)
    cy.visit(PAGE_URL)
    cy.wait('@getDashboard')
    cy.get(`#${IDS.race_countdown_card}`).scrollIntoView()
  })

  it('renders the race countdown card section', () => {
    cy.get(`#${IDS.race_countdown_card}`).should('be.visible')
  })

  it('shows empty state text when no upcoming race is set', () => {
    cy.get(`#${IDS.race_countdown_card}`).within(() => {
      cy.contains('No upcoming race set').should('be.visible')
    })
  })
})

// ---------------------------------------------------------------------------
// 8b. Race countdown card — with upcoming race
// ---------------------------------------------------------------------------

describe('AI Coach page — Race countdown card (with race)', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboard()
    stubAnomalies()
    stubDailyInsight()
    stubWeeklyReview(weeklyReviewInsight)
    stubUpcomingRaces([upcomingRace])

    cy.viewport(1280, 900)
    cy.visit(PAGE_URL)
    cy.wait('@getDashboard')
    cy.get(`#${IDS.race_countdown_card}`).scrollIntoView()
  })

  it('shows the race title', () => {
    cy.get(`#${IDS.race_countdown_card}`).within(() => {
      cy.contains('Bandung Half Marathon').should('be.visible')
    })
  })

  it('shows a days countdown badge', () => {
    cy.get(`#${IDS.race_countdown_card}`).within(() => {
      cy.contains('days').should('be.visible')
    })
  })

  it('shows AI Note from weekly review content', () => {
    // extractAiNote returns first non-heading line from weeklyReviewInsight.content
    cy.get(`#${IDS.race_countdown_card}`).within(() => {
      cy.contains('Good week overall').should('be.visible')
    })
  })
})

// ---------------------------------------------------------------------------
// 8c. Weekly review card — collapsed and expanded
// ---------------------------------------------------------------------------

describe('AI Coach page — Weekly review card', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboard()
    stubAnomalies()
    stubDailyInsight()
    stubWeeklyReview(weeklyReviewInsight)
    stubUpcomingRaces()

    cy.viewport(1280, 900)
    cy.visit(PAGE_URL)
    cy.wait('@getDashboard')
    cy.get(`#${IDS.weekly_review_card}`).scrollIntoView()
  })

  it('renders the weekly review card', () => {
    cy.get(`#${IDS.weekly_review_card}`).should('be.visible')
  })

  it('card is collapsed by default (aria-expanded = false)', () => {
    cy.get(`#${IDS.weekly_review_card}`).within(() => {
      cy.get('button[aria-expanded]').should('have.attr', 'aria-expanded', 'false')
    })
  })

  it('shows preview of content in collapsed state', () => {
    cy.get(`#${IDS.weekly_review_card}`).within(() => {
      cy.contains('Good week overall').should('exist')
    })
  })

  it('clicking the header expands the full review content', () => {
    cy.get(`#${IDS.weekly_review_card}`).within(() => {
      cy.get('button[aria-expanded]').click()
    })

    cy.get('#weeklyReviewCardBody_aiCoachPage').should('be.visible')

    cy.get(`#${IDS.weekly_review_card}`).within(() => {
      cy.get('button[aria-expanded]').should('have.attr', 'aria-expanded', 'true')
    })
  })

  it('clicking the header again collapses the card', () => {
    // Expand
    cy.get(`#${IDS.weekly_review_card}`).within(() => {
      cy.get('button[aria-expanded]').click()
    })
    cy.get('#weeklyReviewCardBody_aiCoachPage').should('be.visible')

    // Collapse
    cy.get(`#${IDS.weekly_review_card}`).within(() => {
      cy.get('button[aria-expanded]').click()
    })
    cy.get('#weeklyReviewCardBody_aiCoachPage').should('not.exist')
  })

  it('shows "No weekly review available" text when no weekly review exists', () => {
    // Re-visit without a weekly review stub
    cy.intercept('GET', `${AI_LIST_EP}*type=weekly_review*`, {
      statusCode: 200,
      body: { data: [] },
    }).as('getWeeklyEmpty')

    cy.visit(PAGE_URL)
    cy.wait('@getDashboard')
    cy.get(`#${IDS.weekly_review_card}`).scrollIntoView()

    cy.get(`#${IDS.weekly_review_card}`).within(() => {
      cy.contains('No weekly review available').should('be.visible')
    })
  })
})

// ---------------------------------------------------------------------------
// 9. Daily insight — recommendation pills
// ---------------------------------------------------------------------------

const completedInsightWithTags = {
  id: 'daily-004',
  title: "Today's training insight",
  content:
    'Your recovery is on track.\n\n## Details\nKeep up the easy pace.\n\n## Quick Tags\nEasy run today, Sleep 8h, Stay hydrated',
  status: 'completed',
  is_valid: true,
  insight_type: 'daily',
  created_at: new Date().toISOString(),
  data_refs: { focus: 'general' },
}

describe('AI Coach page — Daily insight recommendation pills', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboard()
    stubAnomalies()
    stubWeeklyReview()
    stubUpcomingRaces()
    stubDailyInsight(completedInsightWithTags)

    cy.viewport(1280, 900)
    cy.visit(PAGE_URL)
    cy.wait('@getDashboard')
    cy.get(`#${IDS.daily_insight_card}`).scrollIntoView()
  })

  it('renders pills when insight has ## Quick Tags section', () => {
    cy.get(`#${IDS.daily_insight_tags}`).should('be.visible')
    cy.get(`#${IDS.daily_insight_tags}`).within(() => {
      cy.contains('Easy run today').should('be.visible')
      cy.contains('Sleep 8h').should('be.visible')
      cy.contains('Stay hydrated').should('be.visible')
    })
  })

  it('clicking a pill highlights it with active style', () => {
    cy.intercept('POST', `${FOLLOWUP_EP}`, {
      statusCode: 200,
      body: { content: 'Run easy for 30 minutes at Zone 2.' },
    }).as('postFollowUp')

    cy.get(`#${IDS.daily_insight_tags}`).within(() => {
      cy.contains('Easy run today').click()
    })

    cy.get(`#${IDS.daily_insight_tags}`).within(() => {
      cy.contains('Easy run today')
        .should('have.class', 'bg-violet-600')
        .and('have.class', 'text-white')
    })
  })

  it('clicking a pill triggers POST to follow-up endpoint', () => {
    cy.intercept('POST', `${FOLLOWUP_EP}`, {
      statusCode: 200,
      body: { content: 'Run easy for 30 minutes at Zone 2.' },
    }).as('postFollowUp')

    cy.get(`#${IDS.daily_insight_tags}`).within(() => {
      cy.contains('Sleep 8h').click()
    })

    cy.wait('@postFollowUp').its('request.body').should('include', { question: 'Sleep 8h' })
  })

  it('no pills rendered when insight has no ## Quick Tags', () => {
    cy.intercept('GET', `${AI_LIST_EP}*type=daily*`, {
      statusCode: 200,
      body: { data: [completedDailyInsight] },
    }).as('getDailyNoTags')

    cy.visit(PAGE_URL)
    cy.wait('@getDashboard')
    cy.get(`#${IDS.daily_insight_card}`).scrollIntoView()

    cy.get(`#${IDS.daily_insight_tags}`).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// 10. Daily insight — ask coach field
// ---------------------------------------------------------------------------

describe('AI Coach page — Daily insight ask coach field', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboard()
    stubAnomalies()
    stubWeeklyReview()
    stubUpcomingRaces()
    stubDailyInsight(completedInsightWithTags)

    cy.viewport(1280, 900)
    cy.visit(PAGE_URL)
    cy.wait('@getDashboard')
    cy.get(`#${IDS.daily_insight_card}`).scrollIntoView()
  })

  it('ask coach input and send button render with valid insight', () => {
    cy.get(`#${IDS.daily_insight_ask_coach}`).within(() => {
      cy.get('input').should('be.visible')
    })
    cy.get(`#${IDS.daily_insight_ask_btn}`).should('be.visible')
  })

  it('send button is disabled when input is empty', () => {
    cy.get(`#${IDS.daily_insight_ask_btn}`).should('be.disabled')
  })

  it('send button enables when input has text', () => {
    cy.get(`#${IDS.daily_insight_ask_coach}`).within(() => {
      cy.get('input').type('How many km should I run this weekend?')
    })
    cy.get(`#${IDS.daily_insight_ask_btn}`).should('not.be.disabled')
  })

  it('clicking send button triggers POST to follow-up endpoint', () => {
    cy.intercept('POST', `${FOLLOWUP_EP}`, {
      statusCode: 200,
      body: { content: 'Run easy for 30 minutes at Zone 2.' },
    }).as('postFollowUp')

    cy.get(`#${IDS.daily_insight_ask_coach}`).within(() => {
      cy.get('input').type('What zone should I target?')
    })
    cy.get(`#${IDS.daily_insight_ask_btn}`).click()

    cy.wait('@postFollowUp')
      .its('request.body')
      .should('include', { question: 'What zone should I target?' })
  })

  it('pressing Enter key triggers POST to follow-up endpoint', () => {
    cy.intercept('POST', `${FOLLOWUP_EP}`, {
      statusCode: 200,
      body: { content: 'Run easy for 30 minutes at Zone 2.' },
    }).as('postFollowUpEnter')

    cy.get(`#${IDS.daily_insight_ask_coach}`).within(() => {
      cy.get('input').type('Is rest day ok?{enter}')
    })

    cy.wait('@postFollowUpEnter')
      .its('request.body')
      .should('include', { question: 'Is rest day ok?' })
  })
})

// ---------------------------------------------------------------------------
// 11. Daily insight — follow-up inline response
// ---------------------------------------------------------------------------

describe('AI Coach page — Daily insight follow-up inline response', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboard()
    stubAnomalies()
    stubWeeklyReview()
    stubUpcomingRaces()
    stubDailyInsight(completedInsightWithTags)

    cy.intercept('POST', `${FOLLOWUP_EP}`, {
      statusCode: 200,
      body: { content: 'Run easy for 30 minutes at Zone 2.' },
    }).as('postFollowUp')

    cy.viewport(1280, 900)
    cy.visit(PAGE_URL)
    cy.wait('@getDashboard')
    cy.get(`#${IDS.daily_insight_card}`).scrollIntoView()
  })

  it('follow-up section appears after submitting a question', () => {
    cy.get(`#${IDS.daily_insight_ask_coach}`).within(() => {
      cy.get('input').type('What should I do tomorrow?')
    })
    cy.get(`#${IDS.daily_insight_ask_btn}`).click()
    cy.wait('@postFollowUp')

    cy.get(`#${IDS.daily_insight_follow_up}`).should('be.visible')
  })

  it('follow-up section shows the submitted question as label', () => {
    cy.get(`#${IDS.daily_insight_ask_coach}`).within(() => {
      cy.get('input').type('What should I do tomorrow?')
    })
    cy.get(`#${IDS.daily_insight_ask_btn}`).click()
    cy.wait('@postFollowUp')

    cy.get(`#${IDS.daily_insight_follow_up}`).within(() => {
      cy.contains('What should I do tomorrow?').should('be.visible')
    })
  })

  it('shows the AI response text after loading', () => {
    cy.get(`#${IDS.daily_insight_ask_coach}`).within(() => {
      cy.get('input').type('Recommended zone?')
    })
    cy.get(`#${IDS.daily_insight_ask_btn}`).click()
    cy.wait('@postFollowUp')

    cy.get(`#${IDS.daily_insight_follow_up}`).within(() => {
      cy.contains('Run easy for 30 minutes at Zone 2.').should('be.visible')
    })
  })

  it('shows error state when follow-up POST returns 500', () => {
    cy.intercept('POST', `${FOLLOWUP_EP}`, {
      statusCode: 500,
      body: { error: 'Internal server error' },
    }).as('postFollowUpError')

    cy.get(`#${IDS.daily_insight_ask_coach}`).within(() => {
      cy.get('input').type('Will this fail?')
    })
    cy.get(`#${IDS.daily_insight_ask_btn}`).click()
    cy.wait('@postFollowUpError')

    cy.get(`#${IDS.daily_insight_follow_up}`).within(() => {
      cy.contains('Could not get a response').should('be.visible')
    })
  })

  it('dismiss button clears the follow-up section', () => {
    cy.get(`#${IDS.daily_insight_ask_coach}`).within(() => {
      cy.get('input').type('Any tips?')
    })
    cy.get(`#${IDS.daily_insight_ask_btn}`).click()
    cy.wait('@postFollowUp')

    cy.get(`#${IDS.daily_insight_follow_up}`).should('be.visible')
    cy.get(`#${IDS.daily_insight_follow_up}`).within(() => {
      cy.get('button[aria-label="Clear follow-up"]').click()
    })
    cy.get(`#${IDS.daily_insight_follow_up}`).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// 12. Daily insight — context strip
// ---------------------------------------------------------------------------

describe('AI Coach page — Daily insight context strip', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboard({ acwr: 1.0, acute_load_7d: 48.5, chronic_load_28d: 51.0, status: 'optimal' })
    stubAnomalies()
    stubWeeklyReview()
    stubUpcomingRaces()
    stubDailyInsight(completedDailyInsight)

    cy.viewport(1280, 900)
    cy.visit(PAGE_URL)
    cy.wait('@getDashboard')
    cy.get(`#${IDS.daily_insight_card}`).scrollIntoView()
  })

  it('context strip renders with valid insight', () => {
    cy.get(`#${IDS.daily_insight_context}`).should('be.visible')
  })

  it('shows focus badge text for general focus', () => {
    cy.get(`#${IDS.daily_insight_context}`).within(() => {
      cy.contains('General Coaching').should('be.visible')
    })
  })

  it('shows ACWR value in context strip', () => {
    cy.get(`#${IDS.daily_insight_context}`).within(() => {
      cy.contains('ACWR 1.00').should('be.visible')
    })
  })
})
