// Generated by Cypress Author — 2026-06-06
// Fixed: 2026-06-06 — move auth setup into before() per describe block
// Issue #160: Injury Coach API tests — /api/running/v1/ai/injury-coach
// Coverage: POST valid physio, POST valid physician, POST missing question,
//           POST question < 10 chars, POST invalid role, no auth → 401

import { RUNNING_ENDPOINTS } from '../../../fixtures/endpoints.js'

const INJURY_COACH_EP = RUNNING_ENDPOINTS.INJURY_COACH

// ---------------------------------------------------------------------------
// 1. POST valid physio request → 200, response has data.content + escalate
// ---------------------------------------------------------------------------

describe('Injury Coach API — POST valid physio', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  it('POST with role:physio and valid question → 200 with data.content and escalate', () => {
    cy.apiRequestWithSession('POST', INJURY_COACH_EP, {
      body: {
        role: 'physio',
        question: 'What exercises help with knee rehabilitation?',
        body_region: 'left_knee',
        phase: 'subacute',
      },
    }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('data')
      expect(res.body.data).to.have.property('content')
      expect(res.body).to.have.property('escalate')
    })
  })
})

// ---------------------------------------------------------------------------
// 2. POST valid physician request → 200
// ---------------------------------------------------------------------------

describe('Injury Coach API — POST valid physician', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  it('POST with role:physician and valid question → 200', () => {
    cy.apiRequestWithSession('POST', INJURY_COACH_EP, {
      body: {
        role: 'physician',
        question: 'What diagnostic tests should I consider for Achilles tendon pain?',
        body_region: 'right_achilles',
      },
    }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('data')
      expect(res.body.data).to.have.property('content')
    })
  })
})

// ---------------------------------------------------------------------------
// 3. POST missing question → 400
// ---------------------------------------------------------------------------

describe('Injury Coach API — POST missing question', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  it('POST without question field → 400 Bad Request', () => {
    cy.apiRequestWithSession('POST', INJURY_COACH_EP, {
      body: {
        role: 'physio',
        body_region: 'left_knee',
      },
    }).then((res) => {
      expect(res.status).to.eq(400)
    })
  })
})

// ---------------------------------------------------------------------------
// 4. POST question under 10 characters → 400
// ---------------------------------------------------------------------------

describe('Injury Coach API — POST question under 10 chars', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  it('POST with question shorter than 10 chars → 400 Bad Request', () => {
    cy.apiRequestWithSession('POST', INJURY_COACH_EP, {
      body: {
        role: 'physio',
        question: 'Hurts?',
        body_region: 'left_knee',
      },
    }).then((res) => {
      expect(res.status).to.eq(400)
    })
  })
})

// ---------------------------------------------------------------------------
// 5. POST invalid role → 400
// ---------------------------------------------------------------------------

describe('Injury Coach API — POST invalid role', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  it('POST with role:invalid_role → 400 Bad Request', () => {
    cy.apiRequestWithSession('POST', INJURY_COACH_EP, {
      body: {
        role: 'invalid_role',
        question: 'What should I do about my injury recovery plan?',
        body_region: 'lower_back',
      },
    }).then((res) => {
      expect(res.status).to.eq(400)
    })
  })
})

// ---------------------------------------------------------------------------
// 6. No auth → 401
// ---------------------------------------------------------------------------

describe('Injury Coach API — No auth', () => {
  it('POST without authentication → 401 Unauthorized', () => {
    cy.apiRequestNoAuth('POST', INJURY_COACH_EP, {
      body: {
        role: 'physio',
        question: 'What exercises help with knee rehabilitation?',
        body_region: 'left_knee',
      },
    }).then((res) => {
      expect(res.status).to.eq(401)
    })
  })
})
