// Generated by Cypress Author — 2026-06-06
// Fixed: 2026-06-06 — move auth setup into beforeEach per describe block
// Issue #160: Symptom log API tests — /api/running/v1/symptoms
// Coverage: POST valid, POST missing body_region, POST pain_level 11,
//           GET active, PATCH archive, PATCH non-existent UUID

import { RUNNING_ENDPOINTS } from '../../../fixtures/endpoints.js'

const SYMPTOMS_EP = RUNNING_ENDPOINTS.SYMPTOMS
const SYMPTOMS_BY_ID_EP = RUNNING_ENDPOINTS.SYMPTOMS_BY_ID

// Reusable crypto UUID — guaranteed invalid in the DB
const NON_EXISTENT_UUID = '00000000-0000-0000-0000-000000000000'

// ---------------------------------------------------------------------------
// 1. POST valid symptom log → 201
// ---------------------------------------------------------------------------

describe('Symptom Log API — POST valid log', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  it('POST with body_region and pain_level:5 → 201 Created', () => {
    cy.apiRequestWithSession('POST', SYMPTOMS_EP, {
      body: {
        body_region: 'left_knee',
        pain_level: 5,
        description: 'Dull ache after long run',
      },
    }).then((res) => {
      expect(res.status).to.eq(201)
      expect(res.body).to.have.property('data')
      expect(res.body.data).to.have.property('id')
    })
  })
})

// ---------------------------------------------------------------------------
// 2. POST missing body_region → 400
// ---------------------------------------------------------------------------

describe('Symptom Log API — POST missing body_region', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  it('POST without body_region → 400 Bad Request', () => {
    cy.apiRequestWithSession('POST', SYMPTOMS_EP, {
      body: {
        pain_level: 5,
      },
    }).then((res) => {
      expect(res.status).to.eq(400)
    })
  })
})

// ---------------------------------------------------------------------------
// 3. POST pain_level: 11 → 400 (out of valid range 1–10)
// ---------------------------------------------------------------------------

describe('Symptom Log API — POST pain_level out of range', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  it('POST with pain_level:11 → 400 Bad Request', () => {
    cy.apiRequestWithSession('POST', SYMPTOMS_EP, {
      body: {
        body_region: 'right_ankle',
        pain_level: 11,
      },
    }).then((res) => {
      expect(res.status).to.eq(400)
    })
  })
})

// ---------------------------------------------------------------------------
// 4. GET active symptom logs → 200 with array
// ---------------------------------------------------------------------------

describe('Symptom Log API — GET active logs', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  it('GET active symptom logs → 200 with data array', () => {
    cy.apiRequestWithSession('GET', SYMPTOMS_EP).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('data')
      expect(res.body.data).to.be.an('array')
    })
  })
})

// ---------------------------------------------------------------------------
// 5. PATCH archive an existing symptom → 200
//    Creates a fresh symptom in before() so this test is self-contained.
// ---------------------------------------------------------------------------

describe('Symptom Log API — PATCH archive', () => {
  let symptomIdToArchive = null

  before(() => {
    cy.setupApiAuthCookies()
    // Always create a fresh symptom so this test is independent
    cy.apiRequestWithSession('POST', SYMPTOMS_EP, {
      body: {
        body_region: 'lower_back',
        pain_level: 3,
      },
    }).then((res) => {
      if (res.status === 201) {
        symptomIdToArchive = res.body.data.id
      }
    })
  })

  it('PATCH archive existing symptom → 200', function () {
    if (!symptomIdToArchive) {
      this.skip()
    }

    cy.apiRequestWithSession('PATCH', SYMPTOMS_BY_ID_EP(symptomIdToArchive), {
      body: { archived: true },
    }).then((res) => {
      expect(res.status).to.eq(200)
    })
  })
})

// ---------------------------------------------------------------------------
// 6. PATCH non-existent UUID → 404
// ---------------------------------------------------------------------------

describe('Symptom Log API — PATCH non-existent UUID', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  it('PATCH non-existent symptom UUID → 404', () => {
    cy.apiRequestWithSession('PATCH', SYMPTOMS_BY_ID_EP(NON_EXISTENT_UUID), {
      body: { archived: true },
    }).then((res) => {
      expect(res.status).to.eq(404)
    })
  })
})
