// Generated by Cypress Author — 2026-08-11
// Investment Flow API tests for issue #751
// Endpoints:
//   GET    /api/investment-flow/v1          — list nodes (flat adjacency list)
//   POST   /api/investment-flow/v1          — create node
//   PUT    /api/investment-flow/v1          — update node (id in body)
//   DELETE /api/investment-flow/v1?id=:uuid — delete node + subtree
//   PUT    /api/investment-flow/v1/move     — move node to new parent

const makeCategoryPayload = (overrides = {}) => ({
  node_type: 'category',
  name: 'Saham IDX',
  ...overrides,
})

const makeTickerPayload = (overrides = {}) => ({
  node_type: 'ticker',
  name: 'BBCA',
  nominal: 50000000,
  notes: 'Long term hold',
  ...overrides,
})

// ─── GET /api/investment-flow/v1 ─────────────────────────────────────────────

describe('Investment Flow API — GET /api/investment-flow/v1', () => {
  before(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 with valid session', () => {
    cy.listInvestmentFlowNodes().then((res) => {
      expect(res.status).to.eq(200)
    })
  })

  it('returns 401 when unauthenticated', () => {
    cy.clearCookies()
    cy.listInvestmentFlowNodesNoAuth().then((res) => {
      expect(res.status).to.be.oneOf([401, 307])
    })
  })

  it('returns success: true and data array', () => {
    cy.setupApiAuthCookies()
    cy.listInvestmentFlowNodes().then((res) => {
      expect(res.body).to.have.property('success', true)
      expect(res.body).to.have.property('data').that.is.an('array')
    })
  })

  it('returns expected node fields when list is non-empty', () => {
    cy.setupApiAuthCookies()
    cy.listInvestmentFlowNodes().then((res) => {
      if (res.body.data.length === 0) {
        cy.log('Tree is empty — skipping field shape check')
        return
      }
      const node = res.body.data[0]
      expect(node).to.have.property('id')
      expect(node).to.have.property('parent_id')
      expect(node).to.have.property('node_type').that.is.oneOf(['category', 'ticker'])
      expect(node).to.have.property('name').that.is.a('string')
      expect(node).to.have.property('sort_order').that.is.a('number')
      expect(node).to.have.property('created_at')
      expect(node).to.have.property('updated_at')
    })
  })
})

// ─── POST /api/investment-flow/v1 ────────────────────────────────────────────

describe('Investment Flow API — POST /api/investment-flow/v1 (create)', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 201 when creating a valid category node at root level', () => {
    cy.createInvestmentFlowNode(makeCategoryPayload()).then((res) => {
      expect(res.status).to.eq(201)
      expect(res.body).to.have.property('success', true)
      const node = res.body.data
      expect(node).to.have.property('node_type', 'category')
      expect(node).to.have.property('nominal', null)
      expect(node).to.have.property('notes', null)
      expect(node).to.have.property('parent_id', null)
    })
  })

  it('returns 201 when creating a ticker node under a category (manual nominal)', () => {
    // Category (autosum) parent, ticker child holds the manual nominal
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'Saham US' })).then((catRes) => {
      expect(catRes.status).to.eq(201)
      const parentId = catRes.body.data.id

      cy.createInvestmentFlowNode(makeTickerPayload({ parent_id: parentId })).then((res) => {
        expect(res.status).to.eq(201)
        const node = res.body.data
        expect(node).to.have.property('node_type', 'ticker')
        expect(node).to.have.property('nominal', 50000000)
        expect(node).to.have.property('parent_id', parentId)
      })
    })
  })

  it('returns 201 when creating a category node (autosum) under another category', () => {
    // node_type: 'category' means value is derived from children sum, not manual nominal
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'Portfolio Root' })).then((rootRes) => {
      expect(rootRes.status).to.eq(201)
      const parentId = rootRes.body.data.id

      cy.createInvestmentFlowNode(
        makeCategoryPayload({ name: 'Saham IDX (autosum)', parent_id: parentId })
      ).then((res) => {
        expect(res.status).to.eq(201)
        const node = res.body.data
        expect(node).to.have.property('node_type', 'category')
        expect(node).to.have.property('nominal', null)
        expect(node).to.have.property('parent_id', parentId)
      })
    })
  })

  it('returns 201 when creating a nested ticker under a ticker (leaf with children)', () => {
    // Parent ticker's own nominal is superseded once it gains a child —
    // createNode.js clears parent.nominal/notes in this case.
    cy.createInvestmentFlowNode(makeTickerPayload({ name: 'Parent Ticker' })).then((parentRes) => {
      expect(parentRes.status).to.eq(201)
      const parentId = parentRes.body.data.id

      cy.createInvestmentFlowNode(
        makeTickerPayload({ name: 'Child Ticker', parent_id: parentId })
      ).then((res) => {
        expect(res.status).to.eq(201)
        expect(res.body.data).to.have.property('parent_id', parentId)

        cy.listInvestmentFlowNodes().then((listRes) => {
          const parentNode = listRes.body.data.find((n) => n.id === parentId)
          expect(parentNode).to.have.property('nominal', null)
        })
      })
    })
  })

  it('returns 401 when unauthenticated', () => {
    cy.clearCookies()
    cy.createInvestmentFlowNodeNoAuth(makeCategoryPayload()).then((res) => {
      expect(res.status).to.be.oneOf([401, 307])
    })
  })

  it('returns 400 when name is missing', () => {
    const payload = makeCategoryPayload()
    delete payload.name
    cy.createInvestmentFlowNode(payload).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when node_type is missing', () => {
    const payload = makeCategoryPayload()
    delete payload.node_type
    cy.createInvestmentFlowNode(payload).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when node_type is invalid', () => {
    cy.createInvestmentFlowNode({ ...makeCategoryPayload(), node_type: 'stock' }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when ticker node is missing nominal', () => {
    const payload = makeTickerPayload()
    delete payload.nominal
    cy.createInvestmentFlowNode(payload).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when ticker nominal is negative or zero', () => {
    cy.createInvestmentFlowNode(makeTickerPayload({ nominal: -1 })).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when category node has nominal (cross-field violation)', () => {
    cy.createInvestmentFlowNode(makeCategoryPayload({ nominal: 100000 })).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when category node has notes (cross-field violation)', () => {
    cy.createInvestmentFlowNode(makeCategoryPayload({ notes: 'should not be here' })).then(
      (res) => {
        expect(res.status).to.eq(400)
        expect(res.body).to.have.property('error')
      }
    )
  })

  it('returns 400 when parent_id is a non-existent uuid', () => {
    cy.createInvestmentFlowNode(
      makeCategoryPayload({ parent_id: '00000000-0000-0000-0000-000000000000' })
    ).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('accepts optional notes field on ticker node', () => {
    cy.createInvestmentFlowNode(makeTickerPayload({ notes: 'dividend play' })).then((res) => {
      expect(res.status).to.eq(201)
      expect(res.body.data).to.have.property('notes', 'dividend play')
    })
  })

  it('returns 400 when notes exceed 500 characters', () => {
    cy.createInvestmentFlowNode(makeTickerPayload({ notes: 'a'.repeat(501) })).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  // NOTE: createNode.js enforces MAX_NODES_PER_USER = 500 (NODE_LIMIT_EXCEEDED -> 422).
  // cy.request() bypasses the browser network layer, so cy.intercept() cannot stub
  // this response, and seeding 500 real rows per run is too slow/expensive for CI.
  // This edge case is covered by Backend unit/integration tests instead — see
  // lib/services/investmentFlow/createNode.js and errorMessages.js.
})

// ─── PUT /api/investment-flow/v1 (update) ────────────────────────────────────

describe('Investment Flow API — PUT /api/investment-flow/v1 (update)', () => {
  let categoryId

  before(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
    cy.setupApiAuthCookies()
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'Update Test Category' })).then(
      (res) => {
        expect(res.status).to.eq(201)
        categoryId = res.body.data.id
      }
    )
  })

  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 when updating a category node name', () => {
    cy.updateInvestmentFlowNode({ id: categoryId, name: 'Updated Category Name' }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('success', true)
      expect(res.body.data).to.have.property('name', 'Updated Category Name')
    })
  })

  it('returns 200 and clears nominal/notes when converting ticker -> category', () => {
    cy.createInvestmentFlowNode(
      makeTickerPayload({ name: 'To Be Category', nominal: 15000000, notes: 'will be cleared' })
    ).then((createRes) => {
      expect(createRes.status).to.eq(201)
      const tickerId = createRes.body.data.id

      cy.updateInvestmentFlowNode({ id: tickerId, node_type: 'category' }).then((res) => {
        expect(res.status).to.eq(200)
        expect(res.body.data).to.have.property('node_type', 'category')
        expect(res.body.data).to.have.property('nominal', null)
        expect(res.body.data).to.have.property('notes', null)
      })
    })
  })

  it('returns 200 when converting category -> ticker with a nominal', () => {
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'To Be Ticker' })).then((createRes) => {
      expect(createRes.status).to.eq(201)
      const catId = createRes.body.data.id

      cy.updateInvestmentFlowNode({
        id: catId,
        node_type: 'ticker',
        nominal: 7500000,
      }).then((res) => {
        expect(res.status).to.eq(200)
        expect(res.body.data).to.have.property('node_type', 'ticker')
        expect(res.body.data).to.have.property('nominal', 7500000)
      })
    })
  })

  it('returns 401 when unauthenticated', () => {
    cy.clearCookies()
    cy.updateInvestmentFlowNodeNoAuth({ id: categoryId, name: 'Hacked' }).then((res) => {
      expect(res.status).to.be.oneOf([401, 307])
    })
  })

  it('returns 404 for non-existent node id', () => {
    cy.updateInvestmentFlowNode({
      id: '00000000-0000-0000-0000-000000000000',
      name: 'Ghost',
    }).then((res) => {
      expect(res.status).to.eq(404)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when id is missing', () => {
    cy.updateInvestmentFlowNode({ name: 'No ID' }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when trying to set nominal on a category node', () => {
    cy.updateInvestmentFlowNode({ id: categoryId, nominal: 999999 }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 200 when updating ticker node nominal and notes', () => {
    cy.createInvestmentFlowNode(makeTickerPayload({ name: 'TLKM', nominal: 10000000 })).then(
      (createRes) => {
        expect(createRes.status).to.eq(201)
        const tickerId = createRes.body.data.id

        cy.updateInvestmentFlowNode({ id: tickerId, nominal: 20000000, notes: 'updated' }).then(
          (res) => {
            expect(res.status).to.eq(200)
            expect(res.body.data).to.have.property('nominal', 20000000)
            expect(res.body.data).to.have.property('notes', 'updated')
          }
        )
      }
    )
  })
})

// ─── DELETE /api/investment-flow/v1?id=:uuid ─────────────────────────────────

describe('Investment Flow API — DELETE /api/investment-flow/v1?id=:uuid', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 204 with empty body on valid delete of a leaf node', () => {
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'To Delete' })).then((createRes) => {
      expect(createRes.status).to.eq(201)
      const idToDelete = createRes.body.data.id

      cy.deleteInvestmentFlowNode(idToDelete).then((res) => {
        expect(res.status).to.eq(204)
        expect(res.body).to.be.oneOf(['', null, undefined])
      })
    })
  })

  it('returns 204 when deleting a node with children (cascade)', () => {
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'Parent To Cascade' })).then(
      (catRes) => {
        expect(catRes.status).to.eq(201)
        const parentId = catRes.body.data.id

        cy.createInvestmentFlowNode(makeTickerPayload({ parent_id: parentId })).then((tickRes) => {
          expect(tickRes.status).to.eq(201)
          const childId = tickRes.body.data.id

          cy.deleteInvestmentFlowNode(parentId).then((delRes) => {
            expect(delRes.status).to.eq(204)

            // Child was cascade-deleted too — deleting it again is a 404
            cy.deleteInvestmentFlowNode(childId).then((childDelRes) => {
              expect(childDelRes.status).to.eq(404)
            })
          })
        })
      }
    )
  })

  it('returns 401 when unauthenticated', () => {
    cy.clearCookies()
    cy.deleteInvestmentFlowNodeNoAuth('00000000-0000-0000-0000-000000000001').then((res) => {
      expect(res.status).to.be.oneOf([401, 307])
    })
  })

  it('returns 404 for non-existent node id', () => {
    cy.deleteInvestmentFlowNode('00000000-0000-0000-0000-000000000000').then((res) => {
      expect(res.status).to.eq(404)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 404 when deleting an already-deleted node (idempotency)', () => {
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'Double Delete' })).then(
      (createRes) => {
        expect(createRes.status).to.eq(201)
        const id = createRes.body.data.id

        cy.deleteInvestmentFlowNode(id).then((firstRes) => {
          expect(firstRes.status).to.eq(204)

          cy.deleteInvestmentFlowNode(id).then((secondRes) => {
            expect(secondRes.status).to.eq(404)
          })
        })
      }
    )
  })
})

// ─── PUT /api/investment-flow/v1/move ────────────────────────────────────────

describe('Investment Flow API — PUT /api/investment-flow/v1/move', () => {
  let catA
  let catB
  let childCat

  before(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
    cy.setupApiAuthCookies()

    // catA and catB are root-level categories; childCat is nested under catA
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'Move Test Cat A' })).then((res) => {
      expect(res.status).to.eq(201)
      catA = res.body.data.id
    })

    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'Move Test Cat B' })).then((res) => {
      expect(res.status).to.eq(201)
      catB = res.body.data.id
    })
  })

  beforeEach(() => {
    cy.setupApiAuthCookies()
    // Create a fresh childCat under catA before each test so tests are independent
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'Child Cat', parent_id: catA })).then(
      (res) => {
        expect(res.status).to.eq(201)
        childCat = res.body.data.id
      }
    )
  })

  it('returns 200 when moving a node to a new parent', () => {
    cy.moveInvestmentFlowNode({ id: childCat, new_parent_id: catB }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('success', true)
      expect(res.body.data).to.have.property('parent_id', catB)
    })
  })

  it('returns 200 when moving a node to root (new_parent_id null)', () => {
    cy.moveInvestmentFlowNode({ id: childCat, new_parent_id: null }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body.data).to.have.property('parent_id', null)
    })
  })

  it('returns 401 when unauthenticated', () => {
    cy.clearCookies()
    cy.moveInvestmentFlowNodeNoAuth({ id: childCat, new_parent_id: catB }).then((res) => {
      expect(res.status).to.be.oneOf([401, 307])
    })
  })

  it('returns 404 for non-existent node id', () => {
    cy.moveInvestmentFlowNode({
      id: '00000000-0000-0000-0000-000000000000',
      new_parent_id: catB,
    }).then((res) => {
      expect(res.status).to.eq(404)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when new_parent_id is a non-existent uuid', () => {
    cy.moveInvestmentFlowNode({
      id: childCat,
      new_parent_id: '00000000-0000-0000-0000-000000000000',
    }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 409 when moving a node into its own subtree (cycle prevention)', () => {
    // Create a grandchild under childCat, then try to move childCat under grandchild
    cy.createInvestmentFlowNode(
      makeCategoryPayload({ name: 'Grandchild Cat', parent_id: childCat })
    ).then((grandchildRes) => {
      expect(grandchildRes.status).to.eq(201)
      const grandchildId = grandchildRes.body.data.id

      cy.moveInvestmentFlowNode({ id: childCat, new_parent_id: grandchildId }).then((res) => {
        expect(res.status).to.eq(409)
        expect(res.body).to.have.property('error')
      })
    })
  })

  it('returns 409 when self-moving (id === new_parent_id)', () => {
    cy.moveInvestmentFlowNode({ id: childCat, new_parent_id: childCat }).then((res) => {
      expect(res.status).to.eq(409)
      expect(res.body).to.have.property('error')
    })
  })
})
