// Generated by Cypress Author — 2026-08-11
// Investment Flow API tests for issue #751
// Extended for issue #771 — uninvested cash node
// Extended for issue #776 — uninvested cash categories
// Extended for issue #781 — node highlights (color map)
// Endpoints:
//   GET    /api/investment-flow/v1                              — list nodes (flat adjacency list)
//   POST   /api/investment-flow/v1                              — create node
//   PUT    /api/investment-flow/v1                              — update node (id in body)
//   DELETE /api/investment-flow/v1?id=:uuid                     — delete node + subtree
//   PUT    /api/investment-flow/v1/move                         — move node to new parent
//   GET    /api/investment-flow/v1/uninvested-cash              — get uninvested cash amount
//   PATCH  /api/investment-flow/v1/uninvested-cash              — set uninvested cash amount
//   GET    /api/investment-flow/v1/uninvested-cash/categories   — list cash categories
//   POST   /api/investment-flow/v1/uninvested-cash/categories   — create cash category
//   PUT    /api/investment-flow/v1/uninvested-cash/categories/:id   — update cash category
//   DELETE /api/investment-flow/v1/uninvested-cash/categories/:id   — delete cash category
//   GET    /api/investment-flow/v1/highlights                   — get node highlight color map
//   PATCH  /api/investment-flow/v1/highlights                   — set node highlight color map

const makeCategoryPayload = (overrides = {}) => ({
  node_type: 'category',
  name: 'Saham IDX',
  ...overrides,
})

const makeTickerPayload = (overrides = {}) => ({
  node_type: 'ticker',
  name: 'BBCA',
  nominal: 50000000,
  notes: 'Long term hold',
  ...overrides,
})

// ─── GET /api/investment-flow/v1 ─────────────────────────────────────────────

describe('Investment Flow API — GET /api/investment-flow/v1', () => {
  before(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 with valid session', () => {
    cy.listInvestmentFlowNodes().then((res) => {
      expect(res.status).to.eq(200)
    })
  })

  it('returns 401 when unauthenticated', () => {
    cy.clearCookies()
    cy.listInvestmentFlowNodesNoAuth().then((res) => {
      expect(res.status).to.be.oneOf([401, 307])
    })
  })

  it('returns success: true and data.nodes array', () => {
    cy.setupApiAuthCookies()
    cy.listInvestmentFlowNodes().then((res) => {
      expect(res.body).to.have.property('success', true)
      expect(res.body.data).to.have.property('nodes').that.is.an('array')
    })
  })

  it('returns expected node fields when list is non-empty', () => {
    cy.setupApiAuthCookies()
    cy.listInvestmentFlowNodes().then((res) => {
      if (res.body.data.nodes.length === 0) {
        cy.log('Tree is empty — skipping field shape check')
        return
      }
      const node = res.body.data.nodes[0]
      expect(node).to.have.property('id')
      expect(node).to.have.property('parent_id')
      expect(node).to.have.property('node_type').that.is.oneOf(['category', 'ticker'])
      expect(node).to.have.property('name').that.is.a('string')
      expect(node).to.have.property('sort_order').that.is.a('number')
      expect(node).to.have.property('created_at')
      expect(node).to.have.property('updated_at')
    })
  })

  it('returns uninvestedCash as a number alongside the node list', () => {
    cy.listInvestmentFlowNodes().then((res) => {
      expect(res.body.data).to.have.property('uninvestedCash').that.is.a('number')
    })
  })

  it('returns cashCategories as an array alongside the node list (issue #776)', () => {
    cy.listInvestmentFlowNodes().then((res) => {
      expect(res.body.data).to.have.property('cashCategories').that.is.an('array')
    })
  })

  it('returns highlights as an object alongside the node list (issue #781)', () => {
    cy.listInvestmentFlowNodes().then((res) => {
      expect(res.body.data).to.have.property('highlights').that.is.an('object')
    })
  })

  it('reflects a PATCHed highlight color in data.highlights (issue #781)', () => {
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'Highlight Sync Category' })).then(
      (createRes) => {
        expect(createRes.status).to.eq(201)
        const nodeId = createRes.body.data.id

        cy.patchInvestmentFlowHighlights({ highlights: { [nodeId]: '#3B82F6' } }).then(
          (patchRes) => {
            expect(patchRes.status).to.eq(200)

            cy.listInvestmentFlowNodes().then((listRes) => {
              expect(listRes.body.data.highlights).to.have.property(nodeId, '#3B82F6')
            })
          }
        )
      }
    )
  })
})

// ─── POST /api/investment-flow/v1 ────────────────────────────────────────────

describe('Investment Flow API — POST /api/investment-flow/v1 (create)', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 201 when creating a valid category node at root level', () => {
    cy.createInvestmentFlowNode(makeCategoryPayload()).then((res) => {
      expect(res.status).to.eq(201)
      expect(res.body).to.have.property('success', true)
      const node = res.body.data
      expect(node).to.have.property('node_type', 'category')
      expect(node).to.have.property('nominal', null)
      expect(node).to.have.property('notes', null)
      expect(node).to.have.property('parent_id', null)
    })
  })

  it('returns 201 when creating a ticker node under a category (manual nominal)', () => {
    // Category (autosum) parent, ticker child holds the manual nominal
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'Saham US' })).then((catRes) => {
      expect(catRes.status).to.eq(201)
      const parentId = catRes.body.data.id

      cy.createInvestmentFlowNode(makeTickerPayload({ parent_id: parentId })).then((res) => {
        expect(res.status).to.eq(201)
        const node = res.body.data
        expect(node).to.have.property('node_type', 'ticker')
        expect(node).to.have.property('nominal', 50000000)
        expect(node).to.have.property('parent_id', parentId)
      })
    })
  })

  it('returns 201 when creating a category node (autosum) under another category', () => {
    // node_type: 'category' means value is derived from children sum, not manual nominal
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'Portfolio Root' })).then((rootRes) => {
      expect(rootRes.status).to.eq(201)
      const parentId = rootRes.body.data.id

      cy.createInvestmentFlowNode(
        makeCategoryPayload({ name: 'Saham IDX (autosum)', parent_id: parentId })
      ).then((res) => {
        expect(res.status).to.eq(201)
        const node = res.body.data
        expect(node).to.have.property('node_type', 'category')
        expect(node).to.have.property('nominal', null)
        expect(node).to.have.property('parent_id', parentId)
      })
    })
  })

  it('returns 201 when creating a nested ticker under a ticker (leaf with children)', () => {
    // Parent ticker's own nominal is superseded once it gains a child —
    // createNode.js clears parent.nominal/notes in this case.
    cy.createInvestmentFlowNode(makeTickerPayload({ name: 'Parent Ticker' })).then((parentRes) => {
      expect(parentRes.status).to.eq(201)
      const parentId = parentRes.body.data.id

      cy.createInvestmentFlowNode(
        makeTickerPayload({ name: 'Child Ticker', parent_id: parentId })
      ).then((res) => {
        expect(res.status).to.eq(201)
        expect(res.body.data).to.have.property('parent_id', parentId)

        cy.listInvestmentFlowNodes().then((listRes) => {
          const parentNode = listRes.body.data.nodes.find((n) => n.id === parentId)
          expect(parentNode).to.have.property('nominal', null)
        })
      })
    })
  })

  it('returns 401 when unauthenticated', () => {
    cy.clearCookies()
    cy.createInvestmentFlowNodeNoAuth(makeCategoryPayload()).then((res) => {
      expect(res.status).to.be.oneOf([401, 307])
    })
  })

  it('returns 400 when name is missing', () => {
    const payload = makeCategoryPayload()
    delete payload.name
    cy.createInvestmentFlowNode(payload).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when node_type is missing', () => {
    const payload = makeCategoryPayload()
    delete payload.node_type
    cy.createInvestmentFlowNode(payload).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when node_type is invalid', () => {
    cy.createInvestmentFlowNode({ ...makeCategoryPayload(), node_type: 'stock' }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when ticker node is missing nominal', () => {
    const payload = makeTickerPayload()
    delete payload.nominal
    cy.createInvestmentFlowNode(payload).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when ticker nominal is negative or zero', () => {
    cy.createInvestmentFlowNode(makeTickerPayload({ nominal: -1 })).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when category node has nominal (cross-field violation)', () => {
    cy.createInvestmentFlowNode(makeCategoryPayload({ nominal: 100000 })).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when category node has notes (cross-field violation)', () => {
    cy.createInvestmentFlowNode(makeCategoryPayload({ notes: 'should not be here' })).then(
      (res) => {
        expect(res.status).to.eq(400)
        expect(res.body).to.have.property('error')
      }
    )
  })

  it('returns 400 when parent_id is a non-existent uuid', () => {
    cy.createInvestmentFlowNode(
      makeCategoryPayload({ parent_id: '00000000-0000-0000-0000-000000000000' })
    ).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('accepts optional notes field on ticker node', () => {
    cy.createInvestmentFlowNode(makeTickerPayload({ notes: 'dividend play' })).then((res) => {
      expect(res.status).to.eq(201)
      expect(res.body.data).to.have.property('notes', 'dividend play')
    })
  })

  it('returns 400 when notes exceed 500 characters', () => {
    cy.createInvestmentFlowNode(makeTickerPayload({ notes: 'a'.repeat(501) })).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  // NOTE: createNode.js enforces MAX_NODES_PER_USER = 500 (NODE_LIMIT_EXCEEDED -> 422).
  // cy.request() bypasses the browser network layer, so cy.intercept() cannot stub
  // this response, and seeding 500 real rows per run is too slow/expensive for CI.
  // This edge case is covered by Backend unit/integration tests instead — see
  // lib/services/investmentFlow/createNode.js and errorMessages.js.

  it('returns 422 with code INSUFFICIENT_CASH when node nominal exceeds cash category balance (issue #776)', () => {
    cy.createUninvestedCashCategory({ name: 'Small Pool', nominal: 100000 }).then((catRes) => {
      expect(catRes.status).to.eq(201)
      const categoryId = catRes.body.data.category.id

      cy.createInvestmentFlowNode(
        makeTickerPayload({
          name: 'Overdrawn Ticker',
          nominal: 999999999,
          uninvested_cash_category_id: categoryId,
        })
      ).then((res) => {
        expect(res.status).to.eq(422)
        expect(res.body).to.have.property('success', false)
        expect(res.body).to.have.property('code', 'INSUFFICIENT_CASH')
      })
    })
  })
})

// ─── PUT /api/investment-flow/v1 (update) ────────────────────────────────────

describe('Investment Flow API — PUT /api/investment-flow/v1 (update)', () => {
  let categoryId

  before(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
    cy.setupApiAuthCookies()
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'Update Test Category' })).then(
      (res) => {
        expect(res.status).to.eq(201)
        categoryId = res.body.data.id
      }
    )
  })

  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 when updating a category node name', () => {
    cy.updateInvestmentFlowNode({ id: categoryId, name: 'Updated Category Name' }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('success', true)
      expect(res.body.data).to.have.property('name', 'Updated Category Name')
    })
  })

  it('returns 200 and clears nominal/notes when converting ticker -> category', () => {
    cy.createInvestmentFlowNode(
      makeTickerPayload({ name: 'To Be Category', nominal: 15000000, notes: 'will be cleared' })
    ).then((createRes) => {
      expect(createRes.status).to.eq(201)
      const tickerId = createRes.body.data.id

      cy.updateInvestmentFlowNode({ id: tickerId, node_type: 'category' }).then((res) => {
        expect(res.status).to.eq(200)
        expect(res.body.data).to.have.property('node_type', 'category')
        expect(res.body.data).to.have.property('nominal', null)
        expect(res.body.data).to.have.property('notes', null)
      })
    })
  })

  it('returns 200 when converting category -> ticker with a nominal', () => {
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'To Be Ticker' })).then((createRes) => {
      expect(createRes.status).to.eq(201)
      const catId = createRes.body.data.id

      cy.updateInvestmentFlowNode({
        id: catId,
        node_type: 'ticker',
        nominal: 7500000,
      }).then((res) => {
        expect(res.status).to.eq(200)
        expect(res.body.data).to.have.property('node_type', 'ticker')
        expect(res.body.data).to.have.property('nominal', 7500000)
      })
    })
  })

  it('returns 401 when unauthenticated', () => {
    cy.clearCookies()
    cy.updateInvestmentFlowNodeNoAuth({ id: categoryId, name: 'Hacked' }).then((res) => {
      expect(res.status).to.be.oneOf([401, 307])
    })
  })

  it('returns 404 for non-existent node id', () => {
    cy.updateInvestmentFlowNode({
      id: '00000000-0000-0000-0000-000000000000',
      name: 'Ghost',
    }).then((res) => {
      expect(res.status).to.eq(404)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when id is missing', () => {
    cy.updateInvestmentFlowNode({ name: 'No ID' }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when trying to set nominal on a category node', () => {
    cy.updateInvestmentFlowNode({ id: categoryId, nominal: 999999 }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 200 when updating ticker node nominal and notes', () => {
    cy.createInvestmentFlowNode(makeTickerPayload({ name: 'TLKM', nominal: 10000000 })).then(
      (createRes) => {
        expect(createRes.status).to.eq(201)
        const tickerId = createRes.body.data.id

        cy.updateInvestmentFlowNode({ id: tickerId, nominal: 20000000, notes: 'updated' }).then(
          (res) => {
            expect(res.status).to.eq(200)
            expect(res.body.data).to.have.property('nominal', 20000000)
            expect(res.body.data).to.have.property('notes', 'updated')
          }
        )
      }
    )
  })

  it('returns 422 with code INSUFFICIENT_CASH when updated nominal exceeds cash category balance (issue #776)', () => {
    cy.createUninvestedCashCategory({ name: 'Tiny Pool', nominal: 50000 }).then((catRes) => {
      expect(catRes.status).to.eq(201)
      const categoryId = catRes.body.data.category.id

      cy.createInvestmentFlowNode(
        makeTickerPayload({
          name: 'Pool Linked Ticker',
          nominal: 40000,
          uninvested_cash_category_id: categoryId,
        })
      ).then((createRes) => {
        expect(createRes.status).to.eq(201)
        const tickerId = createRes.body.data.id

        cy.updateInvestmentFlowNode({
          id: tickerId,
          nominal: 999999999,
          uninvested_cash_category_id: categoryId,
        }).then((res) => {
          expect(res.status).to.eq(422)
          expect(res.body).to.have.property('success', false)
          expect(res.body).to.have.property('code', 'INSUFFICIENT_CASH')
        })
      })
    })
  })
})

// ─── DELETE /api/investment-flow/v1?id=:uuid ─────────────────────────────────

describe('Investment Flow API — DELETE /api/investment-flow/v1?id=:uuid', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 204 with empty body on valid delete of a leaf node', () => {
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'To Delete' })).then((createRes) => {
      expect(createRes.status).to.eq(201)
      const idToDelete = createRes.body.data.id

      cy.deleteInvestmentFlowNode(idToDelete).then((res) => {
        expect(res.status).to.eq(204)
        expect(res.body).to.be.oneOf(['', null, undefined])
      })
    })
  })

  it('returns 204 when deleting a node with children (cascade)', () => {
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'Parent To Cascade' })).then(
      (catRes) => {
        expect(catRes.status).to.eq(201)
        const parentId = catRes.body.data.id

        cy.createInvestmentFlowNode(makeTickerPayload({ parent_id: parentId })).then((tickRes) => {
          expect(tickRes.status).to.eq(201)
          const childId = tickRes.body.data.id

          cy.deleteInvestmentFlowNode(parentId).then((delRes) => {
            expect(delRes.status).to.eq(204)

            // Child was cascade-deleted too — deleting it again is a 404
            cy.deleteInvestmentFlowNode(childId).then((childDelRes) => {
              expect(childDelRes.status).to.eq(404)
            })
          })
        })
      }
    )
  })

  it('returns 401 when unauthenticated', () => {
    cy.clearCookies()
    cy.deleteInvestmentFlowNodeNoAuth('00000000-0000-0000-0000-000000000001').then((res) => {
      expect(res.status).to.be.oneOf([401, 307])
    })
  })

  it('returns 404 for non-existent node id', () => {
    cy.deleteInvestmentFlowNode('00000000-0000-0000-0000-000000000000').then((res) => {
      expect(res.status).to.eq(404)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 404 when deleting an already-deleted node (idempotency)', () => {
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'Double Delete' })).then(
      (createRes) => {
        expect(createRes.status).to.eq(201)
        const id = createRes.body.data.id

        cy.deleteInvestmentFlowNode(id).then((firstRes) => {
          expect(firstRes.status).to.eq(204)

          cy.deleteInvestmentFlowNode(id).then((secondRes) => {
            expect(secondRes.status).to.eq(404)
          })
        })
      }
    )
  })
})

// ─── PUT /api/investment-flow/v1/move ────────────────────────────────────────

describe('Investment Flow API — PUT /api/investment-flow/v1/move', () => {
  let catA
  let catB
  let childCat

  before(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
    cy.setupApiAuthCookies()

    // catA and catB are root-level categories; childCat is nested under catA
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'Move Test Cat A' })).then((res) => {
      expect(res.status).to.eq(201)
      catA = res.body.data.id
    })

    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'Move Test Cat B' })).then((res) => {
      expect(res.status).to.eq(201)
      catB = res.body.data.id
    })
  })

  beforeEach(() => {
    cy.setupApiAuthCookies()
    // Create a fresh childCat under catA before each test so tests are independent
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'Child Cat', parent_id: catA })).then(
      (res) => {
        expect(res.status).to.eq(201)
        childCat = res.body.data.id
      }
    )
  })

  it('returns 200 when moving a node to a new parent', () => {
    cy.moveInvestmentFlowNode({ id: childCat, new_parent_id: catB }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('success', true)
      expect(res.body.data).to.have.property('parent_id', catB)
    })
  })

  it('returns 200 when moving a node to root (new_parent_id null)', () => {
    cy.moveInvestmentFlowNode({ id: childCat, new_parent_id: null }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body.data).to.have.property('parent_id', null)
    })
  })

  it('returns 401 when unauthenticated', () => {
    cy.clearCookies()
    cy.moveInvestmentFlowNodeNoAuth({ id: childCat, new_parent_id: catB }).then((res) => {
      expect(res.status).to.be.oneOf([401, 307])
    })
  })

  it('returns 404 for non-existent node id', () => {
    cy.moveInvestmentFlowNode({
      id: '00000000-0000-0000-0000-000000000000',
      new_parent_id: catB,
    }).then((res) => {
      expect(res.status).to.eq(404)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when new_parent_id is a non-existent uuid', () => {
    cy.moveInvestmentFlowNode({
      id: childCat,
      new_parent_id: '00000000-0000-0000-0000-000000000000',
    }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 409 when moving a node into its own subtree (cycle prevention)', () => {
    // Create a grandchild under childCat, then try to move childCat under grandchild
    cy.createInvestmentFlowNode(
      makeCategoryPayload({ name: 'Grandchild Cat', parent_id: childCat })
    ).then((grandchildRes) => {
      expect(grandchildRes.status).to.eq(201)
      const grandchildId = grandchildRes.body.data.id

      cy.moveInvestmentFlowNode({ id: childCat, new_parent_id: grandchildId }).then((res) => {
        expect(res.status).to.eq(409)
        expect(res.body).to.have.property('error')
      })
    })
  })

  it('returns 409 when self-moving (id === new_parent_id)', () => {
    cy.moveInvestmentFlowNode({ id: childCat, new_parent_id: childCat }).then((res) => {
      expect(res.status).to.eq(409)
      expect(res.body).to.have.property('error')
    })
  })
})

// ─── GET/PATCH /api/investment-flow/v1/uninvested-cash ───────────────────────

describe('Investment Flow API — GET /api/investment-flow/v1/uninvested-cash', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 with valid session', () => {
    cy.getUninvestedCash().then((res) => {
      expect(res.status).to.eq(200)
    })
  })

  it('returns 401 when unauthenticated', () => {
    cy.clearCookies()
    cy.getUninvestedCashNoAuth().then((res) => {
      expect(res.status).to.be.oneOf([401, 307])
    })
  })

  it('returns success: true and uninvestedCash as a non-negative number', () => {
    cy.setupApiAuthCookies()
    cy.getUninvestedCash().then((res) => {
      expect(res.body).to.have.property('success', true)
      expect(res.body.data).to.have.property('uninvestedCash').that.is.a('number')
      expect(res.body.data.uninvestedCash).to.be.at.least(0)
    })
  })
})

describe('Investment Flow API — PATCH /api/investment-flow/v1/uninvested-cash', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 and the updated amount when setting a valid value', () => {
    cy.patchUninvestedCash({ amount: 12500000 }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('success', true)
      expect(res.body.data).to.have.property('uninvestedCash', 12500000)
    })
  })

  it('persists the updated value on subsequent GET', () => {
    cy.patchUninvestedCash({ amount: 3000000 }).then(() => {
      cy.getUninvestedCash().then((res) => {
        expect(res.body.data).to.have.property('uninvestedCash', 3000000)
      })
    })
  })

  it('accepts 0 as a valid amount (reset to default)', () => {
    cy.patchUninvestedCash({ amount: 0 }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body.data).to.have.property('uninvestedCash', 0)
    })
  })

  it('returns 401 when unauthenticated', () => {
    cy.clearCookies()
    cy.patchUninvestedCashNoAuth({ amount: 1000000 }).then((res) => {
      expect(res.status).to.be.oneOf([401, 307])
    })
  })

  it('returns 400 when amount is missing', () => {
    cy.patchUninvestedCash({}).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when amount is a string instead of a number', () => {
    cy.patchUninvestedCash({ amount: 'not-a-number' }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 400 when amount is negative', () => {
    cy.patchUninvestedCash({ amount: -500 }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })
})

// ─── GET /api/investment-flow/v1/uninvested-cash/categories ─────────────────

describe('Investment Flow API — GET /api/investment-flow/v1/uninvested-cash/categories', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 with valid session', () => {
    cy.listUninvestedCashCategories().then((res) => {
      expect(res.status).to.eq(200)
    })
  })

  it('returns 401 when unauthenticated', () => {
    cy.clearCookies()
    cy.listUninvestedCashCategoriesNoAuth().then((res) => {
      expect(res.status).to.be.oneOf([401, 307])
    })
  })

  it('returns success: true and data.categories array', () => {
    cy.setupApiAuthCookies()
    cy.listUninvestedCashCategories().then((res) => {
      expect(res.body).to.have.property('success', true)
      expect(res.body.data).to.have.property('categories').that.is.an('array')
    })
  })

  it('returns expected category fields when list is non-empty', () => {
    cy.setupApiAuthCookies()
    cy.createUninvestedCashCategory({ name: 'Shape Check Pool', nominal: 500000 }).then(() => {
      cy.listUninvestedCashCategories().then((res) => {
        const category = res.body.data.categories[0]
        expect(category).to.have.property('id')
        expect(category).to.have.property('name').that.is.a('string')
        expect(category).to.have.property('nominal').that.is.a('number')
        expect(category).to.have.property('sort_order').that.is.a('number')
        expect(category).to.have.property('created_at')
      })
    })
  })
})

// ─── POST /api/investment-flow/v1/uninvested-cash/categories ────────────────

describe('Investment Flow API — POST /api/investment-flow/v1/uninvested-cash/categories', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 201 when creating a valid category', () => {
    cy.createUninvestedCashCategory({ name: 'Emergency Fund', nominal: 5000000 }).then((res) => {
      expect(res.status).to.eq(201)
      expect(res.body).to.have.property('success', true)
      const category = res.body.data.category
      expect(category).to.have.property('id')
      expect(category).to.have.property('name', 'Emergency Fund')
      expect(category).to.have.property('nominal', 5000000)
    })
  })

  it('returns 401 when unauthenticated', () => {
    cy.clearCookies()
    cy.createUninvestedCashCategoryNoAuth({ name: 'Blocked Pool', nominal: 1000000 }).then(
      (res) => {
        expect(res.status).to.be.oneOf([401, 307])
      }
    )
  })

  it('returns 400 when name is missing', () => {
    cy.createUninvestedCashCategory({ nominal: 1000000 }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('success', false)
    })
  })

  it('returns 400 when nominal is missing', () => {
    cy.createUninvestedCashCategory({ name: 'No Nominal Pool' }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('success', false)
    })
  })

  it('returns 400 when nominal is negative', () => {
    cy.createUninvestedCashCategory({ name: 'Negative Pool', nominal: -1000 }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('success', false)
    })
  })
})

// ─── PUT /api/investment-flow/v1/uninvested-cash/categories/:id ─────────────

describe('Investment Flow API — PUT /api/investment-flow/v1/uninvested-cash/categories/:id', () => {
  let categoryId

  before(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
    cy.setupApiAuthCookies()
    cy.createUninvestedCashCategory({ name: 'Update Test Pool', nominal: 2000000 }).then((res) => {
      expect(res.status).to.eq(201)
      categoryId = res.body.data.category.id
    })
  })

  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 when updating name and nominal', () => {
    cy.updateUninvestedCashCategory(categoryId, {
      name: 'Renamed Pool',
      nominal: 3000000,
    }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('success', true)
      expect(res.body.data.category).to.have.property('name', 'Renamed Pool')
      expect(res.body.data.category).to.have.property('nominal', 3000000)
    })
  })

  it('returns 200 when updating only name', () => {
    cy.updateUninvestedCashCategory(categoryId, { name: 'Name Only Update' }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body.data.category).to.have.property('name', 'Name Only Update')
    })
  })

  it('returns 401 when unauthenticated', () => {
    cy.clearCookies()
    cy.updateUninvestedCashCategoryNoAuth(categoryId, { name: 'Hacked Pool' }).then((res) => {
      expect(res.status).to.be.oneOf([401, 307])
    })
  })

  it('returns 400 when id is not a valid uuid', () => {
    cy.updateUninvestedCashCategory('not-a-uuid', { name: 'Bad ID' }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('success', false)
    })
  })

  it('returns 404 when id is a valid uuid but category does not exist', () => {
    cy.updateUninvestedCashCategory('00000000-0000-0000-0000-000000000000', {
      name: 'Ghost Pool',
    }).then((res) => {
      expect(res.status).to.eq(404)
      expect(res.body).to.have.property('success', false)
    })
  })

  it('returns 400 when nominal is negative', () => {
    cy.updateUninvestedCashCategory(categoryId, { nominal: -100 }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('success', false)
    })
  })
})

// ─── DELETE /api/investment-flow/v1/uninvested-cash/categories/:id ──────────

describe('Investment Flow API — DELETE /api/investment-flow/v1/uninvested-cash/categories/:id', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 204 with empty body on valid delete', () => {
    cy.createUninvestedCashCategory({ name: 'To Delete Pool', nominal: 100000 }).then(
      (createRes) => {
        expect(createRes.status).to.eq(201)
        const idToDelete = createRes.body.data.category.id

        cy.deleteUninvestedCashCategory(idToDelete).then((res) => {
          expect(res.status).to.eq(204)
          expect(res.body).to.be.oneOf(['', null, undefined])
        })
      }
    )
  })

  it('returns 401 when unauthenticated', () => {
    cy.clearCookies()
    cy.deleteUninvestedCashCategoryNoAuth('00000000-0000-0000-0000-000000000001').then((res) => {
      expect(res.status).to.be.oneOf([401, 307])
    })
  })
})

// ─── GET /api/investment-flow/v1/highlights ──────────────────────────────────

describe('Investment Flow API — GET /api/investment-flow/v1/highlights', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 with valid session', () => {
    cy.getInvestmentFlowHighlights().then((res) => {
      expect(res.status).to.eq(200)
    })
  })

  it('returns 401 when unauthenticated', () => {
    cy.clearCookies()
    cy.getInvestmentFlowHighlightsNoAuth().then((res) => {
      expect(res.status).to.be.oneOf([401, 307])
    })
  })

  it('returns success: true and data.highlights as an object', () => {
    cy.setupApiAuthCookies()
    cy.getInvestmentFlowHighlights().then((res) => {
      expect(res.body).to.have.property('success', true)
      expect(res.body.data).to.have.property('highlights').that.is.an('object')
    })
  })
})

// ─── PATCH /api/investment-flow/v1/highlights ────────────────────────────────

describe('Investment Flow API — PATCH /api/investment-flow/v1/highlights', () => {
  let nodeId

  before(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
    cy.setupApiAuthCookies()
    cy.createInvestmentFlowNode(makeCategoryPayload({ name: 'Highlight Test Category' })).then(
      (res) => {
        expect(res.status).to.eq(201)
        nodeId = res.body.data.id
      }
    )
  })

  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 and the updated highlights when setting a valid color', () => {
    cy.patchInvestmentFlowHighlights({ highlights: { [nodeId]: '#EF4444' } }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('success', true)
      expect(res.body.data.highlights).to.have.property(nodeId, '#EF4444')
    })
  })

  it('persists the updated highlights on subsequent GET', () => {
    cy.patchInvestmentFlowHighlights({ highlights: { [nodeId]: '#22C55E' } }).then(() => {
      cy.getInvestmentFlowHighlights().then((res) => {
        expect(res.body.data.highlights).to.have.property(nodeId, '#22C55E')
      })
    })
  })

  it('returns 401 when unauthenticated', () => {
    cy.clearCookies()
    cy.patchInvestmentFlowHighlightsNoAuth({ highlights: { [nodeId]: '#3B82F6' } }).then((res) => {
      expect(res.status).to.be.oneOf([401, 307])
    })
  })

  it('returns 400 when a highlight value is not a valid hex color', () => {
    cy.patchInvestmentFlowHighlights({ highlights: { [nodeId]: 'not-a-color' } }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('success', false)
    })
  })

  it('returns 400 when a highlight key is not a valid uuid', () => {
    cy.patchInvestmentFlowHighlights({ highlights: { 'not-a-uuid': '#EF4444' } }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('success', false)
    })
  })

  it('returns 400 when highlights field is missing', () => {
    cy.patchInvestmentFlowHighlights({}).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('success', false)
    })
  })
})
