import { faker } from '@faker-js/faker'

describe('Product Brand List API', () => {
  let testUserId
  let testProductBrandIds = []
  let testProductBrandsData = []

  const request = () => ({
    brand_status: faker.food.fruit(),
    note: faker.word.words(25),
    brand: faker.string.alphanumeric(10),
  })

  before(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
    cy.setupApiAuthCookies()

    Cypress._.times(3, () => {
      cy.AddProductBrand(request()).then((response) => {
        expect(response.body.success).to.be.true
        expect(response.body.productBrand).to.exist
        expect(response.status).to.eq(201)
        const productBrand = response.body.productBrand
        testUserId = productBrand.user_id
        testProductBrandIds.push(productBrand.id)
        testProductBrandsData.push(productBrand)
      })
    })
  })

  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('should return 200 with product brand list for authenticated user', () => {
    cy.GetListProductBrand().then((response) => {
      expect(response.status).to.eq(200)
      expect(response.body.success).to.be.true
      expect(response.body.data).to.be.an('array')
      expect(response.body.data.length).to.be.gte(testProductBrandIds.length)
      testProductBrandIds.forEach((id) => {
        expect(response.body.data.some((t) => t.id === id)).to.be.true
      })
    })
  })

  it("should return only authenticated user's product brand", () => {
    cy.GetListProductBrand().then((response) => {
      response.body.data.forEach((productBrand) => {
        expect(productBrand.user_id).to.eq(testUserId)
      })
    })
  })

  it('should sort product brand by brand ASC', () => {
    cy.GetListProductBrand().then((response) => {
      const productBrands = response.body.data
      for (let i = 0; i < productBrands.length - 1; i++) {
        const brand1 = productBrands[i].brand.toLowerCase()
        const brand2 = productBrands[i + 1].brand.toLowerCase()
        expect(brand1.localeCompare(brand2)).to.be.lte(0)
      }
    })
  })

  it('should include all product brands created in before()', () => {
    cy.GetListProductBrand().then((response) => {
      expect(response.body.data.length).to.be.gte(testProductBrandIds.length)
      testProductBrandIds.forEach((id) => {
        expect(response.body.data.some((t) => t.id === id)).to.be.true
      })
    })
  })

  it('should return created product brands with correct field values', () => {
    cy.GetListProductBrand().then((response) => {
      testProductBrandsData.forEach((created) => {
        const found = response.body.data.find((t) => t.id === created.id)
        expect(found).to.exist
        expect(found.brand).to.eq(created.brand)
        expect(found.brand_status).to.eq(created.brand_status)
        expect(found.note).to.eq(created.note)
        expect(found.user_id).to.eq(created.user_id)
      })
    })
  })

  it('should return 401 Unauthorized without auth', () => {
    cy.clearCookies()
    cy.GetListProductBrandNoAuth().then((response) => {
      expect(response.status).to.be.oneOf([401, 307])
      if (response.status === 401) {
        expect(response.body.error).to.eq('Unauthorized')
      }
    })
  })

  it('should return correct response structure', () => {
    cy.GetListProductBrand().then((response) => {
      expect(response.body).to.have.all.keys('success', 'data')
      expect(response.body.success).to.be.a('boolean')
      expect(response.body.data).to.be.an('array')

      if (response.body.data.length > 0) {
        const productBrands = response.body.data[0]
        expect(productBrands).to.have.all.keys([
          'created_at',
          'deleted_at',
          'id',
          'brand',
          'brand_status',
          'note',
          'updated_at',
          'user_id',
          'uuid',
          'product_count',
        ])
      }
    })
  })

  it('should return data as array even when no product brands exist', () => {
    cy.GetListProductBrand().then((response) => {
      expect(response.body.data).to.be.an('array')
    })
  })

  it('should return valid timestamps for each product brand', () => {
    cy.GetListProductBrand().then((response) => {
      response.body.data.forEach((item) => {
        expect(Date.parse(item.created_at)).to.not.be.NaN
        expect(Date.parse(item.updated_at)).to.not.be.NaN
      })
    })
  })

  it('should respond within 1000ms', () => {
    const start = Date.now()
    cy.GetListProductBrand().then(() => {
      const duration = Date.now() - start
      expect(duration).to.be.lte(1000)
      cy.log(`Response time: ${duration}ms`)
    })
  })

  // Generated by Cypress Author — 2026-05-15
  describe('product_count field', () => {
    let countBrandId
    let countProductNameId

    before(() => {
      cy.clearCookies()
      cy.clearLocalStorage()
      cy.setupApiAuthCookies()

      // Create a brand dedicated to product_count tests
      cy.AddProductBrand({
        brand: faker.food.fruit() + '-cnt-' + Date.now(),
        brand_status: 'active',
        note: faker.word.words(5),
      }).then((res) => {
        expect(res.status).to.eq(201)
        countBrandId = res.body.productBrand.id
        cy.log(`✅ Count brand created, ID: ${countBrandId}`)
      })

      // Create a product name for linking to the brand
      cy.AddProductName({
        product_name: faker.food.ingredient() + '-cnt-' + Date.now(),
      }).then((res) => {
        expect(res.status).to.eq(201)
        countProductNameId = res.body.productName.id
        cy.log(`✅ Count product name created, ID: ${countProductNameId}`)
      })
    })

    beforeEach(() => {
      cy.setupApiAuthCookies()
    })

    it('should include product_count in each brand object', () => {
      cy.GetListProductBrand().then((response) => {
        expect(response.status).to.eq(200)
        expect(response.body.data).to.be.an('array')

        response.body.data.forEach((brand) => {
          expect(brand).to.have.property('product_count')
        })

        cy.log(`✅ product_count present on all ${response.body.data.length} brands`)
      })
    })

    it('should return product_count as a number', () => {
      cy.GetListProductBrand().then((response) => {
        expect(response.status).to.eq(200)

        response.body.data.forEach((brand) => {
          expect(brand.product_count).to.be.a('number')
          expect(brand.product_count).to.be.gte(0)
        })

        cy.log('📊 All product_count values are non-negative numbers')
      })
    })

    it('should return 0 for brands with no active products', () => {
      // Create a brand with no products linked
      cy.AddProductBrand({
        brand: faker.food.fruit() + '-zero-' + Date.now(),
        brand_status: 'active',
        note: faker.word.words(5),
      }).then((brandRes) => {
        expect(brandRes.status).to.eq(201)
        const zeroBrandId = brandRes.body.productBrand.id
        cy.log(`✅ Zero-product brand created, ID: ${zeroBrandId}`)

        cy.GetListProductBrand().then((response) => {
          const found = response.body.data.find((b) => b.id === zeroBrandId)
          expect(found, 'Brand should appear in list').to.exist
          expect(found.product_count).to.eq(0)
          cy.log(`✅ product_count is 0 for brand with no active products`)
        })
      })
    })

    it('API vs DB: product_count should match active product count in DB after creating a product linked to the brand', () => {
      // Create one product linked to countBrandId
      cy.AddProduct({
        product_id: countProductNameId,
        brand_id: countBrandId,
        type: faker.word.noun(),
        usage_quantity: faker.number.int({ min: 1, max: 10 }),
        note: faker.word.words(5),
        product_image: '',
      }).then((productRes) => {
        expect(productRes.status).to.eq(201)
        cy.log(`✅ Product created with brand_id: ${countBrandId}`)

        // Get product_count from API
        cy.GetListProductBrand().then((listRes) => {
          const apiBrand = listRes.body.data.find((b) => b.id === countBrandId)
          expect(apiBrand, 'Brand should be in list').to.exist
          const apiCount = apiBrand.product_count
          cy.log(`📊 API product_count: ${apiCount}`)

          // Get count from DB
          cy.getActiveProductCountByBrandFromDb(countBrandId).then((dbCount) => {
            cy.log(`📊 DB active product count: ${dbCount}`)
            expect(apiCount).to.eq(dbCount)
            cy.log(`✅ API product_count (${apiCount}) matches DB count (${dbCount})`)
          })
        })
      })
    })
  })
})
