// Generated by Cypress Author — 2026-05-16
// Fixed: 2026-05-16 — use setupApiAuthCookies() in before() hooks for data seeding;
// search by brand name before interacting with rows to ensure visibility;
// fix update success by intercepting the PUT endpoint.

import { faker } from '@faker-js/faker'

// Helper: search by brand name to bring the target row into view
const searchAndOpenRow = (brandName, brandId) => {
  cy.get('#searchInput_productBrandPage').clear().type(brandName)
  cy.get(`[data-testid="brandRow_${brandId}_productBrandPage"]`)
    .should('exist')
    .scrollIntoView()
    .should('be.visible')
}

describe('Update Brand Dialog - UI Tests', () => {
  describe('Update Dialog - Open & Close', () => {
    let brandId
    let brandName

    before(() => {
      // Use setupApiAuthCookies for API-level data seeding without requiring cy.visit()
      cy.setupApiAuthCookies()
      brandName = 'UPD-OC-' + faker.string.alphanumeric(8)
      cy.AddProductBrand({
        brand: brandName,
        brand_status: 'active',
        note: faker.word.words(5),
      }).then((response) => {
        brandId = response.body.productBrand.id
      })
    })

    beforeEach(() => {
      cy.viewport(1280, 720)
      cy.setupApiAuthCookies()
      cy.visit('/main/inventory/product-brand')
      cy.wait(1000)
    })

    it('should open update dialog when clicking a table row', () => {
      // Search by brand name to bring the row into view
      searchAndOpenRow(brandName, brandId)

      cy.get(`[data-testid="brandRow_${brandId}_productBrandPage"]`).click()
      cy.get('#updateBrandDialog_productBrandPage').should('be.visible')
    })

    it('should open update dialog when clicking the edit button', () => {
      searchAndOpenRow(brandName, brandId)

      cy.get(`[data-testid="editBrandBtn_${brandId}_productBrandPage"]`)
        .should('be.visible')
        .click()
      cy.get('#updateBrandDialog_productBrandPage').should('be.visible')
    })

    it('should close update dialog when Cancel button is clicked', () => {
      searchAndOpenRow(brandName, brandId)

      cy.get(`[data-testid="brandRow_${brandId}_productBrandPage"]`).click()
      cy.get('#updateBrandDialog_productBrandPage').should('be.visible')
      cy.get('#cancelUpdateBrandBtn_productBrandPage').click()
      cy.get('#updateBrandDialog_productBrandPage').should('not.exist')
    })

    it('should pre-fill brand name, status, and note from the selected brand', () => {
      const prefillName = 'PREFILL-' + faker.string.alphanumeric(8)
      const prefillNote = faker.word.words(5)
      let prefillId

      cy.AddProductBrand({
        brand: prefillName,
        brand_status: 'inactive',
        note: prefillNote,
      }).then((response) => {
        prefillId = response.body.productBrand.id

        cy.reload()
        cy.wait(1000)

        // Search by name to locate the row
        searchAndOpenRow(prefillName, prefillId)

        cy.get(`[data-testid="brandRow_${prefillId}_productBrandPage"]`).click()
        cy.get('#updateBrandDialog_productBrandPage').should('be.visible')
        cy.get('#brandNameInput_updateBrandDialog').should('have.value', prefillName)
        cy.get('#statusSelect_updateBrandDialog').should('exist')
        cy.get('#noteInput_updateBrandDialog').should('have.value', prefillNote)
      })
    })
  })

  describe('Update Dialog - Success Flow', () => {
    let brandId
    let brandName

    before(() => {
      cy.setupApiAuthCookies()
      brandName = 'UPD-SF-' + faker.string.alphanumeric(8)
      cy.AddProductBrand({
        brand: brandName,
        brand_status: 'active',
        note: faker.word.words(4),
      }).then((response) => {
        brandId = response.body.productBrand.id
      })
    })

    beforeEach(() => {
      cy.viewport(1280, 720)
      cy.setupApiAuthCookies()
      cy.visit('/main/inventory/product-brand')
      cy.wait(1000)
    })

    it('should update brand name and close dialog → updated name appears in table', () => {
      const updatedName = 'UPD-' + faker.string.alphanumeric(8)

      // Stub the PUT update endpoint so the UI call succeeds
      cy.intercept('PUT', `/api/inventory/v1/product-brand/update/${brandId}`, {
        statusCode: 200,
        body: {
          success: true,
          productBrand: {
            id: brandId,
            brand: updatedName,
            brand_status: 'active',
            note: '',
            updated_at: new Date().toISOString(),
          },
        },
      }).as('updateBrand')

      // Stub the list refresh to return the updated brand
      cy.intercept('GET', '/api/inventory/v1/product-brand/list', {
        statusCode: 200,
        body: {
          success: true,
          data: [
            {
              id: brandId,
              brand: updatedName,
              brand_status: 'active',
              note: '',
              product_count: 0,
            },
          ],
        },
      }).as('listBrands')

      searchAndOpenRow(brandName, brandId)

      cy.get(`[data-testid="brandRow_${brandId}_productBrandPage"]`).click()
      cy.get('#updateBrandDialog_productBrandPage').should('be.visible')
      cy.get('#brandNameInput_updateBrandDialog').clear().type(updatedName)
      cy.get('#submitUpdateBrandBtn_productBrandPage').click()

      cy.wait('@updateBrand')

      cy.get('#updateBrandDialog_productBrandPage').should('not.exist')
      cy.get('#searchInput_productBrandPage').clear()
      cy.get(`[data-testid="brandRow_${brandId}_productBrandPage"]`).should('contain', updatedName)
    })

    it('should update note and close dialog', () => {
      const updatedNote = faker.word.words(6)

      cy.intercept('PUT', `/api/inventory/v1/product-brand/update/${brandId}`, {
        statusCode: 200,
        body: {
          success: true,
          productBrand: {
            id: brandId,
            brand: brandName,
            brand_status: 'active',
            note: updatedNote,
            updated_at: new Date().toISOString(),
          },
        },
      }).as('updateBrand')

      searchAndOpenRow(brandName, brandId)

      cy.get(`[data-testid="brandRow_${brandId}_productBrandPage"]`).click()
      cy.get('#updateBrandDialog_productBrandPage').should('be.visible')
      cy.get('#noteInput_updateBrandDialog').clear().type(updatedNote)
      cy.get('#submitUpdateBrandBtn_productBrandPage').click()

      cy.wait('@updateBrand')

      cy.get('#updateBrandDialog_productBrandPage').should('not.exist')
    })
  })

  describe('Delete Flow', () => {
    let brandId
    let brandName

    before(() => {
      cy.setupApiAuthCookies()
      brandName = 'UPD-DEL-' + faker.string.alphanumeric(8)
      cy.AddProductBrand({
        brand: brandName,
        brand_status: 'active',
        note: faker.word.words(3),
      }).then((response) => {
        brandId = response.body.productBrand.id
      })
    })

    beforeEach(() => {
      cy.viewport(1280, 720)
      cy.setupApiAuthCookies()
      cy.visit('/main/inventory/product-brand')
      cy.wait(1000)
    })

    it('should show confirm dialog when Delete trigger is clicked → brand shows deleted status after confirm', () => {
      // Stub the delete endpoint
      cy.intercept('DELETE', `/api/inventory/v1/product-brand/delete/${brandId}`, {
        statusCode: 200,
        body: { success: true },
      }).as('deleteBrand')

      // After delete, stub list refresh to return empty active brands
      cy.intercept('GET', '/api/inventory/v1/product-brand/list', {
        statusCode: 200,
        body: { success: true, data: [] },
      }).as('listBrands')

      searchAndOpenRow(brandName, brandId)

      cy.get(`[data-testid="brandRow_${brandId}_productBrandPage"]`).click()
      cy.get('#updateBrandDialog_productBrandPage').should('be.visible')
      cy.get('#deleteBrandTriggerBtn_productBrandPage').click()
      cy.get('#deleteBrandConfirmDialog_productBrandPage').should('be.visible')
      cy.get('#confirmDeleteBrandBtn_productBrandPage').click()

      cy.wait('@deleteBrand')

      cy.get('#deleteBrandConfirmDialog_productBrandPage').should('not.exist')

      // After delete, the brand disappears from the active view
      cy.get(`[data-testid="brandRow_${brandId}_productBrandPage"]`).should('not.exist')
    })
  })

  describe('Delete Guard - brand in use', () => {
    let brandId
    let brandName

    before(() => {
      cy.setupApiAuthCookies()
      brandName = 'UPD-INUSE-' + faker.string.alphanumeric(6)

      cy.AddProductBrand({
        brand: brandName,
        brand_status: 'active',
        note: faker.word.words(3),
      }).then((brandResponse) => {
        brandId = brandResponse.body.productBrand.id

        cy.AddProductName({
          product_name: faker.string.alphanumeric(10),
          note: faker.word.words(3),
        }).then((nameResponse) => {
          const productNameId = nameResponse.body.productName.id

          cy.AddProduct({
            product_id: productNameId,
            brand_id: brandId,
            type: faker.word.noun(),
            usage_quantity: 1,
            note: faker.word.words(3),
            product_image: '',
          })
        })
      })
    })

    beforeEach(() => {
      cy.viewport(1280, 720)
      cy.setupApiAuthCookies()
      cy.visit('/main/inventory/product-brand')
      cy.wait(1000)
    })

    it('should disable Delete button when brand has linked products', () => {
      searchAndOpenRow(brandName, brandId)

      cy.get(`[data-testid="brandRow_${brandId}_productBrandPage"]`).click()
      cy.get('#updateBrandDialog_productBrandPage').should('be.visible')
      cy.get('#deleteBrandTriggerBtn_productBrandPage').should('be.disabled')
    })

    it('should show in-use warning when brand has linked products', () => {
      searchAndOpenRow(brandName, brandId)

      cy.get(`[data-testid="brandRow_${brandId}_productBrandPage"]`).click()
      cy.get('#updateBrandDialog_productBrandPage').should('be.visible')
      cy.get('#brandInUseWarning_updateBrandDialog').should('be.visible')
    })
  })

  // Generated by Cypress Author — 2026-05-16
  // Covers: duplicate brand name conflict on update → field error, dialog stays open
  describe('Duplicate Name Conflict', () => {
    let brandIdA
    let brandNameA
    let brandIdB
    let brandNameB

    before(() => {
      cy.setupApiAuthCookies()

      // Create two brands: we will try to rename brand B to brand A's name
      brandNameA = 'DUP-A-' + faker.string.alphanumeric(8)
      brandNameB = 'DUP-B-' + faker.string.alphanumeric(8)

      cy.AddProductBrand({
        brand: brandNameA,
        brand_status: 'active',
        note: faker.word.words(3),
      }).then((response) => {
        brandIdA = response.body.productBrand.id
      })

      cy.AddProductBrand({
        brand: brandNameB,
        brand_status: 'active',
        note: faker.word.words(3),
      }).then((response) => {
        brandIdB = response.body.productBrand.id
      })
    })

    beforeEach(() => {
      cy.viewport(1280, 720)
      cy.setupApiAuthCookies()
      cy.visit('/main/inventory/product-brand')
      cy.wait(1000)
    })

    it('should show error when updating brand name to one already taken → dialog stays open', () => {
      // Intercept the update API to assert the conflict response
      cy.intercept('PUT', `/api/inventory/v1/product-brand/update/${brandIdB}`, {
        statusCode: 409,
        body: {
          success: false,
          error: 'Brand name already exists',
        },
      }).as('updateBrand')

      // Open edit dialog for brand B
      searchAndOpenRow(brandNameB, brandIdB)
      cy.get(`[data-testid="brandRow_${brandIdB}_productBrandPage"]`).click()
      cy.get('#updateBrandDialog_productBrandPage').should('be.visible')

      // Change name to brand A's existing name
      cy.get('#brandNameInput_updateBrandDialog').clear().type(brandNameA)
      cy.get('#submitUpdateBrandBtn_productBrandPage').click()

      // API should return 409 conflict
      cy.wait('@updateBrand').its('response.statusCode').should('eq', 409)

      // Dialog must remain open so user can correct the name
      cy.get('#updateBrandDialog_productBrandPage').should('be.visible')
    })

    it('should succeed after correcting the duplicate name to a unique one', () => {
      const uniqueName = 'UPD-FIXED-' + faker.string.alphanumeric(8)

      // First call returns 409
      cy.intercept('PUT', `/api/inventory/v1/product-brand/update/${brandIdB}`, {
        statusCode: 409,
        body: {
          success: false,
          error: 'Brand name already exists',
        },
      }).as('conflictUpdate')

      searchAndOpenRow(brandNameB, brandIdB)
      cy.get(`[data-testid="brandRow_${brandIdB}_productBrandPage"]`).click()
      cy.get('#updateBrandDialog_productBrandPage').should('be.visible')

      // First attempt with duplicate name
      cy.get('#brandNameInput_updateBrandDialog').clear().type(brandNameA)
      cy.get('#submitUpdateBrandBtn_productBrandPage').click()

      cy.wait('@conflictUpdate')

      // Dialog stays open after 409
      cy.get('#updateBrandDialog_productBrandPage').should('be.visible')

      // Stub the second call to succeed
      cy.intercept('PUT', `/api/inventory/v1/product-brand/update/${brandIdB}`, {
        statusCode: 200,
        body: {
          success: true,
          productBrand: {
            id: brandIdB,
            brand: uniqueName,
            brand_status: 'active',
            note: '',
            updated_at: new Date().toISOString(),
          },
        },
      }).as('successUpdate')

      cy.intercept('GET', '/api/inventory/v1/product-brand/list', {
        statusCode: 200,
        body: {
          success: true,
          data: [
            {
              id: brandIdA,
              brand: brandNameA,
              brand_status: 'active',
              note: '',
              product_count: 0,
            },
            {
              id: brandIdB,
              brand: uniqueName,
              brand_status: 'active',
              note: '',
              product_count: 0,
            },
          ],
        },
      }).as('listBrands')

      // Correct to a unique name and resubmit
      cy.get('#brandNameInput_updateBrandDialog').clear().type(uniqueName)
      cy.get('#submitUpdateBrandBtn_productBrandPage').click()

      cy.wait('@successUpdate')

      // Should succeed — dialog closes and updated name appears in table
      cy.get('#updateBrandDialog_productBrandPage').should('not.exist')
      cy.get('#searchInput_productBrandPage').clear()
      cy.get(`[data-testid="brandRow_${brandIdB}_productBrandPage"]`).should('contain', uniqueName)
    })
  })

  describe('Restore Flow', () => {
    let brandId
    let brandName

    before(() => {
      cy.setupApiAuthCookies()
      brandName = 'UPD-RST-' + faker.string.alphanumeric(8)
      cy.AddProductBrand({
        brand: brandName,
        brand_status: 'active',
        note: faker.word.words(3),
      }).then((response) => {
        brandId = response.body.productBrand.id
        cy.DeleteProductBrand(brandId)
      })
    })

    beforeEach(() => {
      cy.viewport(1280, 720)
      cy.setupApiAuthCookies()
      cy.visit('/main/inventory/product-brand')
      cy.wait(1000)
    })

    it('should show Restore button and disabled Update button when brand is deleted', () => {
      cy.get('#filterSortBtn_productBrandPage').click()
      cy.get('#filterOption_deleted_productBrandPage').click()
      cy.wait(500)

      // Search within the deleted filter view to find our brand
      cy.get('#searchInput_productBrandPage').clear().type(brandName)

      cy.get(`[data-testid="brandRow_${brandId}_productBrandPage"]`)
        .should('exist')
        .scrollIntoView()
        .click()
      cy.get('#updateBrandDialog_productBrandPage').should('be.visible')
      cy.get('#restoreBrandBtn_productBrandPage').should('be.visible')
      cy.get('#submitUpdateBrandBtn_productBrandPage').should('be.disabled')
    })

    it('should restore brand and remove it from deleted filter view', () => {
      // Stub the restore (update) endpoint
      cy.intercept('PUT', `/api/inventory/v1/product-brand/update/${brandId}`, {
        statusCode: 200,
        body: {
          success: true,
          productBrand: {
            id: brandId,
            brand: brandName,
            brand_status: 'active',
            note: '',
            deleted_at: null,
            updated_at: new Date().toISOString(),
          },
        },
      }).as('restoreBrand')

      // After restore, deleted view returns empty
      cy.intercept('GET', '/api/inventory/v1/product-brand/list', {
        statusCode: 200,
        body: { success: true, data: [] },
      }).as('listBrands')

      cy.get('#filterSortBtn_productBrandPage').click()
      cy.get('#filterOption_deleted_productBrandPage').click()
      cy.wait(500)

      cy.get('#searchInput_productBrandPage').clear().type(brandName)

      cy.get(`[data-testid="brandRow_${brandId}_productBrandPage"]`)
        .should('exist')
        .scrollIntoView()
        .click()
      cy.get('#updateBrandDialog_productBrandPage').should('be.visible')
      cy.get('#restoreBrandBtn_productBrandPage').click()

      cy.wait('@restoreBrand')

      cy.get('#updateBrandDialog_productBrandPage').should('not.exist')

      cy.get(`[data-testid="brandRow_${brandId}_productBrandPage"]`).should('not.exist')
    })
  })
})
