// Generated by Cypress Author — 2026-06-06
// Issue #135: Web Push notification delivery — push subscription API tests

import { RUNNING_ENDPOINTS } from '../../../fixtures/endpoints.js'

const PUSH_SUBSCRIPTION_API = RUNNING_ENDPOINTS.PUSH_SUBSCRIPTION

// ============================================================
// Push Subscription API — authenticated
// ============================================================
describe('Push Subscription API — POST (authenticated)', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('valid subscription object → 200 with push_notifications_enabled: true', () => {
    cy.apiRequestWithSession('POST', PUSH_SUBSCRIPTION_API, {
      body: {
        subscription: {
          endpoint: 'https://fcm.googleapis.com/fcm/send/test-endpoint',
          keys: {
            p256dh: 'fake-p256dh-key-for-testing',
            auth: 'fake-auth-key',
          },
        },
      },
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('data')
      expect(res.body.data).to.have.property('push_notifications_enabled', true)
    })
  })

  it('{ subscription: null } → 200 with push_notifications_enabled: false', () => {
    cy.apiRequestWithSession('POST', PUSH_SUBSCRIPTION_API, {
      body: { subscription: null },
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('data')
      expect(res.body.data).to.have.property('push_notifications_enabled', false)
    })
  })

  it('subscription without keys → 400 validation error', () => {
    // keys.p256dh and keys.auth are required — endpoint alone is not a valid subscription
    cy.apiRequestWithSession('POST', PUSH_SUBSCRIPTION_API, {
      body: {
        subscription: {
          endpoint: 'https://test.push/endpoint',
          // keys intentionally omitted; backend validates keys.p256dh and keys.auth
        },
      },
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(400)
      expect(res.body).to.have.property('error')
    })
  })
})

// ============================================================
// Push Subscription API — unauthenticated
// ============================================================
describe('Push Subscription API — POST (unauthenticated)', () => {
  beforeEach(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
  })

  it('returns 401 when no session cookie present', () => {
    cy.request({
      method: 'POST',
      url: PUSH_SUBSCRIPTION_API,
      body: {
        subscription: {
          endpoint: 'https://fcm.googleapis.com/fcm/send/test-endpoint',
          keys: { p256dh: 'fake-p256dh', auth: 'fake-auth' },
        },
      },
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(401)
      expect(res.body).to.have.property('error')
    })
  })
})
