// Generated by Cypress Author — 2026-06-04
// Issue #132: Running Settings page improvements
// Updated by Cypress Author — 2026-06-06
// Issue #135: Web Push notification delivery — push toggle UI tests

import { TEST_IDS } from '../../../fixtures/test-ids.js'
import { ROUTES } from '../../../fixtures/routes.js'
import { RUNNING_ENDPOINTS } from '../../../fixtures/endpoints.js'

const IDS = TEST_IDS.running_settings
const STRAVA_IDS = TEST_IDS.running_strava_connection
const SETTINGS_URL = ROUTES.running_settings
const PROFILE_API = RUNNING_ENDPOINTS.USER_PROFILE
const SETTINGS_API = RUNNING_ENDPOINTS.USER_SETTINGS
const STRAVA_STATUS_API = RUNNING_ENDPOINTS.STRAVA_STATUS
const STRAVA_DISCONNECT_API = RUNNING_ENDPOINTS.STRAVA_DISCONNECT
const ACTIVITIES_API = RUNNING_ENDPOINTS.USER_ACTIVITIES

// Suppress ServiceWorker redirect errors that can surface in headed Chrome when a
// previously-registered /sw.js is redirected (e.g. to /login in test mode).
// These are not caused by the tests themselves and should not fail the suite.
Cypress.on('uncaught:exception', (err) => {
  if (
    err.message.includes('ServiceWorker') ||
    err.message.includes('serviceWorker') ||
    err.message.includes('sw.js')
  ) {
    return false
  }
})

// --- Stub helpers ---

const stubProfileLoaded = (overrides = {}) => {
  cy.intercept('GET', PROFILE_API, {
    statusCode: 200,
    body: {
      data: {
        display_name: 'Test Runner',
        birth_date: '1994-06-15',
        height_cm: 172,
        weight_kg: 68,
        max_hr: 185,
        resting_hr_baseline: 55,
        ...overrides,
      },
      message: 'OK',
    },
  }).as('getProfile')
}

const stubSettingsLoaded = (overrides = {}) => {
  cy.intercept('GET', SETTINGS_API, {
    statusCode: 200,
    body: {
      data: {
        hr_zones_method: 'max_hr',
        threshold_hr: null,
        notify_post_activity: true,
        notify_weekly_review: true,
        notify_friday_prep: true,
        notify_anomaly: true,
        ...overrides,
      },
      message: 'OK',
    },
  }).as('getSettings')
}

const stubStravaConnected = () => {
  cy.intercept('GET', `**${STRAVA_STATUS_API}*`, {
    statusCode: 200,
    body: {
      data: {
        connected: true,
        needs_reconnect: false,
        athlete_id: '12345',
        last_sync_at: null,
      },
      message: 'OK',
    },
  }).as('getStravaStatus')
}

const stubStravaDisconnected = () => {
  cy.intercept('GET', `**${STRAVA_STATUS_API}*`, {
    statusCode: 200,
    body: {
      data: { connected: false },
      message: 'OK',
    },
  }).as('getStravaStatusDisconnected')
}

// Stub rt_users Supabase check (required for running layout onboarding guard)
const stubRtUsers = () => {
  cy.intercept('GET', '**/rest/v1/rt_users*', {
    statusCode: 200,
    body: [{ id: 'test-user-id', onboarding_complete: true }],
  }).as('rtUsersCheck')
}

// ============================================================
// Auth Guard
// ============================================================
describe('Running Settings — Auth Guard', () => {
  it('unauthenticated visit redirects to /login', () => {
    cy.clearAllCookies()
    cy.clearAllLocalStorage()
    cy.visit(SETTINGS_URL, { failOnStatusCode: false })
    cy.url().should('include', '/login')
  })
})

// ============================================================
// Page Load
// ============================================================
describe('Running Settings — Page Load', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.loginWithBypass()
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubProfileLoaded()
    stubSettingsLoaded()
    stubStravaConnected()
    cy.viewport(1280, 720)
    cy.visit(SETTINGS_URL)
  })

  it('page container is visible after loading', () => {
    cy.get(`#${IDS.page}`).should('be.visible')
  })
})

// ============================================================
// Profile Section
// ============================================================
describe('Running Settings — Profile Section', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.loginWithBypass()
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubSettingsLoaded()
    stubStravaConnected()
    cy.viewport(1280, 720)
  })

  it('profile form renders after loading skeleton disappears', () => {
    stubProfileLoaded()
    cy.visit(SETTINGS_URL)
    // Wait for loading skeleton to disappear
    cy.get(`#${IDS.profile_loading}`).should('not.exist')
    cy.get(`#${IDS.display_name_input}`).should('be.visible')
  })

  it('save profile → shows success message on 200', () => {
    stubProfileLoaded()
    cy.visit(SETTINGS_URL)
    cy.get(`#${IDS.profile_loading}`).should('not.exist')

    cy.intercept('PATCH', PROFILE_API, {
      statusCode: 200,
      body: { data: { display_name: 'Test Runner' }, message: 'Profile updated' },
    }).as('patchProfile')

    cy.get(`#${IDS.display_name_input}`).clear().type('Test Runner')
    cy.get(`#${IDS.profile_save_btn}`).click()

    cy.wait('@patchProfile')
    cy.get(`#${IDS.profile_save_success}`).should('be.visible')
  })

  it('save profile → shows error message on server error (422)', () => {
    stubProfileLoaded()
    cy.visit(SETTINGS_URL)
    cy.get(`#${IDS.profile_loading}`).should('not.exist')

    cy.intercept('PATCH', PROFILE_API, {
      statusCode: 422,
      body: { error: 'Validation failed' },
    }).as('patchProfileError')

    cy.get(`#${IDS.display_name_input}`).clear().type('Bad Input')
    cy.get(`#${IDS.profile_save_btn}`).click()

    cy.wait('@patchProfileError')
    cy.get(`#${IDS.profile_save_error}`).should('be.visible')
  })
})

// ============================================================
// HR Zones Section
// ============================================================
describe('Running Settings — HR Zones Section', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.loginWithBypass()
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubProfileLoaded()
    stubStravaConnected()
    cy.viewport(1280, 720)
  })

  it('threshold input is hidden when method is max_hr', () => {
    stubSettingsLoaded({ hr_zones_method: 'max_hr', threshold_hr: null })
    cy.visit(SETTINGS_URL)
    cy.get(`#${IDS.hr_zones_loading}`).should('not.exist')
    cy.get(`#${IDS.threshold_hr_input}`).should('not.exist')
  })

  it('selecting Lactate Threshold reveals threshold HR input', () => {
    stubSettingsLoaded({ hr_zones_method: 'max_hr', threshold_hr: null })
    cy.visit(SETTINGS_URL)
    cy.get(`#${IDS.hr_zones_loading}`).should('not.exist')

    // Open the Select dropdown and pick threshold option
    cy.get(`#${IDS.hr_zones_method_select}`).click()
    cy.contains('[role="option"]', 'Lactate Threshold').click()

    cy.get(`#${IDS.threshold_hr_input}`).should('be.visible')
  })

  it('threshold client-side validation — leaving threshold empty shows error without firing API', () => {
    stubSettingsLoaded({ hr_zones_method: 'max_hr', threshold_hr: null })
    cy.visit(SETTINGS_URL)
    cy.get(`#${IDS.hr_zones_loading}`).should('not.exist')

    // Switch to threshold method
    cy.get(`#${IDS.hr_zones_method_select}`).click()
    cy.contains('[role="option"]', 'Lactate Threshold').click()

    // Leave threshold input empty and click Save
    cy.intercept('PATCH', SETTINGS_API).as('patchSettings')
    cy.get(`#${IDS.hr_zones_save_btn}`).click()

    cy.get(`#${IDS.hr_zones_save_error}`).should('be.visible')
    // API should NOT have been called
    cy.get('@patchSettings.all').should('have.length', 0)
  })

  it('save HR zones → shows success on 200', () => {
    stubSettingsLoaded({ hr_zones_method: 'max_hr', threshold_hr: null })
    cy.visit(SETTINGS_URL)
    cy.get(`#${IDS.hr_zones_loading}`).should('not.exist')

    // Switch to Karvonen method
    cy.get(`#${IDS.hr_zones_method_select}`).click()
    cy.contains('[role="option"]', 'Karvonen').click()

    cy.intercept('PATCH', SETTINGS_API, {
      statusCode: 200,
      body: { data: { hr_zones_method: 'karvonen' }, message: 'Settings updated' },
    }).as('patchSettingsKarvonen')

    cy.get(`#${IDS.hr_zones_save_btn}`).click()
    cy.wait('@patchSettingsKarvonen')
    cy.get(`#${IDS.hr_zones_save_success}`).should('be.visible')
  })
})

// ============================================================
// Notifications Section
// ============================================================
describe('Running Settings — Notifications Section', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.loginWithBypass()
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubProfileLoaded()
    stubStravaConnected()
    stubSettingsLoaded({
      notify_post_activity: true,
      notify_weekly_review: true,
      notify_friday_prep: true,
      notify_anomaly: true,
    })
    cy.viewport(1280, 720)
    cy.visit(SETTINGS_URL)
    cy.get(`#${IDS.notifications_loading}`).should('not.exist')
  })

  it('all 4 notification toggles are rendered', () => {
    cy.get(`#${IDS.notify_post_activity_toggle}`).should('exist')
    cy.get(`#${IDS.notify_weekly_review_toggle}`).should('exist')
    cy.get(`#${IDS.notify_friday_prep_toggle}`).should('exist')
    cy.get(`#${IDS.notify_anomaly_toggle}`).should('exist')
  })

  it('clicking a toggle fires PATCH to settings API', () => {
    cy.intercept('PATCH', SETTINGS_API, {
      statusCode: 200,
      body: { data: { notify_post_activity: false }, message: 'Settings updated' },
    }).as('patchToggle')

    cy.get(`#${IDS.notify_post_activity_toggle}`).click()
    cy.wait('@patchToggle')
  })
})

// ============================================================
// Strava Connection
// ============================================================
describe('Running Settings — Strava Connection (connected state)', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.loginWithBypass()
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubProfileLoaded()
    stubSettingsLoaded()
    cy.viewport(1280, 720)
  })

  it('connected state shows the connected card and Disconnect button', () => {
    stubStravaConnected()
    cy.visit(SETTINGS_URL)
    // scrollIntoView is needed because the card parent has overflow:hidden which clips visibility
    cy.get(`#${STRAVA_IDS.settings_connected_state}`).scrollIntoView().should('be.visible')
    cy.get(`#${IDS.strava_disconnect_btn}`)
      .scrollIntoView()
      .should('be.visible')
      .and('contain.text', 'Disconnect')
  })

  it('Disconnect button → POST disconnect, then shows disconnected state', () => {
    stubStravaConnected()
    cy.visit(SETTINGS_URL)
    cy.get(`#${STRAVA_IDS.settings_connected_state}`).scrollIntoView().should('be.visible')

    cy.intercept('POST', STRAVA_DISCONNECT_API, {
      statusCode: 200,
      body: { data: null, message: 'Disconnected' },
    }).as('postDisconnect')

    // After disconnect, the page re-fetches strava status
    cy.intercept('GET', `**${STRAVA_STATUS_API}*`, {
      statusCode: 200,
      body: { data: { connected: false }, message: 'OK' },
    }).as('getStravaStatusAfterDisconnect')

    cy.get(`#${IDS.strava_disconnect_btn}`).click()
    cy.wait('@postDisconnect')
    cy.wait('@getStravaStatusAfterDisconnect')
    cy.get(`#${STRAVA_IDS.settings_disconnected_state}`).should('be.visible')
  })
})

// ============================================================
// Danger Zone
// ============================================================
describe('Running Settings — Danger Zone', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.loginWithBypass()
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubProfileLoaded()
    stubSettingsLoaded()
    stubStravaConnected()
    cy.viewport(1280, 720)
    cy.visit(SETTINGS_URL)
    cy.get(`#${IDS.page}`).should('be.visible')
  })

  it('clicking Delete All opens the confirmation dialog', () => {
    cy.get(`#${IDS.danger_zone_delete_btn}`).click()
    cy.get(`#${IDS.danger_zone_dialog}`).should('be.visible')
  })

  it('confirm button is disabled when dialog first opens', () => {
    cy.get(`#${IDS.danger_zone_delete_btn}`).click()
    cy.get(`#${IDS.danger_zone_confirm_btn}`).should('be.disabled')
  })

  it('typing wrong text keeps confirm button disabled', () => {
    cy.get(`#${IDS.danger_zone_delete_btn}`).click()
    cy.get(`#${IDS.danger_zone_confirm_input}`).type('WRONG')
    cy.get(`#${IDS.danger_zone_confirm_btn}`).should('be.disabled')
  })

  it('typing DELETE enables confirm button and completing delete closes dialog', () => {
    cy.get(`#${IDS.danger_zone_delete_btn}`).click()
    cy.get(`#${IDS.danger_zone_confirm_input}`).clear().type('DELETE')
    cy.get(`#${IDS.danger_zone_confirm_btn}`).should('not.be.disabled')

    cy.intercept('DELETE', ACTIVITIES_API, {
      statusCode: 200,
      body: { data: { deleted: 5 }, message: 'All activity data deleted' },
    }).as('deleteActivities')

    cy.get(`#${IDS.danger_zone_confirm_btn}`).click()
    cy.wait('@deleteActivities')
    cy.get(`#${IDS.danger_zone_dialog}`).should('not.exist')
  })
})

// ============================================================
// Push Notifications Toggle
// ============================================================
describe('Running Settings — Push Notifications', () => {
  const PUSH_SUBSCRIPTION_API = RUNNING_ENDPOINTS.PUSH_SUBSCRIPTION

  before(() => {
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.loginWithBypass()
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubProfileLoaded()
    stubStravaConnected()
    cy.viewport(1280, 720)
  })

  it('enable flow → POST subscription object when permission is granted', () => {
    // Start with push disabled
    stubSettingsLoaded({ push_notifications_enabled: false })

    // Use cy.intercept before cy.visit so the stub is in place when the page loads
    cy.intercept('POST', PUSH_SUBSCRIPTION_API, {
      statusCode: 200,
      body: { data: { push_notifications_enabled: true }, message: 'Push subscription saved' },
    }).as('postSubscription')

    // Stub browser push APIs using plain functions (not cy.stub) inside onBeforeLoad
    // cy.stub() cannot be used in onBeforeLoad — it requires the Cypress context which is not
    // available during app initialization. Plain functions are used instead.
    cy.visit(SETTINGS_URL, {
      onBeforeLoad(win) {
        const fakeSubscription = {
          toJSON: () => ({
            endpoint: 'https://fcm.googleapis.com/fcm/send/test-endpoint',
            keys: { p256dh: 'fake-p256dh-key', auth: 'fake-auth-key' },
          }),
        }
        const fakePushManager = {
          subscribe: () => Promise.resolve(fakeSubscription),
          getSubscription: () => Promise.resolve(null),
        }
        const fakeRegistration = { pushManager: fakePushManager }

        // Override only Notification.requestPermission — permission getter is read-only in Chrome
        // and cannot be set directly. The component only calls requestPermission() and checks
        // its return value, so we only need to stub that method.
        win.Notification.requestPermission = () => Promise.resolve('granted')

        // Override serviceWorker so register returns our fake registration
        Object.defineProperty(win.navigator, 'serviceWorker', {
          configurable: true,
          writable: true,
          value: {
            register: () => Promise.resolve(fakeRegistration),
            ready: Promise.resolve(fakeRegistration),
          },
        })
      },
    })

    cy.get(`#${IDS.notifications_loading}`).should('not.exist')

    // Click the push toggle — force true because shadcn Switch may have pointer-events managed
    cy.get(`#${IDS.push_notifications_toggle}`).click({ force: true })
    cy.wait('@postSubscription').then((interception) => {
      expect(interception.request.body).to.have.property('subscription')
      expect(interception.request.body.subscription).to.not.be.null
    })
  })

  it('disable flow → POST { subscription: null } to clear subscription', () => {
    // Start with push already enabled
    stubSettingsLoaded({ push_notifications_enabled: true })

    cy.intercept('POST', PUSH_SUBSCRIPTION_API, {
      statusCode: 200,
      body: { data: { push_notifications_enabled: false }, message: 'Push subscription cleared' },
    }).as('clearSubscription')

    cy.visit(SETTINGS_URL, {
      onBeforeLoad(win) {
        // Stub unsubscribe on an existing subscription — plain functions only in onBeforeLoad
        const fakeExistingSubscription = {
          unsubscribe: () => Promise.resolve(true),
        }
        const fakePushManager = {
          getSubscription: () => Promise.resolve(fakeExistingSubscription),
        }
        const fakeRegistration = { pushManager: fakePushManager }
        Object.defineProperty(win.navigator, 'serviceWorker', {
          configurable: true,
          writable: true,
          value: {
            register: () => Promise.resolve(fakeRegistration),
            ready: Promise.resolve(fakeRegistration),
          },
        })
      },
    })

    cy.get(`#${IDS.notifications_loading}`).should('not.exist')
    // Toggle is currently ON (push_notifications_enabled: true) — clicking turns it off
    cy.get(`#${IDS.push_notifications_toggle}`).click({ force: true })
    cy.wait('@clearSubscription').then((interception) => {
      expect(interception.request.body).to.deep.equal({ subscription: null })
    })
  })

  it('permission denied → shows error element, toggle stays OFF', () => {
    stubSettingsLoaded({ push_notifications_enabled: false })

    cy.visit(SETTINGS_URL, {
      onBeforeLoad(win) {
        // Override only requestPermission — the permission getter is read-only in Chrome.
        // The component calls Notification.requestPermission() and checks the return value.
        win.Notification.requestPermission = () => Promise.resolve('denied')
        const fakePushManager = { getSubscription: () => Promise.resolve(null) }
        const fakeRegistration = { pushManager: fakePushManager }
        Object.defineProperty(win.navigator, 'serviceWorker', {
          configurable: true,
          writable: true,
          value: {
            register: () => Promise.resolve(fakeRegistration),
            ready: Promise.resolve(fakeRegistration),
          },
        })
      },
    })

    cy.get(`#${IDS.notifications_loading}`).should('not.exist')
    cy.get(`#${IDS.push_notifications_toggle}`).click({ force: true })

    // Error message should appear after permission is denied.
    // scrollIntoView is needed because the card container has overflow:hidden which clips
    // the error paragraph from Cypress' visibility check without scrolling.
    cy.get(`#${IDS.push_notifications_error}`).scrollIntoView().should('be.visible')

    // Toggle should remain unchecked (aria-checked="false")
    cy.get(`#${IDS.push_notifications_toggle}`).should('have.attr', 'aria-checked', 'false')
  })

  it('persist after reload → toggle is ON when settings return push_notifications_enabled: true', () => {
    // First load with push enabled
    stubSettingsLoaded({ push_notifications_enabled: true })

    cy.visit(SETTINGS_URL)
    cy.get(`#${IDS.notifications_loading}`).should('not.exist')

    // Toggle should be ON after initial load
    cy.get(`#${IDS.push_notifications_toggle}`).should('have.attr', 'aria-checked', 'true')

    // Simulate a reload — re-stub the settings endpoint before reload
    cy.intercept('GET', SETTINGS_API, {
      statusCode: 200,
      body: {
        data: {
          hr_zones_method: 'max_hr',
          threshold_hr: null,
          notify_post_activity: true,
          notify_weekly_review: true,
          notify_friday_prep: true,
          notify_anomaly: true,
          push_notifications_enabled: true,
        },
        message: 'OK',
      },
    }).as('getSettingsAfterReload')

    cy.reload()
    stubRtUsers()
    stubProfileLoaded()
    stubStravaConnected()
    cy.wait('@getSettingsAfterReload')

    cy.get(`#${IDS.notifications_loading}`).should('not.exist')
    cy.get(`#${IDS.push_notifications_toggle}`).should('have.attr', 'aria-checked', 'true')
  })
})
