import constants from '../../../../../fixtures/app-constants.json'

const TARGET_EFFORT = constants.endpoints.running_analytics.target_effort
const PERSONAL_BESTS = constants.endpoints.running_analytics.personal_bests
const CALORIE_TREND = constants.endpoints.running_analytics.calorie_trend
const FITNESS_AGE = constants.endpoints.running_analytics.fitness_age
const ENDURANCE_SCORE = constants.endpoints.running_analytics.endurance_score
const ZONES = constants.endpoints.running_analytics.zones
const ZONES_REFERENCE = constants.endpoints.running_analytics.zones_reference
const GEAR_ANALYTICS = constants.endpoints.running_analytics.gear
const PMC = constants.endpoints.running_analytics.pmc
const SESSION_PROFILE = constants.endpoints.running_analytics.session_profile

Cypress.Commands.add('getTargetEffort', (qs = {}) => {
  return cy.apiRequestWithSession('GET', TARGET_EFFORT, { qs })
})

Cypress.Commands.add('getTargetEffortNoAuth', () => {
  return cy.apiRequestNoAuth('GET', TARGET_EFFORT)
})

Cypress.Commands.add('getPersonalBests', (qs = {}) => {
  return cy.apiRequestWithSession('GET', PERSONAL_BESTS, { qs })
})

Cypress.Commands.add('getPersonalBestsNoAuth', () => {
  return cy.apiRequestNoAuth('GET', PERSONAL_BESTS)
})

Cypress.Commands.add('getCalorieTrend', (qs = {}) => {
  return cy.apiRequestWithSession('GET', CALORIE_TREND, { qs })
})

Cypress.Commands.add('getCalorieTrendNoAuth', () => {
  return cy.apiRequestNoAuth('GET', CALORIE_TREND)
})

Cypress.Commands.add('getFitnessAgeTrend', () => {
  return cy.apiRequestWithSession('GET', FITNESS_AGE)
})

Cypress.Commands.add('getFitnessAgeTrendNoAuth', () => {
  return cy.apiRequestNoAuth('GET', FITNESS_AGE)
})

Cypress.Commands.add('getEnduranceScore', () => {
  return cy.apiRequestWithSession('GET', ENDURANCE_SCORE)
})

Cypress.Commands.add('getEnduranceScoreNoAuth', () => {
  return cy.apiRequestNoAuth('GET', ENDURANCE_SCORE)
})

Cypress.Commands.add('getZoneAnalytics', (qs = {}) => {
  return cy.apiRequestWithSession('GET', ZONES, { qs })
})

Cypress.Commands.add('getZoneAnalyticsNoAuth', () => {
  return cy.apiRequestNoAuth('GET', ZONES)
})

Cypress.Commands.add('getZonesReference', () => {
  return cy.apiRequestWithSession('GET', ZONES_REFERENCE)
})

Cypress.Commands.add('getZonesReferenceNoAuth', () => {
  return cy.apiRequestNoAuth('GET', ZONES_REFERENCE)
})

Cypress.Commands.add('getGearAnalytics', (qs = {}) => {
  return cy.apiRequestWithSession('GET', GEAR_ANALYTICS, { qs })
})

Cypress.Commands.add('getGearAnalyticsNoAuth', () => {
  return cy.apiRequestNoAuth('GET', GEAR_ANALYTICS)
})

Cypress.Commands.add('getPmc', (qs = {}) => {
  return cy.apiRequestWithSession('GET', PMC, { qs })
})

Cypress.Commands.add('getPmcNoAuth', () => {
  return cy.apiRequestNoAuth('GET', PMC)
})

// Generated by Cypress Author — 2026-06-20
Cypress.Commands.add('getSessionProfile', () => {
  return cy.apiRequestWithSession('GET', SESSION_PROFILE)
})

Cypress.Commands.add('getSessionProfileNoAuth', () => {
  return cy.apiRequestNoAuth('GET', SESSION_PROFILE)
})
