// Generated by Cypress Author — 2026-05-20
// Covers: Running Tracker onboarding flow (3 steps):
//   Step 1 — Biometrics (field rendering, validation, formula/manual max HR, happy path)
//   Step 2 — Strava Connect (skip flow, connect button)
//   Step 3 — First Goal (no-goal path, yes-goal path with race distance + date)
//   Auth guard — unauthenticated visit redirects to /login
//   (app) layout guard — routes under /main/running/(app)/ require real Supabase session
//
// AUTH STRATEGY:
//   - /main/running/onboarding uses app/main/layout.jsx → requireAuth() → bypass-friendly
//     BUT we also call cy.setupApiAuthCookies() so the API calls in the form work correctly
//   - /main/running/dashboard (and other (app) routes) use (app)/layout.jsx which calls
//     supabase.auth.getUser() directly. We must use cy.setupApiAuthCookies() for a real
//     Supabase session — the bypass cookie alone is NOT sufficient for those routes.

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/**
 * Fills Step 1 (Biometrics) with valid values using placeholder-based selectors.
 * These selectors are interim — id attributes have been requested via Frontend signal.
 */
const fillBiometricsValid = () => {
  // Birth date — use a date ~30 years ago so the formula HR preview shows
  cy.get('input[type="date"]').first().type('1994-06-15')
  // Height
  cy.get('input[placeholder="170"]').type('172')
  // Weight
  cy.get('input[placeholder="65"]').type('68')
  // Resting HR
  cy.get('input[placeholder="55"]').type('58')
  // Max HR mode stays as 'formula' (default) — no extra action needed
}

// ---------------------------------------------------------------------------
// A. Unauthenticated access guard
// ---------------------------------------------------------------------------

describe('Running Onboarding — Auth Guard', () => {
  it('unauthenticated visit to /main/running/onboarding redirects to /login', () => {
    cy.clearAllCookies()
    cy.clearAllLocalStorage()
    cy.visit('/main/running/onboarding', { failOnStatusCode: false })
    cy.url().should('include', '/login')
  })

  it('unauthenticated visit to (app) route /main/running/dashboard redirects to /login', () => {
    cy.clearAllCookies()
    cy.clearAllLocalStorage()
    cy.visit('/main/running/dashboard', { failOnStatusCode: false })
    cy.url().should('include', '/login')
  })
})

// ---------------------------------------------------------------------------
// B. Step 1 — Biometrics form rendering
// ---------------------------------------------------------------------------

describe('Running Onboarding — Step 1 Biometrics (rendering)', () => {
  before(() => {
    // setupApiAuthCookies ensures the real Supabase session cookie is present
    // so API calls from the form work; loginWithBypass handles requireAuth() in main layout
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.viewport(1280, 720)
    cy.loginWithBypass()
    cy.setupApiAuthCookies()
    cy.visit('/main/running/onboarding')
  })

  it('renders the onboarding page heading', () => {
    cy.contains('Welcome to Running Tracker').should('be.visible')
  })

  it('shows step 1 of 3 label', () => {
    cy.contains('Step 1 of 3').should('be.visible')
  })

  it('shows step indicator with Biometrics, Connect Strava, First Goal', () => {
    cy.contains('Biometrics').should('be.visible')
    cy.contains('Connect Strava').should('be.visible')
    cy.contains('First Goal').should('be.visible')
  })

  it('renders the Biometrics form heading', () => {
    cy.contains("Let's set up your biometrics").should('be.visible')
  })

  it('renders Birth date, Height, Weight, Resting HR and Max HR fields', () => {
    cy.get('input[type="date"]').should('exist')
    cy.get('input[placeholder="170"]').should('exist')
    cy.get('input[placeholder="65"]').should('exist')
    cy.get('input[placeholder="55"]').should('exist')
  })

  it('formula mode is selected by default and shows formula label', () => {
    cy.contains('Use formula (220 − age)').should('be.visible')
    cy.contains('Enter manually').should('be.visible')
    // manual input should not exist in formula mode
    cy.get('input[placeholder="185"]').should('not.exist')
  })

  it('shows Continue button', () => {
    cy.contains('button', 'Continue').should('be.visible')
  })

  it('does NOT show a Back button on step 1', () => {
    cy.get('[aria-label="Go back to previous step"]').should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// C. Step 1 — Biometrics validation
// ---------------------------------------------------------------------------

describe('Running Onboarding — Step 1 Biometrics (validation)', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.viewport(1280, 720)
    cy.loginWithBypass()
    cy.setupApiAuthCookies()
    cy.visit('/main/running/onboarding')
  })

  it('shows validation error when birth date is missing → does not advance to step 2', () => {
    // Stub the biometric API to prevent real DB writes during validation tests
    cy.intercept('POST', '/api/running/v1/onboarding/biometric').as('biometricSave')

    cy.get('input[placeholder="170"]').type('172')
    cy.get('input[placeholder="65"]').type('68')
    cy.get('input[placeholder="55"]').type('58')

    cy.contains('button', 'Continue').click()

    // Still on step 1 — birth date error should appear
    cy.contains('Birth date is required').should('be.visible')
    cy.contains('Step 1 of 3').should('be.visible')
  })

  it('shows validation error when height is out of range (99) → does not advance', () => {
    cy.get('input[type="date"]').first().type('1994-06-15')
    cy.get('input[placeholder="170"]').type('99')
    cy.get('input[placeholder="65"]').type('68')
    cy.get('input[placeholder="55"]').type('58')
    cy.contains('button', 'Continue').click()

    cy.contains('Height must be between 100 and 250 cm').should('be.visible')
    cy.contains('Step 1 of 3').should('be.visible')
  })

  it('shows validation error when weight is out of range (25) → does not advance', () => {
    cy.get('input[type="date"]').first().type('1994-06-15')
    cy.get('input[placeholder="170"]').type('172')
    cy.get('input[placeholder="65"]').type('25')
    cy.get('input[placeholder="55"]').type('58')
    cy.contains('button', 'Continue').click()

    cy.contains('Weight must be between 30 and 300 kg').should('be.visible')
    cy.contains('Step 1 of 3').should('be.visible')
  })

  it('shows validation error when resting HR is out of range (130) → does not advance', () => {
    cy.get('input[type="date"]').first().type('1994-06-15')
    cy.get('input[placeholder="170"]').type('172')
    cy.get('input[placeholder="65"]').type('68')
    cy.get('input[placeholder="55"]').type('130')
    cy.contains('button', 'Continue').click()

    cy.contains('Resting HR must be between 30 and 120 bpm').should('be.visible')
    cy.contains('Step 1 of 3').should('be.visible')
  })

  it('shows manual max HR error when mode is manual and field is empty', () => {
    cy.get('input[type="date"]').first().type('1994-06-15')
    cy.get('input[placeholder="170"]').type('172')
    cy.get('input[placeholder="65"]').type('68')
    cy.get('input[placeholder="55"]').type('58')

    // Switch to manual mode
    cy.contains('Enter manually').click()
    cy.get('input[placeholder="185"]').should('be.visible')
    // Leave manual max HR empty and try to submit
    cy.contains('button', 'Continue').click()

    cy.contains('Max HR is required').should('be.visible')
    cy.contains('Step 1 of 3').should('be.visible')
  })

  it('shows manual max HR out-of-range error (50 bpm) → does not advance', () => {
    cy.get('input[type="date"]').first().type('1994-06-15')
    cy.get('input[placeholder="170"]').type('172')
    cy.get('input[placeholder="65"]').type('68')
    cy.get('input[placeholder="55"]').type('58')

    cy.contains('Enter manually').click()
    cy.get('input[placeholder="185"]').type('50')
    cy.contains('button', 'Continue').click()

    cy.contains('Max HR must be between 100 and 250 bpm').should('be.visible')
    cy.contains('Step 1 of 3').should('be.visible')
  })
})

// ---------------------------------------------------------------------------
// D. Step 1 — Max HR formula preview
// ---------------------------------------------------------------------------

describe('Running Onboarding — Step 1 Max HR formula preview', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.viewport(1280, 720)
    cy.loginWithBypass()
    cy.setupApiAuthCookies()
    cy.visit('/main/running/onboarding')
  })

  it('shows placeholder text before birth date is entered', () => {
    cy.contains('Enter your birth date to see the estimate').should('be.visible')
  })

  it('shows estimated max HR bpm after entering birth date', () => {
    cy.get('input[type="date"]').first().type('1994-06-15')
    // 220 - 32 = 188 (age in 2026)
    cy.contains('Estimated max HR:').should('be.visible')
    cy.contains('bpm').should('be.visible')
  })

  it('manual mode hides formula preview and shows text input', () => {
    cy.contains('Enter manually').click()
    cy.contains('Estimated max HR:').should('not.exist')
    cy.get('input[placeholder="185"]').should('be.visible')
  })

  it('switching back to formula mode hides manual input', () => {
    cy.contains('Enter manually').click()
    cy.get('input[placeholder="185"]').should('be.visible')

    cy.contains('Use formula (220 − age)').click()
    cy.get('input[placeholder="185"]').should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// E. Step 1 → Step 2 — Advancing via Continue (happy path, stubbed API)
// ---------------------------------------------------------------------------

describe('Running Onboarding — Step 1 → Step 2 (happy path, stubbed)', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.viewport(1280, 720)
    cy.loginWithBypass()
    cy.setupApiAuthCookies()
    cy.visit('/main/running/onboarding')
  })

  it('fills valid biometrics and advances to Step 2 after API succeeds', () => {
    cy.intercept('POST', '/api/running/v1/onboarding/biometric', {
      statusCode: 200,
      body: { data: { id: 'test-user-id' }, message: 'Biometric data saved' },
    }).as('saveBiometric')

    fillBiometricsValid()
    cy.contains('button', 'Continue').click()

    cy.wait('@saveBiometric').its('response.statusCode').should('eq', 200)

    // Should now be on step 2
    cy.contains('Connect Strava').should('be.visible')
    cy.contains('Step 2 of 3').should('be.visible')
  })

  it('shows root error when biometric API returns 500', () => {
    cy.intercept('POST', '/api/running/v1/onboarding/biometric', {
      statusCode: 500,
      body: { error: 'Internal server error', message: 'Something went wrong' },
    }).as('saveBiometricFail')

    fillBiometricsValid()
    cy.contains('button', 'Continue').click()

    cy.wait('@saveBiometricFail')

    // Root error should appear; stays on step 1
    cy.get('[role="alert"]').should('be.visible')
    cy.contains('Step 1 of 3').should('be.visible')
  })
})

// ---------------------------------------------------------------------------
// F. Step 2 — Strava Connect
// ---------------------------------------------------------------------------

describe('Running Onboarding — Step 2 Strava Connect', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  const advanceToStep2 = () => {
    cy.intercept('POST', '/api/running/v1/onboarding/biometric', {
      statusCode: 200,
      body: { data: {}, message: 'Biometric data saved' },
    }).as('saveBiometric')

    fillBiometricsValid()
    cy.contains('button', 'Continue').click()
    cy.wait('@saveBiometric')
    cy.contains('Step 2 of 3').should('be.visible')
  }

  beforeEach(() => {
    cy.viewport(1280, 720)
    cy.loginWithBypass()
    cy.setupApiAuthCookies()
    cy.visit('/main/running/onboarding')
    advanceToStep2()
  })

  it('renders Step 2 heading and Strava benefits', () => {
    cy.contains('Connect Strava').should('be.visible')
    cy.contains('Auto-sync all past and future activities').should('be.visible')
    cy.contains('Real-time HR, GPS, and pace streams').should('be.visible')
    cy.contains('AI Coach insights right after each run').should('be.visible')
  })

  it('shows Connect with Strava and Skip buttons', () => {
    cy.get('[aria-label="Connect with Strava"]').should('be.visible')
    cy.get('[aria-label="Skip Strava connection for now"]').should('be.visible')
  })

  it('shows Back button on step 2', () => {
    cy.get('[aria-label="Go back to previous step"]').should('be.visible')
  })

  it('clicking Back returns to Step 1', () => {
    cy.get('[aria-label="Go back to previous step"]').click()
    cy.contains('Step 1 of 3').should('be.visible')
    cy.contains("Let's set up your biometrics").should('be.visible')
  })

  it('clicking Skip advances to Step 3', () => {
    cy.get('[aria-label="Skip Strava connection for now"]').click()
    cy.contains('Step 3 of 3').should('be.visible')
    cy.contains('Set your first goal').should('be.visible')
  })
})

// ---------------------------------------------------------------------------
// G. Step 3 — First Goal (no race planned)
// ---------------------------------------------------------------------------

describe('Running Onboarding — Step 3 First Goal (no race planned)', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  const advanceToStep3 = () => {
    cy.intercept('POST', '/api/running/v1/onboarding/biometric', {
      statusCode: 200,
      body: { data: {}, message: 'Biometric data saved' },
    }).as('saveBiometric')

    fillBiometricsValid()
    cy.contains('button', 'Continue').click()
    cy.wait('@saveBiometric')

    // Skip Strava
    cy.get('[aria-label="Skip Strava connection for now"]').click()
    cy.contains('Step 3 of 3').should('be.visible')
  }

  beforeEach(() => {
    cy.viewport(1280, 720)
    cy.loginWithBypass()
    cy.setupApiAuthCookies()
    cy.visit('/main/running/onboarding')
    advanceToStep3()
  })

  it('renders Step 3 heading and goal toggle', () => {
    cy.contains('Set your first goal').should('be.visible')
    cy.get('[aria-label="Yes, I have a race"]').should('exist')
    cy.get('[aria-label="No race planned yet"]').should('exist')
  })

  it('"No race planned yet" is default — goal fields are hidden', () => {
    cy.get('input[placeholder="e.g. 30"]').should('not.exist')
  })

  it('shows "Go to dashboard" button when no goal is selected', () => {
    cy.contains('button', 'Go to dashboard').should('be.visible')
  })

  it('clicking "Go to dashboard" without goal completes onboarding → redirects to /main/running/dashboard', () => {
    cy.intercept('POST', '/api/running/v1/onboarding/complete', {
      statusCode: 200,
      body: { data: {}, message: 'Onboarding complete' },
    }).as('completeOnboarding')

    cy.contains('button', 'Go to dashboard').click()

    cy.wait('@completeOnboarding')
    cy.url().should('include', '/main/running/dashboard')
  })
})

// ---------------------------------------------------------------------------
// H. Step 3 — First Goal (yes, I have a race)
// ---------------------------------------------------------------------------

describe('Running Onboarding — Step 3 First Goal (yes, I have a race)', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  const advanceToStep3 = () => {
    cy.intercept('POST', '/api/running/v1/onboarding/biometric', {
      statusCode: 200,
      body: { data: {}, message: 'Biometric data saved' },
    }).as('saveBiometric')

    fillBiometricsValid()
    cy.contains('button', 'Continue').click()
    cy.wait('@saveBiometric')
    cy.get('[aria-label="Skip Strava connection for now"]').click()
    cy.contains('Step 3 of 3').should('be.visible')
  }

  beforeEach(() => {
    cy.viewport(1280, 720)
    cy.loginWithBypass()
    cy.setupApiAuthCookies()
    cy.visit('/main/running/onboarding')
    advanceToStep3()
    // The radio input is covered by its parent <label> — click the label instead
    cy.contains('label', 'Yes, I have a race').click()
  })

  it('shows goal fields when "Yes, I have a race" is selected', () => {
    cy.get('input[placeholder="e.g. 30"]').should('be.visible')
    cy.contains('5K').should('be.visible')
    cy.contains('10K').should('be.visible')
    cy.contains('Half Marathon').should('be.visible')
    cy.contains('Marathon').should('be.visible')
  })

  it('clicking a quick distance button fills the distance input', () => {
    cy.contains('button', '5K').click()
    cy.get('input[placeholder="e.g. 30"]').should('have.value', '5')
  })

  it('clicking Marathon (exact match) fills 42.195 in distance input', () => {
    // Use exact text regex to avoid matching "Half Marathon" (cy.contains does substring match)
    cy.contains('button', /^Marathon$/).click()
    cy.get('input[placeholder="e.g. 30"]').should('have.value', '42.195')
  })

  it('shows "Save goal & go to dashboard" button when race goal is selected', () => {
    cy.contains('button', 'Save goal & go to dashboard').should('be.visible')
  })

  it('saves goal and redirects to dashboard when valid goal is set', () => {
    cy.intercept('POST', '/api/running/v1/onboarding/complete', {
      statusCode: 200,
      body: { data: {}, message: 'Onboarding complete' },
    }).as('completeOnboarding')

    cy.contains('button', /^Marathon$/).click()

    // Set a race date in the future
    cy.get('input[type="date"]').last().type('2027-04-15')

    cy.contains('button', 'Save goal & go to dashboard').click()

    cy.wait('@completeOnboarding')
      .its('request.body')
      .then((body) => {
        expect(body.goal_type).to.eq('race')
        expect(body.target_distance_m).to.eq(42195)
        expect(body.target_date).to.eq('2027-04-15')
      })

    cy.url().should('include', '/main/running/dashboard')
  })

  it('completes onboarding even if the API returns 500 (goal save failure is non-blocking)', () => {
    cy.intercept('POST', '/api/running/v1/onboarding/complete', {
      statusCode: 500,
      body: { error: 'Internal server error' },
    }).as('completeOnboardingFail')

    // Reset to "No race planned" so "Go to dashboard" button is shown
    cy.contains('label', 'No race planned yet').click()
    cy.contains('button', 'Go to dashboard').click()

    cy.wait('@completeOnboardingFail')
    // Per PRD spec: goal save failure is non-blocking — should still redirect
    cy.url().should('include', '/main/running/dashboard')
  })
})

// ---------------------------------------------------------------------------
// I. (app) layout guard — visiting (app) routes requires real Supabase session
// ---------------------------------------------------------------------------

describe('Running (app) layout — auth guard with real Supabase session', () => {
  it('setupApiAuthCookies provides a real Supabase session for (app) routes', () => {
    // The (app)/layout.jsx calls supabase.auth.getUser() directly (not requireAuth())
    // so it needs a real sb-{projectRef}-auth-token cookie — not just the bypass cookie.
    // setupApiAuthCookies sets exactly that cookie.
    // We stub the rt_users check to avoid needing a real onboarding_complete record.
    cy.setupApiAuthCookies()

    // Intercept the Supabase REST request for rt_users table that (app)/layout.jsx makes
    // after auth succeeds — respond as if onboarding is complete so we reach the page.
    cy.intercept('GET', '**/rest/v1/rt_users*', {
      statusCode: 200,
      body: [{ id: 'test-user-id', onboarding_complete: true }],
    }).as('rtUsersCheck')

    cy.visit('/main/running/dashboard')

    // If the auth guard passes (real session valid), we should NOT be on /login
    // and NOT be redirected to /onboarding.
    cy.url().should('not.include', '/login')
  })
})
