import '../app/globals.css'
import { withThemeByClassName } from '@storybook/addon-themes'

/** @type {import('@storybook/nextjs').Preview} */
const preview = {
  parameters: {
    nextjs: {
      appDirectory: true,
    },
    options: {
      storySort: {
        order: [
          'Base',
          ['Colors'],
          'Input',
          [
            'Button',
            ['Docs', 'Default', 'Secondary', 'Ghost', 'Outline', 'Link', 'Destructive'],
            'Field',
            ['Docs', '*'],
            'Input Field',
            ['Docs', 'Normal', 'Filled', 'Disabled', 'Error State', 'Affix', '*'],
            'Password Input',
            ['Docs', 'Basic', 'Disabled', 'Error State', 'Strength Rules', '*'],
            'Textarea',
            ['Docs', 'Normal', 'Filled', 'Disabled', 'Error State', '*'],
            'Select',
            ['Docs', 'Basic', 'Grouped', 'Disabled', 'Error State', '*'],
            'Checkbox',
            ['Docs', 'Basic', 'Group', 'Disabled', 'Error State', '*'],
            'Radio Group',
            ['Docs', 'Basic', 'Horizontal', 'Disabled', 'Error State', '*'],
            'Switch',
            ['Docs', 'Basic', 'With Label', 'Disabled', 'Error State', '*'],
            'SelectCard',
            ['Docs', 'Basic', 'Orientation', 'Disabled', '*'],
            'Slider',
            ['Docs', 'Basic', 'Disabled', 'Error State', '*'],
            'DatePicker',
            ['Docs', 'Basic', 'Disabled', 'Error State', '*'],
            'Pin Input',
            ['Docs', 'Basic', 'Disabled', 'Error State', '*'],
          ],
          'Accordion',
          ['Docs', 'Basic', 'Card', 'Multiple', 'Disabled', '*'],
          'Badge',
          ['Docs', 'Default', 'Size', 'Radius', 'With Icon', 'As Child', '*'],
          'Modal',
          ['Docs', 'Basic', 'Sizes', 'Animation', 'Controlled', 'Example', '*'],
          'Sheet',
          [
            'Docs',
            'Basic',
            'Sides',
            'Sizes',
            'Animation',
            'With Form',
            'With Footer Actions',
            'Controlled',
            '*',
          ],
          'Breadcrumb',
          ['Docs', 'Basic', 'Custom Separator', 'Collapsed', '*'],
          'Tooltip',
          [
            'Docs',
            'Basic',
            'Positions',
            'Alignment',
            'Animation',
            'Controlled',
            'Rich Content',
            '*',
          ],
          'HoverCard',
          ['Docs', 'Basic', 'Positions', 'Rich Content', 'Controlled', '*'],
          'Tabs',
          [
            'Docs',
            'Basic',
            'Variants',
            'Orientations',
            'With Icons',
            'Disabled Tabs',
            'Controlled',
            '*',
          ],
          'Skeleton',
          ['Docs', 'Basic', 'Animation', 'Presets', 'Composing', '*'],
          'Avatar',
          [
            'Docs',
            'Basic',
            'Sizes',
            'Shapes',
            'Fallback',
            'With Status',
            'Avatar Group',
            'Interactions',
            '*',
          ],
          'Toast',
          ['Docs', 'Basic', 'Variants', 'Positions', 'With Action', 'Animation', 'Controlled', '*'],
          'Sidebar',
          [
            'Docs',
            'Basic',
            'Size',
            'Collapsible',
            'Mobile Drawer',
            'Positions',
            'Nested Items',
            'Animation',
            'With Header & Footer',
            '*',
          ],
          'Layout',
          [
            'Card',
            [
              'Docs',
              'Card',
              [
                'Default',
                'Transparent',
                'Status',
                ['All Variants', 'Loading State', 'Error State', 'With Action', '*'],
                '*',
              ],
              'Usage',
              '*',
            ],
            'Section',
            [
              'Docs',
              'Overview',
              [
                'Single Section',
                'Multiple Sections',
                'No Breadcrumbs',
                'No Description',
                'No Page Header',
                'Transparent — Single Section',
                'Transparent — Multiple Sections',
                'Transparent — Mixed with Shell',
                'Loading State',
                'Empty State',
                'Error State',
                'Data State',
              ],
              [
                'Default',
                [
                  'With Button',
                  'Without Button',
                  'No Icon',
                  'Title Only',
                  'Description Only',
                  'Button Only',
                  'No Header',
                  'Header Only',
                ],
                'Transparent',
                [
                  'With Button',
                  'Without Button',
                  'No Icon',
                  'Title Only',
                  'Description Only',
                  'Button Only',
                  'No Header',
                  'Header Only',
                ],
              ],
            ],
          ],
          'EmptyState',
          [
            'Docs',
            'Basic',
            'Sizes',
            'Variants',
            'With Actions',
            'Without Icon',
            'Inside Table',
            'Inside Card',
            'Inside Dropdown',
            '*',
          ],
          'DropdownMenu',
          [
            'Docs',
            'Basic',
            'With Icons & Shortcuts',
            'Groups & Separators',
            'Checkbox Items',
            'Radio Group',
            'Nested Submenu',
            'Hover Trigger',
            'Disabled Items',
            '*',
          ],
          'Separator',
          ['Docs', 'Basic', 'Orientations', 'Variants', 'With Label', '*'],
          'Spinner',
          ['Docs', 'Basic', 'Sizes', 'Variants', 'Inside Button', 'Full Page', '*'],
          'Banner',
          [
            'Docs',
            'Basic',
            'Variants',
            'With Action',
            'Dismissible',
            'Without Icon',
            'Icon Position',
            'Compact',
            '*',
          ],
          'Popover',
          ['Docs', 'Basic', 'Positions', 'With Form', 'With Filter', 'Controlled', '*'],
          'Table',
          [
            'Docs',
            'Basic',
            'Sortable',
            'Searchable',
            'Selectable',
            'Expandable',
            'Pagination',
            'Loading State',
            'Empty State',
            'Full Featured',
            'Table in Popover',
            'Popover in Table',
            '*',
          ],
        ],
      },
    },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
  },
  decorators: [
    withThemeByClassName({
      themes: {
        light: '',
        dark: 'dark',
      },
      defaultTheme: 'light',
    }),
  ],
}

export default preview
