import '../app/globals.css'
import { withThemeByClassName } from '@storybook/addon-themes'

/** @type {import('@storybook/nextjs').Preview} */
const preview = {
  parameters: {
    nextjs: {
      appDirectory: true,
    },
    options: {
      storySort: {
        order: [
          'Accordion',
          ['Docs', 'Basic', 'Card', 'Multiple', 'Disabled', '*'],
          'Avatar',
          [
            'Docs',
            'Basic',
            'Sizes',
            'Shapes',
            'Fallback',
            'With Status',
            'Avatar Group',
            'Interactions',
            '*',
          ],
          'Badge',
          ['Docs', 'Default', 'Size', 'Radius', 'With Icon', 'As Child', '*'],
          'Banner',
          [
            'Docs',
            'Basic',
            'Variants',
            'With Action',
            'Dismissible',
            'Without Icon',
            'Icon Position',
            'Compact',
            '*',
          ],
          'Breadcrumb',
          ['Docs', 'Basic', 'Custom Separator', 'Collapsed', '*'],
          'Card',
          [
            'Docs',
            'Card',
            [
              'Default',
              'Transparent',
              'Status',
              ['All Variants', 'Loading State', 'Error State', 'With Action', '*'],
              '*',
            ],
            'Usage',
            '*',
          ],
          'Colors',
          ['*'],
          'Command',
          ['Docs', 'Basic', 'With Groups', 'With Shortcuts', 'Empty State', 'Controlled', '*'],
          'DropdownMenu',
          [
            'Docs',
            'Basic',
            'With Icons & Shortcuts',
            'Groups & Separators',
            'Checkbox Items',
            'Radio Group',
            'Nested Submenu',
            'Hover Trigger',
            'Disabled Items',
            '*',
          ],
          'EmptyState',
          [
            'Docs',
            'Basic',
            'Sizes',
            'Variants',
            'With Actions',
            'Without Icon',
            'Inside Table',
            'Inside Card',
            'Inside Dropdown',
            '*',
          ],
          'HoverCard',
          ['Docs', 'Basic', 'Positions', 'Rich Content', 'Controlled', '*'],
          'Input',
          [
            'Button',
            ['Docs', 'Default', 'Secondary', 'Ghost', 'Outline', 'Link', 'Destructive'],
            'Field',
            ['Docs', '*'],
            'Input Field',
            ['Docs', 'Normal', 'Filled', 'Disabled', 'Error State', 'Affix', '*'],
            'Password Input',
            ['Docs', 'Basic', 'Disabled', 'Error State', 'Strength Rules', '*'],
            'Textarea',
            ['Docs', 'Normal', 'Filled', 'Disabled', 'Error State', '*'],
            'Select',
            ['Docs', 'Basic', 'Grouped', 'Disabled', 'Error State', '*'],
            'Checkbox',
            ['Docs', 'Basic', 'Group', 'Disabled', 'Error State', '*'],
            'Radio Group',
            ['Docs', 'Basic', 'Horizontal', 'Disabled', 'Error State', '*'],
            'Switch',
            ['Docs', 'Basic', 'With Label', 'Disabled', 'Error State', '*'],
            'SelectCard',
            ['Docs', 'Basic', 'Orientation', 'Disabled', '*'],
            'Slider',
            ['Docs', 'Basic', 'Disabled', 'Error State', '*'],
            'DatePicker',
            ['Docs', 'Basic', 'Disabled', 'Error State', '*'],
            'Pin Input',
            ['Docs', 'Basic', 'Disabled', 'Error State', '*'],
          ],
          'Modal',
          ['Docs', 'Basic', 'Sizes', 'Animation', 'Controlled', 'Example', '*'],
          'NavMenu',
          [
            'Docs',
            'Basic',
            'With Mega Menu',
            'Nested Submenu',
            'Trigger Modes',
            'With Routing',
            'Controlled',
            '*',
          ],
          'Popover',
          ['Docs', 'Basic', 'Positions', 'With Form', 'With Filter', 'Controlled', '*'],
          'Separator',
          ['Docs', 'Basic', 'Orientations', 'Variants', 'With Label', '*'],
          'Sheet',
          [
            'Docs',
            'Basic',
            'Sides',
            'Sizes',
            'Animation',
            'With Form',
            'With Footer Actions',
            'Controlled',
            '*',
          ],
          'Sidebar',
          [
            'Docs',
            'Basic',
            'Size',
            'Collapsible',
            'Mobile Drawer',
            'Positions',
            'Nested Items',
            'Animation',
            'With Header & Footer',
            '*',
          ],
          'Skeleton',
          ['Docs', 'Basic', 'Animation', 'Presets', 'Composing', '*'],
          'Spinner',
          ['Docs', 'Basic', 'Sizes', 'Variants', 'Inside Button', 'Full Page', '*'],
          'Table',
          [
            'Docs',
            'Basic',
            'Sortable',
            'Searchable',
            'Selectable',
            'Expandable',
            'Pagination',
            'Loading State',
            'Empty State',
            'Full Featured',
            'Table in Popover',
            'Popover in Table',
            '*',
          ],
          'Tabs',
          [
            'Docs',
            'Basic',
            'Variants',
            'Orientations',
            'With Icons',
            'Disabled Tabs',
            'Controlled',
            '*',
          ],
          'Toast',
          ['Docs', 'Basic', 'Variants', 'Positions', 'With Action', 'Animation', 'Controlled', '*'],
          'Tooltip',
          [
            'Docs',
            'Basic',
            'Positions',
            'Alignment',
            'Animation',
            'Controlled',
            'Rich Content',
            '*',
          ],
        ],
      },
    },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
  },
  decorators: [
    withThemeByClassName({
      themes: {
        light: '',
        dark: 'dark',
      },
      defaultTheme: 'light',
    }),
  ],
}

export default preview
