import '../app/globals.css'
import '../app/tokens.css'
import { withThemeByClassName } from '@storybook/addon-themes'

/** @type {import('@storybook/nextjs').Preview} */
const preview = {
  parameters: {
    nextjs: {
      appDirectory: true,
    },
    options: {
      storySort: {
        order: [
          'Theme',
          ['Docs', 'Palette', 'Visual', '*'],
          'Accordion',
          ['Docs', 'Basic', 'Variant', 'Disabled', 'Default Value', 'Controlled', '*'],
          'Avatar',
          [
            'Docs',
            'Basic',
            'Sizes',
            'Shapes',
            ['Circle', 'Square', '*'],
            'Fallback',
            ['Initials', 'Icon', 'Custom Color', '*'],
            'With Status',
            ['Online', 'Offline', 'Busy', 'Away', 'Ping', '*'],
            'Avatar Group',
            'Interactions',
            ['Clickable', 'With Popover', '*'],
            '*',
          ],
          'Badge',
          [
            'Docs',
            'Variant',
            ['Default', 'Secondary', 'Destructive', 'Outline', '*'],
            'Size',
            'Radius',
            'With Icon',
            ['Icon Left', 'Icon Right', '*'],
            'As Child',
            '*',
          ],
          'Banner',
          [
            'Docs',
            'Basic',
            'Variants',
            ['Info', 'Success', 'Warning', 'Danger', '*'],
            'With Action',
            'Dismissible',
            'Without Icon',
            'Icon Position',
            'Compact',
            '*',
          ],
          'Breadcrumb',
          ['Docs', 'Basic', 'Custom Separator', 'Collapsed', '*'],
          'Card',
          [
            'Docs',
            'Card',
            [
              'Default',
              'Transparent',
              'Status',
              ['All Variants', 'Loading State', 'Error State', 'With Action', '*'],
              'Bordered prop',
              'Shadow prop',
              '*',
            ],
            'Usage',
            '*',
          ],
          'Collapsible',
          ['Docs', 'Basic', 'asChild trigger', '*'],
          'Colors',
          ['*'],
          'Command',
          ['Docs', 'Basic', 'With Groups', 'With Shortcuts', 'Empty State', 'Controlled', '*'],
          'DropdownMenu',
          [
            'Docs',
            'Basic',
            'With Icons & Shortcuts',
            'Groups & Separators',
            'Checkbox Items',
            'Radio Group',
            'Nested Submenu',
            'Hover Trigger',
            'Disabled Items',
            '*',
          ],
          'EmptyState',
          [
            'Docs',
            'Basic',
            'Sizes',
            'Variants',
            'With Actions',
            'Without Icon',
            'Inside Table',
            'Inside Card',
            'Inside Dropdown',
            '*',
          ],
          'HoverCard',
          ['Docs', 'Basic', 'Positions', 'Rich Content', 'Controlled', '*'],
          'Input',
          [
            'Attachment',
            [
              'Docs',
              'Basic',
              'Trigger Types',
              'Custom Label',
              'Constraints',
              'Status',
              ['Idle', 'Uploading', 'Done', 'Error State', '*'],
              '*',
            ],
            'Button',
            ['Docs', 'Default', 'Secondary', 'Ghost', 'Outline', 'Link', 'Destructive', '*'],
            'Checkbox',
            ['Docs', 'Basic', 'Group', 'Disabled', 'Error State', '*'],
            'ColorPicker',
            ['Docs', 'Basic', 'With Presets', 'Uncontrolled', 'Disabled', 'Error State', '*'],
            'Combobox',
            [
              'Docs',
              'Basic',
              'Multiple',
              'Groups',
              'Trigger Type',
              'Async Search',
              'Creatable',
              'Disabled',
              'Error State',
              '*',
            ],
            'DatePicker',
            ['Docs', 'Basic', 'Disabled', 'Error State', '*'],
            'Field',
            ['Docs', '*'],
            'Input Field',
            ['Docs', 'Normal', 'Filled', 'Disabled', 'Error State', 'Affix', '*'],
            'Password Input',
            ['Docs', 'Basic', 'Disabled', 'Error State', 'Strength Rules', '*'],
            'Pin Input',
            ['Docs', 'Basic', 'Disabled', 'Error State', '*'],
            'Radio Group',
            ['Docs', 'Basic', 'Horizontal', 'Disabled', 'Error State', '*'],
            'RatingInput',
            ['Docs', 'Basic', 'Style', 'Allow Half', 'Read Only', 'Disabled', 'Error State', '*'],
            'Select',
            ['Docs', 'Basic', 'Grouped', 'Disabled', 'Error State', '*'],
            'SelectCard',
            ['Docs', 'Basic', 'Orientation', 'Disabled', '*'],
            'Slider',
            ['Docs', 'Basic', 'Disabled', 'Error State', '*'],
            'Switch',
            ['Docs', 'Basic', 'With Label', 'Disabled', 'Error State', '*'],
            'Textarea',
            ['Docs', 'Normal', 'Filled', 'Disabled', 'Error State', '*'],
            'TimePicker',
            ['Docs', 'Basic', 'Fields', 'Step', 'Icon', 'Disabled', 'Error State', '*'],
            '*',
          ],
          'Modal',
          ['Docs', 'Basic', 'Sizes', 'Animation', 'Controlled', 'Example', '*'],
          'NavMenu',
          [
            'Docs',
            'Basic',
            ['With Icon', 'Without Icon', '*'],
            'Trigger Modes',
            ['Trigger Hover', 'Trigger Click', '*'],
            'Menu',
            [
              '2 Columns',
              '3 Columns',
              'Active Item',
              'Simple Nested Submenu',
              'Mega Menu Nested Submenu',
              'With Routing',
              '*',
            ],
            'Controlled',
            '*',
          ],
          'Pagination',
          [
            'Docs',
            'Basic',
            ['Icon + Text', 'Icon Only', '*'],
            'Variants',
            ['Full', 'Center', 'Left', 'Right', '*'],
            'States',
            '*',
          ],
          'Popover',
          [
            'Docs',
            'Basic',
            'Positions',
            ['Side', 'Align', '*'],
            'With Form',
            'With Filter',
            'Controlled',
            '*',
          ],
          'ScrollArea',
          ['Docs', 'Basic', ['Vertical (default)', 'Horizontal', 'Both', '*'], '*'],
          'Separator',
          ['Docs', 'Basic', 'Orientations', 'Variants', 'With Label', '*'],
          'Sheet',
          [
            'Docs',
            'Basic',
            ['Uncontrolled', 'With Footer Close', 'Default Open', '*'],
            'Sides',
            ['Right', 'Left', 'Top', 'Bottom', '*'],
            'Sizes',
            ['Sm', 'Default', 'Lg', 'Full', '*'],
            'Animation',
            ['Slide', 'None', '*'],
            'With Form',
            'With Footer Actions',
            'Controlled',
            '*',
          ],
          'Sidebar',
          [
            'Docs',
            'Basic',
            'Size',
            ['Sm', 'Md', 'Lg', 'Mixed', '*'],
            'Collapsible',
            'Mobile Drawer',
            'Positions',
            ['Left', 'Right', '*'],
            'Nested Items',
            ['2 Levels', '3 Levels', '4 Levels', '*'],
            'Animation',
            ['Sub — Slide', 'Sub — None', 'Collapse — Slide', 'Collapse — None', '*'],
            'With Header & Footer',
            '*',
          ],
          'Skeleton',
          [
            'Docs',
            'Basic',
            'Animation',
            ['Pulse', 'Wave', 'None', '*'],
            'Presets',
            'Composing',
            '*',
          ],
          'Spinner',
          [
            'Docs',
            'Basic',
            'Sizes',
            'Variants',
            ['Default', 'Muted', 'White', 'Custom', '*'],
            'Inside Button',
            'Full Page',
            '*',
          ],
          'State',
          ['Docs', 'Variants', 'With Action', 'Custom Icon', 'Loading', '*'],
          'Table',
          [
            'Docs',
            'Basic',
            'Sortable',
            'Searchable',
            'Selectable',
            'Expandable',
            'Pagination',
            'Loading State',
            'Empty State',
            'Full Featured',
            'Table in Popover',
            'Popover in Table',
            '*',
          ],
          'Tabs',
          [
            'Docs',
            'Basic',
            'Variants',
            ['Underline', 'Pill', '*'],
            'Sizes',
            [
              'Underline / Xs',
              'Underline / Sm',
              'Underline / Base',
              'Underline / Lg',
              'Underline / Xl',
              'Pill / Xs',
              'Pill / Sm',
              'Pill / Base',
              'Pill / Lg',
              'Pill / Xl',
              '*',
            ],
            'Orientations',
            [
              'Horizontal / Underline',
              'Horizontal / Pill',
              'Vertical / Underline',
              'Vertical / Pill',
              '*',
            ],
            'With Icons',
            ['Underline', 'Pill', '*'],
            'Disabled Tabs',
            ['Underline', 'Pill', '*'],
            'Controlled',
            ['Underline', 'Pill', '*'],
            '*',
          ],
          'Toast',
          [
            'Docs',
            'Basic',
            'Variants',
            ['Default', 'Info', 'Success', 'Warning', 'Danger', '*'],
            'Positions',
            'With Action',
            ['Inline', 'Stacked Left', 'Stacked Right', '*'],
            'Animation',
            ['Slide Fade', 'Slide', 'Fade', 'None', 'Duration', '*'],
            'Controlled',
            '*',
          ],
          'Tooltip',
          [
            'Docs',
            'Basic',
            'Variants',
            ['Default', 'Info', 'Success', 'Warning', 'Danger', '*'],
            'Positions',
            'Alignment',
            'Animation',
            ['Fade', 'Zoom', 'Slide Up', 'Slide Down', 'None', 'Duration', '*'],
            'Controlled',
            'Rich Content',
            '*',
          ],
        ],
      },
    },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
  },
  decorators: [
    withThemeByClassName({
      themes: {
        light: '',
        dark: 'dark',
      },
      defaultTheme: 'light',
    }),
  ],
}

export default preview
