// Generated by Cypress Author — 2026-06-03
// Issue #119: Strava broken connection — UI/banner/settings tests

import { TEST_IDS } from '../../../fixtures/test-ids.js'
import { ROUTES } from '../../../fixtures/routes.js'
import { RUNNING_ENDPOINTS } from '../../../fixtures/endpoints.js'

const IDS = TEST_IDS.running_strava_connection
const DASHBOARD_URL = ROUTES.running_dashboard
const SETTINGS_URL = ROUTES.running_settings

const stubRtUsers = () => {
  cy.intercept('GET', '**/rest/v1/rt_users*', {
    statusCode: 200,
    body: [{ id: 'test-user-id', onboarding_complete: true }],
  }).as('rtUsersCheck')
}

const stubStravaStatus = (overrides = {}) => {
  cy.intercept('GET', `**${RUNNING_ENDPOINTS.STRAVA_STATUS}**`, {
    statusCode: 200,
    body: {
      data: {
        connected: true,
        athlete_id: 12345,
        last_sync_at: null,
        needs_reconnect: false,
        ...overrides,
      },
      message: 'OK',
    },
  }).as('stravaStatus')
}

describe('Strava Reconnect Banner — visibility on dashboard', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
  })

  it('banner visible when needs_reconnect is true → banner appears', () => {
    stubStravaStatus({ needs_reconnect: true })
    cy.visit(DASHBOARD_URL)
    cy.wait('@stravaStatus')
    cy.get(`#${IDS.disconnect_banner}`).should('be.visible')
  })

  it('needs_reconnect is false → banner does not appear', () => {
    stubStravaStatus({ needs_reconnect: false })
    cy.visit(DASHBOARD_URL)
    cy.wait('@stravaStatus')
    cy.get(`#${IDS.disconnect_banner}`).should('not.exist')
  })

  it('needs_reconnect is true → banner has no dismiss or close button', () => {
    stubStravaStatus({ needs_reconnect: true })
    cy.visit(DASHBOARD_URL)
    cy.wait('@stravaStatus')
    cy.get(`#${IDS.disconnect_banner}`).within(() => {
      cy.get('[aria-label="close"]').should('not.exist')
      cy.get('[aria-label="Close"]').should('not.exist')
      cy.get('[aria-label="dismiss"]').should('not.exist')
    })
  })

  it('needs_reconnect is true → Reconnect Strava CTA button is visible', () => {
    stubStravaStatus({ needs_reconnect: true })
    cy.visit(DASHBOARD_URL)
    cy.wait('@stravaStatus')
    cy.get(`#${IDS.reconnect_btn}`).should('be.visible').and('contain.text', 'Reconnect Strava')
  })
})

describe('Strava Connection — Settings page states', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
    stubRtUsers()
  })

  it('connected=true, needs_reconnect=true → broken state is visible', () => {
    stubStravaStatus({ connected: true, needs_reconnect: true })
    cy.visit(SETTINGS_URL)
    cy.wait('@stravaStatus')
    cy.get(`#${IDS.settings_broken_state}`).should('be.visible')
    cy.get(`#${IDS.reconnect_btn_settings}`).should('be.visible')
  })

  it('connected=true, needs_reconnect=false → connected state is visible', () => {
    stubStravaStatus({ connected: true, needs_reconnect: false })
    cy.visit(SETTINGS_URL)
    cy.wait('@stravaStatus')
    cy.get(`#${IDS.settings_connected_state}`).should('be.visible')
  })

  it('connected=false → disconnected state is visible', () => {
    stubStravaStatus({ connected: false, needs_reconnect: false })
    cy.visit(SETTINGS_URL)
    cy.wait('@stravaStatus')
    cy.get(`#${IDS.settings_disconnected_state}`).should('be.visible')
  })

  it('loading skeleton renders before status resolves', () => {
    cy.intercept('GET', `**${RUNNING_ENDPOINTS.STRAVA_STATUS}**`, (req) => {
      req.reply((res) => {
        res.setDelay(600)
        res.send({
          statusCode: 200,
          body: {
            data: {
              connected: false,
              athlete_id: null,
              last_sync_at: null,
              needs_reconnect: false,
            },
            message: 'OK',
          },
        })
      })
    }).as('stravaStatusDelayed')

    cy.visit(SETTINGS_URL)
    cy.get(`#${IDS.settings_loading}`).should('exist')
    cy.wait('@stravaStatusDelayed')
    cy.get(`#${IDS.settings_loading}`).should('not.exist')
  })
})
