// Generated by Cypress Author — 2026-06-03
// Issue #119: Strava broken connection — API-level tests

import { RUNNING_ENDPOINTS } from '../../../fixtures/endpoints.js'

const STRAVA_STATUS = RUNNING_ENDPOINTS.STRAVA_STATUS
const SYNC_WEBHOOK = RUNNING_ENDPOINTS.SYNC_WEBHOOK

describe('Strava Status API — GET (authenticated)', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 with correct response shape', () => {
    cy.apiRequestWithSession('GET', STRAVA_STATUS, {
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('message', 'OK')
      expect(res.body).to.have.property('data')

      const { data } = res.body
      expect(data).to.have.property('connected').that.is.a('boolean')
      expect(data).to.have.property('needs_reconnect').that.is.a('boolean')

      const athleteId = data.athlete_id
      expect(athleteId === null || typeof athleteId === 'number').to.be.true

      const lastSync = data.last_sync_at
      expect(lastSync === null || typeof lastSync === 'string').to.be.true
    })
  })

  it('needs_reconnect defaults to false when Strava not connected', () => {
    cy.apiRequestWithSession('GET', STRAVA_STATUS, {
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(200)
      // Test user has no Strava connected — needs_reconnect must be false (not true)
      expect(res.body.data.needs_reconnect).to.eq(false)
    })
  })
})

describe('Strava Status API — GET (unauthenticated)', () => {
  beforeEach(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
  })

  it('returns 401 with error field when no session cookie', () => {
    cy.request({
      method: 'GET',
      url: STRAVA_STATUS,
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(401)
      expect(res.body).to.have.property('error')
    })
  })
})

describe('Strava Webhook API — HMAC signature verification', () => {
  const webhookPayload = {
    aspect_type: 'create',
    object_id: 999999,
    object_type: 'activity',
    owner_id: 1,
  }

  it('returns 401 when x-hub-signature header is missing', () => {
    cy.request({
      method: 'POST',
      url: SYNC_WEBHOOK,
      headers: { 'Content-Type': 'application/json' },
      body: webhookPayload,
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(401)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 401 when x-hub-signature has wrong value', () => {
    cy.request({
      method: 'POST',
      url: SYNC_WEBHOOK,
      headers: {
        'Content-Type': 'application/json',
        'x-hub-signature':
          'sha256=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      },
      body: webhookPayload,
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(401)
      expect(res.body).to.have.property('error')
    })
  })

  it('returns 401 when x-hub-signature format is invalid', () => {
    cy.request({
      method: 'POST',
      url: SYNC_WEBHOOK,
      headers: {
        'Content-Type': 'application/json',
        'x-hub-signature': 'not-a-valid-signature-format',
      },
      body: webhookPayload,
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(401)
      expect(res.body).to.have.property('error')
    })
  })
})
