import FieldContent from '../Field/FieldContent'
import FieldLabel from '../Field/FieldLabel'
import FieldDescription from '../Field/FieldDescription'
import Textarea from './Textarea'

/** @type {import('@storybook/nextjs').Meta} */
const meta = {
  title: 'Input/Textarea/Disabled',
}

export default meta

const BestPractices = ({ items }) => (
  <div className="flex flex-col gap-8 w-full max-w-2xl">
    {items.map(({ heading, cards }) => (
      <div key={heading}>
        <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">
          {heading}
        </p>
        <div className="flex flex-col gap-3">
          {cards.map(({ title, body }) => (
            <div
              key={title}
              className="flex gap-3 p-4 rounded-lg border border-violet-100 bg-violet-50"
            >
              <span className="mt-0.5 shrink-0 size-4 rounded-full bg-violet-500 flex items-center justify-center text-white text-[10px] font-bold">
                ✓
              </span>
              <div>
                <p className="text-xs font-semibold text-violet-800 mb-0.5">{title}</p>
                <p className="text-xs text-violet-700 leading-relaxed">{body}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    ))}
  </div>
)

export const Disabled = {
  name: 'Disabled',
  render: () => (
    <div className="flex flex-col gap-6 w-full">
      <p className="text-sm text-gray-500 leading-relaxed max-w-2xl">
        The disabled state dims the textarea and blocks all interaction including resizing. Prefer
        setting <code className="font-mono bg-gray-100 px-1 rounded text-xs">disabled</code> on{' '}
        <code className="font-mono bg-gray-100 px-1 rounded text-xs">FieldContent</code> so the
        label is also dimmed. Use{' '}
        <code className="font-mono bg-gray-100 px-1 rounded text-xs">variant="disabled"</code>{' '}
        directly only for standalone usage.
      </p>

      <div className="flex flex-col gap-2">
        <span className="text-xs text-gray-400">
          via FieldContent disabled — label and description also dimmed
        </span>
        <div className="p-4 bg-gray-50 border border-gray-200 rounded-lg w-80">
          <FieldContent disabled>
            <FieldLabel>Internal notes</FieldLabel>
            <FieldDescription>Auto-generated — cannot be edited manually.</FieldDescription>
            <Textarea rows={3} defaultValue="Generated by the system on 12 Jul 2026." />
          </FieldContent>
        </div>
      </div>

      <div className="flex flex-col gap-2">
        <span className="text-xs text-gray-400">
          standalone variant="disabled" — no FieldContent
        </span>
        <div className="p-4 bg-gray-50 border border-gray-200 rounded-lg w-80">
          <Textarea rows={3} variant="disabled" defaultValue="Cannot be edited." />
        </div>
      </div>

      <BestPractices
        items={[
          {
            heading: 'When to use',
            cards: [
              {
                title:
                  'Disable a textarea when the content is system-generated or read-only in the current context',
                body: 'Auto-generated summaries, audit logs, or computed descriptions should be visible but non-editable. Disabling makes the read-only state explicit rather than hiding the field.',
              },
            ],
          },
          {
            heading: 'When not to use',
            cards: [
              {
                title:
                  "Don't disable a textarea the user needs to fill — use conditional visibility instead",
                body: 'A disabled field implies it exists but cannot be used right now, which is confusing if the user must fill it to proceed. If the field is conditionally editable, show it enabled only when the condition is met.',
              },
            ],
          },
          {
            heading: 'Accessibility',
            cards: [
              {
                title:
                  'Prefer FieldContent disabled over variant="disabled" for full a11y coverage',
                body: 'Setting disabled on FieldContent flows the disabled attribute to the Textarea and dims the FieldLabel. Screen readers then correctly announce the field as disabled without extra manual wiring.',
              },
            ],
          },
          {
            heading: 'Advice',
            cards: [
              {
                title: 'Add a FieldDescription explaining why the field is disabled',
                body: 'Users seeing a dimmed textarea often wonder if it is a bug. A short FieldDescription like "Auto-generated — cannot be edited manually" removes that confusion and builds trust in the UI.',
              },
            ],
          },
        ]}
      />

      <pre className="bg-gray-900 rounded-lg px-5 py-4 text-xs text-green-400 overflow-x-auto leading-relaxed w-full max-w-2xl">
        <code>{`{/* Via FieldContent — recommended */}
<FieldContent disabled>
  <FieldLabel>Internal notes</FieldLabel>
  <FieldDescription>Auto-generated — cannot be edited manually.</FieldDescription>
  <Textarea rows={3} defaultValue="Generated by the system." />
</FieldContent>

{/* Standalone */}
<Textarea rows={3} variant="disabled" defaultValue="Cannot be edited." />`}</code>
      </pre>
    </div>
  ),
}
