// Generated by Cypress Author — 2026-05-23
// Covers: Running Dashboard API endpoint
//   GET /api/running/v1/dashboard — happy path, response shape, 401

// ---------------------------------------------------------------------------
// A. GET /api/running/v1/dashboard — Authenticated
// ---------------------------------------------------------------------------

describe('Running Dashboard API — GET /api/running/v1/dashboard', () => {
  // Use beforeEach because cookies are cleared between tests by Cypress session management
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  // Happy path — returns 200 with expected top-level shape
  it('returns 200 with valid session', () => {
    cy.apiRequestWithSession('GET', '/api/running/v1/dashboard').then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('data')
    })
  })

  // Response shape — weekly_stats block
  it('response data contains weekly_stats with current and prev blocks', () => {
    cy.apiRequestWithSession('GET', '/api/running/v1/dashboard').then((res) => {
      expect(res.status).to.eq(200)
      const { data } = res.body
      expect(data).to.have.property('weekly_stats')
      expect(data.weekly_stats).to.have.property('current')
      expect(data.weekly_stats).to.have.property('prev')

      // current block must have the four stat fields
      const { current } = data.weekly_stats
      expect(current).to.have.property('distance_m')
      expect(current).to.have.property('duration_sec')
      expect(current).to.have.property('count')
      expect(current).to.have.property('avg_pace_sec_per_km')
    })
  })

  // Response shape — training_load block
  it('response data contains training_load with acwr, acute_load_7d, chronic_load_28d, status', () => {
    cy.apiRequestWithSession('GET', '/api/running/v1/dashboard').then((res) => {
      expect(res.status).to.eq(200)
      const { training_load } = res.body.data
      expect(training_load).to.have.property('acwr')
      expect(training_load).to.have.property('acute_load_7d')
      expect(training_load).to.have.property('chronic_load_28d')
      expect(training_load).to.have.property('status')
      // status must be one of the documented values
      expect(training_load.status).to.be.oneOf(['no_data', 'low', 'optimal', 'caution', 'danger'])
    })
  })

  // Response shape — recent_activities is an array
  it('response data contains recent_activities as an array', () => {
    cy.apiRequestWithSession('GET', '/api/running/v1/dashboard').then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body.data).to.have.property('recent_activities')
      expect(res.body.data.recent_activities).to.be.an('array')
    })
  })

  // Response shape — calendar_activities is an array
  it('response data contains calendar_activities as an array', () => {
    cy.apiRequestWithSession('GET', '/api/running/v1/dashboard').then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body.data).to.have.property('calendar_activities')
      expect(res.body.data.calendar_activities).to.be.an('array')
    })
  })

  // Response shape — health_today block
  it('response data contains health_today with logged boolean', () => {
    cy.apiRequestWithSession('GET', '/api/running/v1/dashboard').then((res) => {
      expect(res.status).to.eq(200)
      const { health_today } = res.body.data
      expect(health_today).to.have.property('logged')
      expect(health_today.logged).to.be.a('boolean')
    })
  })

  // Numeric types — distance_m and duration_sec must be integers
  it('weekly_stats current distance_m and duration_sec are integers', () => {
    cy.apiRequestWithSession('GET', '/api/running/v1/dashboard').then((res) => {
      const { current } = res.body.data.weekly_stats
      expect(Number.isInteger(current.distance_m)).to.eq(true)
      expect(Number.isInteger(current.duration_sec)).to.eq(true)
    })
  })
})

// ---------------------------------------------------------------------------
// B. GET /api/running/v1/dashboard — Unauthenticated (isolated describe, no beforeEach auth)
// ---------------------------------------------------------------------------

describe('Running Dashboard API — Unauthenticated access (no session)', () => {
  beforeEach(() => {
    // Ensure no auth cookies carry over from other describe blocks
    cy.clearCookies()
    cy.clearLocalStorage()
  })

  it('returns 401 with no session cookie', () => {
    cy.request({
      method: 'GET',
      url: '/api/running/v1/dashboard',
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(401)
      expect(res.body).to.have.property('error', 'Unauthorized')
    })
  })
})
