// Generated by Cypress Author — 2026-05-25
// Covers: Running Tracker Gear API
//   GET /api/running/v1/gear — authenticated, response shape, field presence
//   PATCH /api/running/v1/gear — update gear settings, auth guard
//
// AUTH STRATEGY:
//   cy.setupApiAuthCookies() — real Supabase session required (app layout
//   calls supabase.auth.getUser() directly; bypass cookie alone is insufficient).

describe('Running Gear API — GET /api/running/v1/gear', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 with data array when authenticated', () => {
    cy.request({
      method: 'GET',
      url: '/api/running/v1/gear',
    }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('data')
      expect(res.body.data).to.be.an('array')
    })
  })

  it('each gear item has required fields: id, name, distance_m, retired', () => {
    cy.request({
      method: 'GET',
      url: '/api/running/v1/gear',
    }).then((res) => {
      expect(res.status).to.eq(200)
      const items = res.body.data
      if (items.length === 0) {
        // No gear synced — skip field check (not a test failure)
        cy.log('No gear items found — skipping field assertions')
        return
      }
      items.forEach((item) => {
        expect(item).to.have.property('id')
        expect(item).to.have.property('name')
        expect(item).to.have.property('distance_m')
        expect(item).to.have.property('retired')
      })
    })
  })

  it('each gear item has optional limit fields: category, retirement_km, notification_distance_m', () => {
    cy.request({
      method: 'GET',
      url: '/api/running/v1/gear',
    }).then((res) => {
      expect(res.status).to.eq(200)
      const items = res.body.data
      if (items.length === 0) {
        cy.log('No gear items found — skipping field assertions')
        return
      }
      items.forEach((item) => {
        // Fields may be null but must exist as keys
        expect(item).to.have.any.keys('category', 'retirement_km', 'notification_distance_m')
      })
    })
  })
})

describe('Running Gear API — GET /api/running/v1/gear — Unauthenticated', () => {
  beforeEach(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
  })

  it('returns 401 when unauthenticated', () => {
    cy.request({
      method: 'GET',
      url: '/api/running/v1/gear',
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(401)
    })
  })
})

describe('Running Gear API — PATCH /api/running/v1/gear', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 with updated gear object when patching category and retirement_km', () => {
    // First fetch to get a real gear id
    cy.request({
      method: 'GET',
      url: '/api/running/v1/gear',
    }).then((getRes) => {
      expect(getRes.status).to.eq(200)
      const items = getRes.body.data
      if (items.length === 0) {
        cy.log('No gear items available — skipping PATCH test')
        return
      }

      const gearId = items[0].id
      cy.request({
        method: 'PATCH',
        url: '/api/running/v1/gear',
        body: { id: gearId, category: 'daily', retirement_km: 800 },
      }).then((patchRes) => {
        expect(patchRes.status).to.eq(200)
        expect(patchRes.body).to.have.property('data')
        expect(patchRes.body.data).to.have.property('id', gearId)
      })
    })
  })
})

describe('Running Gear API — PATCH /api/running/v1/gear — Unauthenticated', () => {
  beforeEach(() => {
    cy.clearCookies()
    cy.clearLocalStorage()
  })

  it('returns 401 when unauthenticated on PATCH', () => {
    cy.request({
      method: 'PATCH',
      url: '/api/running/v1/gear',
      body: { id: 'some-id', category: 'tempo' },
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(401)
    })
  })
})
