// Generated by Cypress Author — 2026-05-25
// Covers: Running Tracker Gear UI (ShoeRotation component on Dashboard)
//   Rendered inside /main/running/dashboard — ShoeRotation is always mounted
//   on the dashboard page (not a separate route).
//
// AUTH STRATEGY:
//   cy.setupApiAuthCookies() — real Supabase session required.
//   stubRtUsers() — stubs rt_users onboarding check so (app)/layout lets us through.
//   stubDashboardMinimal() — stubs GET /api/running/v1/dashboard with minimal data
//     so the rest of the dashboard renders quickly and ShoeRotation can mount.
//   GET /api/running/v1/gear is intercepted per-test with fixture data.

import constants from '../../../fixtures/app-constants.json'

const GEAR_IDS = constants.test_ids.running_gear

/** Stub rt_users to report onboarding complete. */
const stubRtUsers = () => {
  cy.intercept('GET', '**/rest/v1/rt_users*', {
    statusCode: 200,
    body: [{ id: 'test-user-id', onboarding_complete: true }],
  }).as('rtUsersCheck')
}

/** Minimal dashboard stub so the page renders without failing. */
const stubDashboardMinimal = () => {
  cy.intercept('GET', '/api/running/v1/dashboard', {
    statusCode: 200,
    body: {
      data: {
        weekly_stats: {
          current: { distance_m: 0, duration_sec: 0, count: 0, avg_pace_sec_per_km: null },
          prev: { distance_m: 0, duration_sec: 0, count: 0, avg_pace_sec_per_km: null },
        },
        training_load: {
          acwr: null,
          acute_load_7d: null,
          chronic_load_28d: null,
          status: 'no_data',
        },
        recent_activities: [],
        calendar_activities: [],
        health_today: { logged: false, data: null },
      },
    },
  }).as('getDashboardMinimal')
}

/** Stub auto-sync so page doesn't fire a real POST on mount. */
const stubSyncStrava = () => {
  cy.intercept('POST', '/api/running/v1/auth/strava/sync', {
    statusCode: 200,
    body: { synced: 0 },
  }).as('syncStrava')
}

// ---------------------------------------------------------------------------
// A. Loading skeleton
// ---------------------------------------------------------------------------

describe('Running Gear UI — Loading skeleton', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  it('shows #gearLoadingSkeleton while gear fetch is pending', () => {
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboardMinimal()
    stubSyncStrava()

    cy.intercept('GET', '/api/running/v1/gear', (req) => {
      req.reply((res) => {
        res.setDelay(1000)
        res.send({ statusCode: 200, body: { data: [] } })
      })
    }).as('getGearDelayed')

    cy.viewport(1280, 720)
    cy.visit('/main/running/dashboard')
    cy.wait('@getDashboardMinimal')

    cy.get(`#${GEAR_IDS.loading_skeleton}`).should('exist')
  })
})

// ---------------------------------------------------------------------------
// B. Happy path — active gear renders
// ---------------------------------------------------------------------------

describe('Running Gear UI — Happy path', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.viewport(1280, 720)
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboardMinimal()
    stubSyncStrava()

    cy.intercept('GET', '/api/running/v1/gear', {
      statusCode: 200,
      body: {
        data: [
          {
            id: 'gear-1',
            name: 'Nike Vaporfly 3',
            distance_m: 320000,
            retired: false,
            category: 'race',
            retirement_km: 800,
            notification_distance_m: 500000,
          },
          {
            id: 'gear-2',
            name: 'ASICS Gel-Nimbus 25',
            distance_m: 210000,
            retired: false,
            category: 'daily',
            retirement_km: null,
            notification_distance_m: null,
          },
        ],
      },
    }).as('getGear')

    cy.visit('/main/running/dashboard')
    cy.wait('@getDashboardMinimal')
    cy.wait('@getGear')
  })

  it('renders #gearList with active shoes', () => {
    cy.get(`#${GEAR_IDS.list}`).should('exist')
    cy.get(`#${GEAR_IDS.list}`).find('li').should('have.length', 2)
  })

  it('#gearCard shows shoe name', () => {
    cy.get(`#${GEAR_IDS.gear_card}`).first().should('contain', 'Nike Vaporfly 3')
  })

  it('#gearCard shows distance in km with 2 decimal places', () => {
    // 320000m → 320.00 km
    cy.get(`#${GEAR_IDS.gear_card}`).first().should('contain', '320.00')
  })
})

// ---------------------------------------------------------------------------
// C. Empty state — no shoes synced
// ---------------------------------------------------------------------------

describe('Running Gear UI — Empty state', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.viewport(1280, 720)
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboardMinimal()
    stubSyncStrava()

    cy.intercept('GET', '/api/running/v1/gear', {
      statusCode: 200,
      body: { data: [] },
    }).as('getGearEmpty')

    cy.visit('/main/running/dashboard')
    cy.wait('@getDashboardMinimal')
    cy.wait('@getGearEmpty')
  })

  it('shows "No shoes synced yet" when gear list is empty', () => {
    cy.get(`#${GEAR_IDS.page}`).scrollIntoView()
    cy.get(`#${GEAR_IDS.page}`).contains('No shoes synced yet').should('be.visible')
  })

  it('does not render #gearList when no gear', () => {
    cy.get(`#${GEAR_IDS.list}`).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// D. Error state — API 500
// ---------------------------------------------------------------------------

describe('Running Gear UI — Error state', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.viewport(1280, 720)
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboardMinimal()
    stubSyncStrava()

    cy.intercept('GET', '/api/running/v1/gear', {
      statusCode: 500,
      body: { error: 'Internal server error' },
    }).as('getGearError')

    cy.visit('/main/running/dashboard')
    cy.wait('@getDashboardMinimal')
    cy.wait('@getGearError')
  })

  it('shows #gearError on API 500', () => {
    cy.get(`#${GEAR_IDS.error}`, { timeout: 8000 }).should('be.visible')
  })

  it('shows a retry button in error state', () => {
    cy.get(`#${GEAR_IDS.error}`).contains('Try again').should('be.visible')
  })

  it('does not show #gearLoadingSkeleton after error resolves', () => {
    cy.get(`#${GEAR_IDS.loading_skeleton}`).should('not.exist')
  })
})

// ---------------------------------------------------------------------------
// E. Limit tabs — Strava-only gear
// ---------------------------------------------------------------------------

describe('Running Gear UI — Limit tabs: Strava only', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.viewport(1280, 720)
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboardMinimal()
    stubSyncStrava()

    cy.intercept('GET', '/api/running/v1/gear', {
      statusCode: 200,
      body: {
        data: [
          {
            id: 'gear-strava-only',
            name: 'Brooks Ghost 15',
            distance_m: 150000,
            retired: false,
            category: null,
            retirement_km: null,
            notification_distance_m: 500000,
          },
        ],
      },
    }).as('getGearStravaOnly')

    cy.visit('/main/running/dashboard')
    cy.wait('@getDashboardMinimal')
    cy.wait('@getGearStravaOnly')
  })

  it('Strava tab shows "500.00 km" when notification_distance_m=500000', () => {
    cy.get(`#${GEAR_IDS.gear_card}`).should('contain', '500.00 km')
  })

  it('Manual tab shows "—" when retirement_km is null', () => {
    cy.get(`#${GEAR_IDS.gear_card}`).should('contain', 'Manual · —')
  })
})

// ---------------------------------------------------------------------------
// F. Limit tabs — both Manual and Strava set
// ---------------------------------------------------------------------------

describe('Running Gear UI — Limit tabs: Manual and Strava', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.viewport(1280, 720)
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboardMinimal()
    stubSyncStrava()

    cy.intercept('GET', '/api/running/v1/gear', {
      statusCode: 200,
      body: {
        data: [
          {
            id: 'gear-both',
            name: 'Saucony Endorphin Pro 3',
            distance_m: 400000,
            retired: false,
            category: 'tempo',
            retirement_km: 800,
            notification_distance_m: 500000,
          },
        ],
      },
    }).as('getGearBoth')

    cy.visit('/main/running/dashboard')
    cy.wait('@getDashboardMinimal')
    cy.wait('@getGearBoth')
  })

  it('Manual tab shows "800.00 km" when retirement_km=800 (default tab when manual is set)', () => {
    // Default tab is Manual when retirement_km is set
    cy.get(`#${GEAR_IDS.gear_card}`).should('contain', 'Manual · 800.00 km')
  })

  it('Strava tab shows "500.00 km" when notification_distance_m=500000', () => {
    cy.get(`#${GEAR_IDS.gear_card}`).should('contain', 'Strava · 500.00 km')
  })

  it('clicking Strava tab when Manual is active switches displayed limit', () => {
    // Manual is the default; click Strava tab
    cy.get(`#${GEAR_IDS.gear_card}`)
      .contains('button', /^Strava/)
      .click()
    // After clicking Strava tab the Strava tab should be aria-pressed=true
    cy.get(`#${GEAR_IDS.gear_card}`)
      .contains('button', /^Strava/)
      .should('have.attr', 'aria-pressed', 'true')
  })
})

// ---------------------------------------------------------------------------
// G. Near retirement warning
// ---------------------------------------------------------------------------

describe('Running Gear UI — Near retirement warning', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.viewport(1280, 720)
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboardMinimal()
    stubSyncStrava()

    cy.intercept('GET', '/api/running/v1/gear', {
      statusCode: 200,
      body: {
        data: [
          {
            id: 'gear-near',
            name: 'HOKA Clifton 9',
            distance_m: 720000, // 720 km
            retired: false,
            category: 'daily',
            retirement_km: 800, // 90% threshold
            notification_distance_m: null,
          },
        ],
      },
    }).as('getGearNear')

    cy.visit('/main/running/dashboard')
    cy.wait('@getDashboardMinimal')
    cy.wait('@getGearNear')
  })

  it('shows "Nearing limit" text when distance >= 90% of retirement_km', () => {
    // 720/800 = 90% — exactly at threshold
    cy.get(`#${GEAR_IDS.gear_card}`).contains('Nearing limit').should('be.visible')
  })
})

// ---------------------------------------------------------------------------
// H. Edit form
// ---------------------------------------------------------------------------

describe('Running Gear UI — Edit form', () => {
  before(() => {
    cy.setupApiAuthCookies()
  })

  beforeEach(() => {
    cy.viewport(1280, 720)
    cy.setupApiAuthCookies()
    stubRtUsers()
    stubDashboardMinimal()
    stubSyncStrava()

    cy.intercept('GET', '/api/running/v1/gear', {
      statusCode: 200,
      body: {
        data: [
          {
            id: 'gear-edit',
            name: 'New Balance FuelCell',
            distance_m: 80000,
            retired: false,
            category: null,
            retirement_km: null,
            notification_distance_m: null,
          },
        ],
      },
    }).as('getGearEdit')

    cy.visit('/main/running/dashboard')
    cy.wait('@getDashboardMinimal')
    cy.wait('@getGearEdit')
  })

  it('clicking the edit pencil button opens the edit form', () => {
    cy.get(`#${GEAR_IDS.gear_card}`).find('button[aria-label^="Edit"]').click()
    cy.get(`#${GEAR_IDS.save_btn}`).should('be.visible')
  })

  it('#gearSaveBtn is present in the edit form', () => {
    cy.get(`#${GEAR_IDS.gear_card}`).find('button[aria-label^="Edit"]').click()
    cy.get(`#${GEAR_IDS.save_btn}`).should('exist')
    cy.get(`#${GEAR_IDS.save_btn}`).should('contain', 'Save')
  })

  it('Cancel button closes the edit form', () => {
    cy.get(`#${GEAR_IDS.gear_card}`).find('button[aria-label^="Edit"]').click()
    cy.get(`#${GEAR_IDS.save_btn}`).should('be.visible')

    cy.get(`#${GEAR_IDS.gear_card}`).find('button[aria-label="Cancel editing"]').click()

    cy.get(`#${GEAR_IDS.save_btn}`).should('not.exist')
  })
})
