// Generated by Cypress Author — 2026-05-25
// Covers: Running Tracker Performance Trends API
//   GET /api/running/v1/performance-trends — auth guard, response shape,
//   query param ?limit=, query param ?type=, field presence per item

describe('Running Performance Trends API — GET /api/running/v1/performance-trends', () => {
  beforeEach(() => {
    cy.setupApiAuthCookies()
  })

  it('returns 200 with data array when authenticated', () => {
    cy.request({
      method: 'GET',
      url: '/api/running/v1/performance-trends',
    }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body).to.have.property('data')
      expect(res.body.data).to.be.an('array')
    })
  })

  it('each item in data has started_at and distance_m fields', () => {
    cy.request({
      method: 'GET',
      url: '/api/running/v1/performance-trends',
    }).then((res) => {
      expect(res.status).to.eq(200)
      const items = res.body.data
      if (items.length === 0) {
        cy.log('No performance trend items — skipping field assertions')
        return
      }
      items.forEach((item) => {
        expect(item).to.have.property('started_at')
        expect(item).to.have.property('distance_m')
      })
    })
  })

  it('?limit=20 param is accepted and returns at most 20 items', () => {
    cy.request({
      method: 'GET',
      url: '/api/running/v1/performance-trends?limit=20',
    }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body.data).to.be.an('array')
      expect(res.body.data.length).to.be.lte(20)
    })
  })

  it('?type=Run filter param is accepted and returns 200', () => {
    cy.request({
      method: 'GET',
      url: '/api/running/v1/performance-trends?type=Run',
    }).then((res) => {
      expect(res.status).to.eq(200)
      expect(res.body.data).to.be.an('array')
    })
  })

  it('returns 401 when unauthenticated', () => {
    cy.clearCookies()
    cy.request({
      method: 'GET',
      url: '/api/running/v1/performance-trends',
      failOnStatusCode: false,
    }).then((res) => {
      expect(res.status).to.eq(401)
    })
  })
})
