// Generated by Cypress Author — 2026-08-10
Cypress.Commands.add('resetVo2maxTargetInDb', () => {
  return cy.getTestUserId().then((userId) => {
    return cy.task('resetVo2maxTarget', { userId })
  })
})
