// Generated by Cypress Author on 2026-07-06.
import constants from '../../../../../fixtures/app-constants.json'

const BASE = constants.endpoints.running_routes.list

Cypress.Commands.add('getRoutes', (qs = {}) => {
  return cy.apiRequestWithSession('GET', BASE, { qs })
})

Cypress.Commands.add('getRoutesNoAuth', () => {
  return cy.apiRequestNoAuth('GET', BASE)
})

Cypress.Commands.add('postRoute', (body) => {
  return cy.apiRequestWithSession('POST', BASE, { body })
})

Cypress.Commands.add('postRouteNoAuth', (body) => {
  return cy.apiRequestNoAuth('POST', BASE, { body })
})

Cypress.Commands.add('patchRoute', (id, body) => {
  return cy.apiRequestWithSession('PATCH', `${BASE}/${id}`, { body })
})

Cypress.Commands.add('patchRouteNoAuth', (id, body) => {
  return cy.apiRequestNoAuth('PATCH', `${BASE}/${id}`, { body })
})

Cypress.Commands.add('deleteRoute', (id) => {
  return cy.apiRequestWithSession('DELETE', `${BASE}/${id}`)
})

Cypress.Commands.add('deleteRouteNoAuth', (id) => {
  return cy.apiRequestNoAuth('DELETE', `${BASE}/${id}`)
})
