name: Cypress Tests

on:
  push:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build
        # pastikan di package.json ada: "build": "next build"

      - name: Start server in background
        run: npm run start &
        # atau: npx next start &
        # & biar server jalan di background

      - name: Wait for server
        run: |
          sleep 10
          # atau gunakan curl ping ke / setelah build

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: "http://localhost:3000"
          start: npm run start
          build: npm run build
